//type:fp
//options_all:--c++17
//remark:[5.1] Internal error in C-generating back end on missing address_taken flag
// 1/28/19  [EDGcpfe/18708]
//
// Internal error in C-generating back end on missing address_taken flag
//
// IL lowering previously failed to set the address_taken flag to TRUE when a
// temporary variable generated by IL lowering appeared under a reference cast.
// That, in turn, could trigger an internal error in the C-generating back end.
//
// This is now fixed.
struct S { void f() noexcept {} };
using PMF = void (S::*)();
void g() {
  static_cast<PMF&&>(&S::f);  // Previously triggered an internal error
}                             // in the C++-generating back end.
