//type:fp
//options_all:--c++11
//remark:[4.5] Defaulted move operations
// 3/20/12  [EDGcpfe/12216]
//
// Defaulted move operations
//
// In C++11 modes that permit the generation of move constructors and move
// assignment operators (see Changes entry of 3/16/12), the front end now
// permits such special members to be explicitly "defaulted".
//
// Such defaulted move operations are also permitted in GNU C++ mode with
// gnu_version >= 40500 (even though move operations are not generated by
// default when gnu_version < 40600).
struct MO { MO(MO&&); };
struct DM {
  DM(DM&&) = default;  // Now allowed in many C++11 modes.
  MO mo;
};
