//remark:Match correspondences across translation units
//type:fp
//name:
//options:
//options_all:-A --multi_trans_unit
//cases:
//source_files:d00139a_2.c d00139a_3.c
//input_files:
//output_files:
//ulimit:
//linker_options:
//execution_args:

// 14
// autogenerated

//cmdp -A -c --multi_trans_unit 1.c 2.c 3.c

namespace A {
	int f(char*) {return 1;}
	static int f(int) {return 2;}
}

using namespace A;

template <class T> struct B {
	int g1()
	{
		return f(sizeof(T));
	}
	int g2()
	{
		return f(sizeof(double));
	}
};

int main()
{
	B<double> b;

	if (b.g1() != 2)
		return 1;
	if (b.g2() != 2)
		return 2;

	return 0;
}

