#!/bin/bash

# Part of the EDG Compiler Project, under the Apache License v2.0 with LLVM
# Exceptions.
# See https://edgcpp.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

shell_path=$(command -v "$1")
if [ $? -eq 0 ] ; then
  # Execute the user's preferred shell
  exec $shell_path
else
  # Fallback to bash
  exec /bin/bash
fi
