/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
*                                                             /  | |  \       *
* Copyright 1996-2016 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/

/*
Redistribution and use in source and binary forms are permitted
provided that the above copyright notice and this paragraph are
duplicated in all source code forms.  The name of Edison Design
Group, Inc. may not be used to endorse or promote products derived
from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
Any use of this software is at the user's own risk.
*/

/*
This tool is used to generate (a portion of) the contents for a
predefined_macros.txt file in order to more completely emulate the predefined
macros that are defined by a version of Microsoft Visual Studio.  Microsoft
Visual Studio pre-defines a number of macros (see
https://msdn.microsoft.com/en-us/library/b0084kay(v=vs.140).aspx for a recent
list).  Some of these macros are pre-defined by the front end, namely:

  _CHAR_UNSIGNED
  __COUNTER__
  __cplusplus
  __cplusplus_cli
  __cplusplus_winrt
  _CPPRTTI
  __FUNCDNAME__
  __FUNCSIG__
  __FUNCTION__
  _INTEGRAL_MAX_BITS
  _MANAGED
  _M_CEE
  _MSC_BUILD
  _MSC_EXTENSIONS
  _MSC_FULL_VER
  _MSC_VER
  _NATIVE_WCHAR_T_DEFINED
  _WCHAR_T_DEFINED
  _WIN32
  _WIN64

Other macros not on the list above are deemed to be target-specific (or
at least not something for which the front end has knowledge).  In order to
more closely emulate the values generated by Microsoft Visual Studio, this
tool examines the setting for a number of predefined macros and writes their
values (to stdout) in the format expected for a predefined_macros.txt file.
The predefined_macros.txt file is then used by the front end (when
DEFAULT_USE_PREDEFINED_MACRO_FILE is TRUE), in Microsoft emulation mode,
to assign the same values to predefined macros.

Note that the output from this tool may depend on the command-line options
that are specified when compiling the tool, as well as the particular
hardware on which the compilation occurs.  It may be necessary to compile
this tool on a number of platforms, or with a number of different command-line
options, creating a different target-specific predefined_macros.txt file for
each case and using the --target option of the front end to select the proper
version of the file at run-time.

To use this tool, simply compile it with "cl" (with whatever command-line
options are relevant), run the resulting executable, and place the resulting
output in the relevant predefined_macros.txt file.  For example:

  C:\>cl make_win_predef_macro.c
  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.21901.1 for x86
  Copyright (C) Microsoft Corporation.  All rights reserved.

  make_win_predef_macro.c
  Microsoft (R) Incremental Linker Version 14.00.21901.1
  Copyright (C) Microsoft Corporation.  All rights reserved.

  /out:make_win_predef_macro.exe
  make_win_predef_macro.obj

  C:\>make_win_predef_macro > predefined_macros.txt

  C:\>

Then copy predefined_macros.txt to $EDG_BASE/lib (or a target-specific
version thereof).
*/

#include <stdio.h>

/* Produce a string version of the input. */
#define stringize(macro) #macro

/* Write the macro and its definition in the format expected in a
   predefined_macros.txt file. */
#define define_predefined_macro(macro) \
  printf("microsoft no %s %s\n", #macro, stringize(macro));

int main(int argc, char *argv[]) {
  /* Test all known non-standard predefined macros used by Microsoft Visual
     Studio and write those that are defined to stdout in the specified
     format. */
#ifdef _ATL_VER
  define_predefined_macro(_ATL_VER)
#endif /* _ATL_VER */
#ifdef __AVX__
  define_predefined_macro(__AVX__)
#endif /* __AVX__ */
#ifdef __AVX2__
  define_predefined_macro(__AVX2__)
#endif /* __AVX2__ */
#ifdef __CLR_VER
  define_predefined_macro(__CLR_VER)
#endif /* __CLR_VER */
#ifdef _CPPUNWIND
  define_predefined_macro(_CPPUNWIND)
#endif /* _CPPUNWIND */
#ifdef _DEBUG
  define_predefined_macro(_DEBUG)
#endif /* _DEBUG */
#ifdef _DLL
  define_predefined_macro(_DLL)
#endif /* _DLL */
#ifdef _M_AMD64
  define_predefined_macro(_M_AMD64)
#endif /* _M_AMD64 */
#ifdef _M_ARM
  define_predefined_macro(_M_ARM)
#endif /* _M_ARM */
#ifdef _M_ARM_FP
  define_predefined_macro(_M_ARM_FP)
#endif /* _M_ARM_FP */
#ifdef _M_CEE_PURE
  define_predefined_macro(_M_CEE_PURE)
#endif /* _M_CEE_PURE */
#ifdef _M_CEE_SAFE
  define_predefined_macro(_M_CEE_SAFE)
#endif /* _M_CEE_SAFE */
#ifdef _M_IX86
  define_predefined_macro(_M_IX86)
#endif /* _M_IX86 */
#ifdef _M_IX86_FP
  define_predefined_macro(_M_IX86_FP)
#endif /* _M_IX86_FP */
#ifdef _M_X64
  define_predefined_macro(_M_X64)
#endif /* _M_X64 */
#ifdef _MFC_VER
  define_predefined_macro(_MFC_VER)
#endif /* _MFC_VER */
#ifdef __MSVC_RUNTIME_CHECKS
  define_predefined_macro(__MSVC_RUNTIME_CHECKS)
#endif /* __MSVC_RUNTIME_CHECKS */
#ifdef _MT
  define_predefined_macro(_MT)
#endif /* _MT */
#ifdef _OPENMP
  define_predefined_macro(_OPENMP)
#endif /* _OPENMP */
#ifdef _VC_NODEFAULTLIB
  define_predefined_macro(_VC_NODEFAULTLIB)
#endif /* _VC_NODEFAULTLIB */
#ifdef _Wp64
  define_predefined_macro(_Wp64)
#endif /* _Wp64 */
  return 0;
}  /* main */

/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
*                                                             /  | |  \       *
* Copyright 1996-2016 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
