//type:fp
//options:--g++ --ms_extensions
//options_all:-W

/* Verify that the normal behavior for the following keywords holds.  These are
   not implemented as keywords upstream in GCC (meaning the shouldn't show up
   in the errors generated by gnats24385b.c, and shouldn't impact
   gnats24385.c), but the functionality needs to be preserved.

   This test helps ensure that if we fix our handling of these names to
   be identifier based rather than keyword based, we won't have a functionality
   regression. */

void foo() {
    __if_exists(bar) { }
    __if_not_exists(bar) { }
}

__declspec(selectany) int * pi1 = 0;
