//type:fp
//options:--clang --ms_extensions
//options_all:-W

/* Verify that the normal behavior for the following keywords holds.  These are
   not implemented as keywords upstream in Clang (meaning the shouldn't show up
   in the errors generated by gnats24385d.c, and shouldn't impact
   gnats24385c.c), but the functionality needs to be preserved.

   This test helps ensure that if we fix our handling of these names to
   be identifier based rather than keyword based, we won't have a functionality
   regression. */

void foo() {
  __assume(1);
  __noop(0);
}

void bar() {
  __try {
  }
  __except(1) {
  }
}

int __w64 a;
__int16 b;
__int64 c;

int * __unaligned d;
