//type: rp
//options: 
# 0 "./builtin-dynamic-object-size-16.c"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "./builtin-dynamic-object-size-16.c"




char ax2[];
# 1 "./builtin-object-size-16.c" 1
# 9 "./builtin-object-size-16.c"
static int nfails;
# 54 "./builtin-object-size-16.c"
typedef long unsigned int size_t;

extern char ax[];




extern char a0[0];
static char a1[1];
static char a2[2];
static char a9[9];






extern int ia0[0];
static int ia1[1];
static int ia9[9];






static char a2x2[2][2];
static char a3x5[3][5];

struct Sx { char n, a[]; } sx;
struct S0 { char n, a[0]; } s0;
struct S1 { char n, a[1]; } s1;
struct S2 { char n, a[2]; } s2;
struct S9 { char n, a[9]; } s9;

struct S2x2 { char n, a[2][2]; } s2x2;
struct S3x5 { char n, a[3][5]; } s3x5;

static __attribute__ ((noclone, noinline)) void
test_arrays ()
{
  do { do { if (__builtin_dynamic_object_size (ax, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax" ", %i) == %zu, got %zu\n", 95, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)-1), __builtin_dynamic_object_size (ax, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax" ", %i) == %zu, got %zu\n", 95, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)-1), __builtin_dynamic_object_size (ax, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax" ", %i) == %zu, got %zu\n", 95, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)0), __builtin_dynamic_object_size (ax, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax" ", %i) == %zu, got %zu\n", 95, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ax : (size_t)0), __builtin_dynamic_object_size (ax, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a0, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 97, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a0, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 97, 1, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a0, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 97, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a0, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 97, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ax2, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 98, 0, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax2, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 98, 1, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax2, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 98, 2, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax2, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 98, 3, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a1, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1" ", %i) == %zu, got %zu\n", 100, 0, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1), __builtin_dynamic_object_size (a1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1" ", %i) == %zu, got %zu\n", 100, 1, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1), __builtin_dynamic_object_size (a1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1" ", %i) == %zu, got %zu\n", 100, 2, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1), __builtin_dynamic_object_size (a1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1" ", %i) == %zu, got %zu\n", 100, 3, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1), __builtin_dynamic_object_size (a1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a2, 0) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2" ", %i) == %zu, got %zu\n", 101, 0, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2), __builtin_dynamic_object_size (a2, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2, 1) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2" ", %i) == %zu, got %zu\n", 101, 1, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2), __builtin_dynamic_object_size (a2, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2, 2) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2" ", %i) == %zu, got %zu\n", 101, 2, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2), __builtin_dynamic_object_size (a2, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2, 3) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2" ", %i) == %zu, got %zu\n", 101, 3, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2), __builtin_dynamic_object_size (a2, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a9, 0) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a9" ", %i) == %zu, got %zu\n", 102, 0, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9), __builtin_dynamic_object_size (a9, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a9, 1) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a9" ", %i) == %zu, got %zu\n", 102, 1, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9), __builtin_dynamic_object_size (a9, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a9, 2) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a9" ", %i) == %zu, got %zu\n", 102, 2, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9), __builtin_dynamic_object_size (a9, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a9, 3) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a9" ", %i) == %zu, got %zu\n", 102, 3, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9), __builtin_dynamic_object_size (a9, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a0, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 104, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a0, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 104, 1, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a0, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 104, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a0, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a0" ", %i) == %zu, got %zu\n", 104, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0), __builtin_dynamic_object_size (a0, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ax2, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 105, 0, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax2, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 105, 1, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax2, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 105, 2, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ax2, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ax2" ", %i) == %zu, got %zu\n", 105, 3, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1), __builtin_dynamic_object_size (ax2, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (ia0, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia0" ", %i) == %zu, got %zu\n", 107, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0), __builtin_dynamic_object_size (ia0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia0, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia0" ", %i) == %zu, got %zu\n", 107, 1, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0), __builtin_dynamic_object_size (ia0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia0, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia0" ", %i) == %zu, got %zu\n", 107, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0), __builtin_dynamic_object_size (ia0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia0, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia0" ", %i) == %zu, got %zu\n", 107, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0), __builtin_dynamic_object_size (ia0, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ia1, 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia1" ", %i) == %zu, got %zu\n", 108, 0, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4), __builtin_dynamic_object_size (ia1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia1, 1) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia1" ", %i) == %zu, got %zu\n", 108, 1, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4), __builtin_dynamic_object_size (ia1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia1, 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia1" ", %i) == %zu, got %zu\n", 108, 2, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4), __builtin_dynamic_object_size (ia1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia1, 3) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia1" ", %i) == %zu, got %zu\n", 108, 3, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4), __builtin_dynamic_object_size (ia1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ia9, 0) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia9" ", %i) == %zu, got %zu\n", 109, 0, ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36), __builtin_dynamic_object_size (ia9, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia9, 1) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia9" ", %i) == %zu, got %zu\n", 109, 1, ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36), __builtin_dynamic_object_size (ia9, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia9, 2) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia9" ", %i) == %zu, got %zu\n", 109, 2, ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36), __builtin_dynamic_object_size (ia9, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ia9, 3) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ia9" ", %i) == %zu, got %zu\n", 109, 3, ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36), __builtin_dynamic_object_size (ia9, 3)), ++nfails; } while (0); } while (0);




  do { do { if (__builtin_dynamic_object_size (a2x2, 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2x2" ", %i) == %zu, got %zu\n", 114, 0, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4), __builtin_dynamic_object_size (a2x2, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2x2, 1) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2x2" ", %i) == %zu, got %zu\n", 114, 1, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4), __builtin_dynamic_object_size (a2x2, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2x2, 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2x2" ", %i) == %zu, got %zu\n", 114, 2, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4), __builtin_dynamic_object_size (a2x2, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2x2, 3) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2x2" ", %i) == %zu, got %zu\n", 114, 3, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4), __builtin_dynamic_object_size (a2x2, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0], 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0]" ", %i) == %zu, got %zu\n", 115, 0, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4), __builtin_dynamic_object_size (&a2x2[0], 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0], 1) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0]" ", %i) == %zu, got %zu\n", 115, 1, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4), __builtin_dynamic_object_size (&a2x2[0], 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0], 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0]" ", %i) == %zu, got %zu\n", 115, 2, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4), __builtin_dynamic_object_size (&a2x2[0], 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0], 3) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0]" ", %i) == %zu, got %zu\n", 115, 3, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4), __builtin_dynamic_object_size (&a2x2[0], 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0][0], 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0]" ", %i) == %zu, got %zu\n", 116, 0, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)4), __builtin_dynamic_object_size (&a2x2[0][0], 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0], 1) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0]" ", %i) == %zu, got %zu\n", 116, 1, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)2), __builtin_dynamic_object_size (&a2x2[0][0], 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0], 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)4)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0]" ", %i) == %zu, got %zu\n", 116, 2, ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)4), __builtin_dynamic_object_size (&a2x2[0][0], 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0], 3) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0]" ", %i) == %zu, got %zu\n", 116, 3, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)2), __builtin_dynamic_object_size (&a2x2[0][0], 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2 + 1, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2 + 1" ", %i) == %zu, got %zu\n", 117, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0), __builtin_dynamic_object_size (&a2x2 + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2 + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2 + 1" ", %i) == %zu, got %zu\n", 117, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)-1), __builtin_dynamic_object_size (&a2x2 + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2 + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2 + 1" ", %i) == %zu, got %zu\n", 117, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0), __builtin_dynamic_object_size (&a2x2 + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2 + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2 + 1" ", %i) == %zu, got %zu\n", 117, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0), __builtin_dynamic_object_size (&a2x2 + 1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0] + 1, 0) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0] + 1" ", %i) == %zu, got %zu\n", 118, 0, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)2), __builtin_dynamic_object_size (&a2x2[0] + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0] + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0] + 1" ", %i) == %zu, got %zu\n", 118, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)-1), __builtin_dynamic_object_size (&a2x2[0] + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0] + 1, 2) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0] + 1" ", %i) == %zu, got %zu\n", 118, 2, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)2), __builtin_dynamic_object_size (&a2x2[0] + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0] + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0] + 1" ", %i) == %zu, got %zu\n", 118, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)0), __builtin_dynamic_object_size (&a2x2[0] + 1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0][0] + 1, 0) != ((size_t)3 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)3)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0] + 1" ", %i) == %zu, got %zu\n", 119, 0, ((size_t)3 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)3), __builtin_dynamic_object_size (&a2x2[0][0] + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0] + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0] + 1" ", %i) == %zu, got %zu\n", 119, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)-1), __builtin_dynamic_object_size (&a2x2[0][0] + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0] + 1, 2) != ((size_t)3 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)3)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0] + 1" ", %i) == %zu, got %zu\n", 119, 2, ((size_t)3 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)3), __builtin_dynamic_object_size (&a2x2[0][0] + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0] + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a2x2[0][0] + 1" ", %i) == %zu, got %zu\n", 119, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)0), __builtin_dynamic_object_size (&a2x2[0][0] + 1, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a3x5, 0) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a3x5" ", %i) == %zu, got %zu\n", 121, 0, ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15), __builtin_dynamic_object_size (a3x5, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a3x5, 1) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a3x5" ", %i) == %zu, got %zu\n", 121, 1, ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15), __builtin_dynamic_object_size (a3x5, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a3x5, 2) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a3x5" ", %i) == %zu, got %zu\n", 121, 2, ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15), __builtin_dynamic_object_size (a3x5, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a3x5, 3) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a3x5" ", %i) == %zu, got %zu\n", 121, 3, ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15), __builtin_dynamic_object_size (a3x5, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 0) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)15)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 0" ", %i) == %zu, got %zu\n", 122, 0, ((size_t)15 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)15), __builtin_dynamic_object_size (&a3x5[0][0] + 0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 1) != ((size_t)5 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)5)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 0" ", %i) == %zu, got %zu\n", 122, 1, ((size_t)5 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)5), __builtin_dynamic_object_size (&a3x5[0][0] + 0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 2) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)15)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 0" ", %i) == %zu, got %zu\n", 122, 2, ((size_t)15 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)15), __builtin_dynamic_object_size (&a3x5[0][0] + 0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 3) != ((size_t)5 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)5)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 0" ", %i) == %zu, got %zu\n", 122, 3, ((size_t)5 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)5), __builtin_dynamic_object_size (&a3x5[0][0] + 0, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 1, 0) != ((size_t)14 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)14)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 1" ", %i) == %zu, got %zu\n", 123, 0, ((size_t)14 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)14), __builtin_dynamic_object_size (&a3x5[0][0] + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 1" ", %i) == %zu, got %zu\n", 123, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)-1), __builtin_dynamic_object_size (&a3x5[0][0] + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 1, 2) != ((size_t)14 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)14)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 1" ", %i) == %zu, got %zu\n", 123, 2, ((size_t)14 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)14), __builtin_dynamic_object_size (&a3x5[0][0] + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a3x5[0][0] + 1" ", %i) == %zu, got %zu\n", 123, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)0), __builtin_dynamic_object_size (&a3x5[0][0] + 1, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a1 + 0, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 0" ", %i) == %zu, got %zu\n", 125, 0, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1), __builtin_dynamic_object_size (a1 + 0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 0, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 0" ", %i) == %zu, got %zu\n", 125, 1, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1), __builtin_dynamic_object_size (a1 + 0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 0, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 0" ", %i) == %zu, got %zu\n", 125, 2, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1), __builtin_dynamic_object_size (a1 + 0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 0, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 0" ", %i) == %zu, got %zu\n", 125, 3, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1), __builtin_dynamic_object_size (a1 + 0, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a1 + 1, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 1" ", %i) == %zu, got %zu\n", 126, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)0), __builtin_dynamic_object_size (a1 + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 1" ", %i) == %zu, got %zu\n", 126, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)-1), __builtin_dynamic_object_size (a1 + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 1" ", %i) == %zu, got %zu\n", 126, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)0), __builtin_dynamic_object_size (a1 + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 1" ", %i) == %zu, got %zu\n", 126, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 1 : (size_t)0), __builtin_dynamic_object_size (a1 + 1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a1 + 1, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a1 + 1" ", %i) == %zu, got %zu\n", 127, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0), __builtin_dynamic_object_size (&a1 + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a1 + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a1 + 1" ", %i) == %zu, got %zu\n", 127, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)-1), __builtin_dynamic_object_size (&a1 + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a1 + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a1 + 1" ", %i) == %zu, got %zu\n", 127, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0), __builtin_dynamic_object_size (&a1 + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&a1 + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&a1 + 1" ", %i) == %zu, got %zu\n", 127, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0), __builtin_dynamic_object_size (&a1 + 1, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (a1 + 2, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 2" ", %i) == %zu, got %zu\n", 131, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)0), __builtin_dynamic_object_size (a1 + 2, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 2, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 2" ", %i) == %zu, got %zu\n", 131, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)-1), __builtin_dynamic_object_size (a1 + 2, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 2, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 2" ", %i) == %zu, got %zu\n", 131, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)0), __builtin_dynamic_object_size (a1 + 2, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a1 + 2, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a1 + 2" ", %i) == %zu, got %zu\n", 131, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a1 + 2 : (size_t)0), __builtin_dynamic_object_size (a1 + 2, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a2 + 0, 0) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 0" ", %i) == %zu, got %zu\n", 133, 0, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2), __builtin_dynamic_object_size (a2 + 0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 0, 1) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 0" ", %i) == %zu, got %zu\n", 133, 1, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2), __builtin_dynamic_object_size (a2 + 0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 0, 2) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 0" ", %i) == %zu, got %zu\n", 133, 2, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2), __builtin_dynamic_object_size (a2 + 0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 0, 3) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 0" ", %i) == %zu, got %zu\n", 133, 3, ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2), __builtin_dynamic_object_size (a2 + 0, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a2 + 1, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 1" ", %i) == %zu, got %zu\n", 134, 0, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)1), __builtin_dynamic_object_size (a2 + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 1" ", %i) == %zu, got %zu\n", 134, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)-1), __builtin_dynamic_object_size (a2 + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 1, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 1" ", %i) == %zu, got %zu\n", 134, 2, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)1), __builtin_dynamic_object_size (a2 + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 1" ", %i) == %zu, got %zu\n", 134, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)0), __builtin_dynamic_object_size (a2 + 1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a2 + 2, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 2" ", %i) == %zu, got %zu\n", 135, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0), __builtin_dynamic_object_size (a2 + 2, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 2, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 2" ", %i) == %zu, got %zu\n", 135, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)-1), __builtin_dynamic_object_size (a2 + 2, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 2, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 2" ", %i) == %zu, got %zu\n", 135, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0), __builtin_dynamic_object_size (a2 + 2, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (a2 + 2, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "a2 + 2" ", %i) == %zu, got %zu\n", 135, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0), __builtin_dynamic_object_size (a2 + 2, 3)), ++nfails; } while (0); } while (0);
}

static __attribute__ ((noclone, noinline)) void
test_structs (struct Sx *psx, struct S0 *ps0, struct S1 *ps1, struct S9 *ps9)
{


  do { do { if (__builtin_dynamic_object_size (&sx, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&sx" ", %i) == %zu, got %zu\n", 143, 0, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&sx, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&sx, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&sx" ", %i) == %zu, got %zu\n", 143, 1, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&sx, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&sx, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&sx" ", %i) == %zu, got %zu\n", 143, 2, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&sx, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&sx, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&sx" ", %i) == %zu, got %zu\n", 143, 3, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&sx, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (psx, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx" ", %i) == %zu, got %zu\n", 147, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)-1), __builtin_dynamic_object_size (psx, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (psx, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx" ", %i) == %zu, got %zu\n", 147, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)-1), __builtin_dynamic_object_size (psx, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (psx, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx" ", %i) == %zu, got %zu\n", 147, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)0), __builtin_dynamic_object_size (psx, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (psx, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx" ", %i) == %zu, got %zu\n", 147, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx : (size_t)0), __builtin_dynamic_object_size (psx, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (sx.a, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "sx.a" ", %i) == %zu, got %zu\n", 151, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0), __builtin_dynamic_object_size (sx.a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (sx.a, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "sx.a" ", %i) == %zu, got %zu\n", 151, 1, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0), __builtin_dynamic_object_size (sx.a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (sx.a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "sx.a" ", %i) == %zu, got %zu\n", 151, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0), __builtin_dynamic_object_size (sx.a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (sx.a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "sx.a" ", %i) == %zu, got %zu\n", 151, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0), __builtin_dynamic_object_size (sx.a, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (psx->a, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx->a" ", %i) == %zu, got %zu\n", 155, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)-1), __builtin_dynamic_object_size (psx->a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (psx->a, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx->a" ", %i) == %zu, got %zu\n", 155, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)-1), __builtin_dynamic_object_size (psx->a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (psx->a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx->a" ", %i) == %zu, got %zu\n", 155, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)0), __builtin_dynamic_object_size (psx->a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (psx->a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "psx->a" ", %i) == %zu, got %zu\n", 155, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *psx->a : (size_t)0), __builtin_dynamic_object_size (psx->a, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (&s0, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s0" ", %i) == %zu, got %zu\n", 159, 0, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s0, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s0" ", %i) == %zu, got %zu\n", 159, 1, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s0, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s0" ", %i) == %zu, got %zu\n", 159, 2, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s0, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s0" ", %i) == %zu, got %zu\n", 159, 3, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s0, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (ps0, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0" ", %i) == %zu, got %zu\n", 163, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)-1), __builtin_dynamic_object_size (ps0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps0, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0" ", %i) == %zu, got %zu\n", 163, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)-1), __builtin_dynamic_object_size (ps0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps0, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0" ", %i) == %zu, got %zu\n", 163, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)0), __builtin_dynamic_object_size (ps0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps0, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0" ", %i) == %zu, got %zu\n", 163, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0 : (size_t)0), __builtin_dynamic_object_size (ps0, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (s0.a, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s0.a" ", %i) == %zu, got %zu\n", 167, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0), __builtin_dynamic_object_size (s0.a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s0.a, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s0.a" ", %i) == %zu, got %zu\n", 167, 1, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0), __builtin_dynamic_object_size (s0.a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s0.a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s0.a" ", %i) == %zu, got %zu\n", 167, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0), __builtin_dynamic_object_size (s0.a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s0.a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s0.a" ", %i) == %zu, got %zu\n", 167, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0), __builtin_dynamic_object_size (s0.a, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (ps0->a, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0->a" ", %i) == %zu, got %zu\n", 171, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)-1), __builtin_dynamic_object_size (ps0->a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps0->a, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0->a" ", %i) == %zu, got %zu\n", 171, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)-1), __builtin_dynamic_object_size (ps0->a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps0->a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0->a" ", %i) == %zu, got %zu\n", 171, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)0), __builtin_dynamic_object_size (ps0->a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps0->a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps0->a" ", %i) == %zu, got %zu\n", 171, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps0->a : (size_t)0), __builtin_dynamic_object_size (ps0->a, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (&s1, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s1" ", %i) == %zu, got %zu\n", 173, 0, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s1, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s1" ", %i) == %zu, got %zu\n", 173, 1, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s1, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s1" ", %i) == %zu, got %zu\n", 173, 2, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s1, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s1" ", %i) == %zu, got %zu\n", 173, 3, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s1.a, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a" ", %i) == %zu, got %zu\n", 174, 0, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1), __builtin_dynamic_object_size (s1.a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s1.a, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a" ", %i) == %zu, got %zu\n", 174, 1, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1), __builtin_dynamic_object_size (s1.a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s1.a, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a" ", %i) == %zu, got %zu\n", 174, 2, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1), __builtin_dynamic_object_size (s1.a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s1.a, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a" ", %i) == %zu, got %zu\n", 174, 3, ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1), __builtin_dynamic_object_size (s1.a, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s1.a + 1, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a + 1" ", %i) == %zu, got %zu\n", 175, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0), __builtin_dynamic_object_size (s1.a + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s1.a + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a + 1" ", %i) == %zu, got %zu\n", 175, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)-1), __builtin_dynamic_object_size (s1.a + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s1.a + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a + 1" ", %i) == %zu, got %zu\n", 175, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0), __builtin_dynamic_object_size (s1.a + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s1.a + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s1.a + 1" ", %i) == %zu, got %zu\n", 175, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0), __builtin_dynamic_object_size (s1.a + 1, 3)), ++nfails; } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (ps1, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1" ", %i) == %zu, got %zu\n", 179, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)-1), __builtin_dynamic_object_size (ps1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1" ", %i) == %zu, got %zu\n", 179, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)-1), __builtin_dynamic_object_size (ps1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1" ", %i) == %zu, got %zu\n", 179, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)0), __builtin_dynamic_object_size (ps1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1" ", %i) == %zu, got %zu\n", 179, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1 : (size_t)0), __builtin_dynamic_object_size (ps1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ps1->a, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a" ", %i) == %zu, got %zu\n", 180, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)-1), __builtin_dynamic_object_size (ps1->a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1->a, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a" ", %i) == %zu, got %zu\n", 180, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)-1), __builtin_dynamic_object_size (ps1->a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1->a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a" ", %i) == %zu, got %zu\n", 180, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)0), __builtin_dynamic_object_size (ps1->a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1->a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a" ", %i) == %zu, got %zu\n", 180, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a : (size_t)0), __builtin_dynamic_object_size (ps1->a, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ps1->a + 1, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a + 1" ", %i) == %zu, got %zu\n", 181, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)-1), __builtin_dynamic_object_size (ps1->a + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1->a + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a + 1" ", %i) == %zu, got %zu\n", 181, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)-1), __builtin_dynamic_object_size (ps1->a + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1->a + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a + 1" ", %i) == %zu, got %zu\n", 181, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)0), __builtin_dynamic_object_size (ps1->a + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps1->a + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps1->a + 1" ", %i) == %zu, got %zu\n", 181, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps1->a + 1 : (size_t)0), __builtin_dynamic_object_size (ps1->a + 1, 3)), ++nfails; } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (&s9, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s9" ", %i) == %zu, got %zu\n", 183, 0, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s9, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s9, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s9" ", %i) == %zu, got %zu\n", 183, 1, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s9, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s9, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s9" ", %i) == %zu, got %zu\n", 183, 2, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s9, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (&s9, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "&s9" ", %i) == %zu, got %zu\n", 183, 3, ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef), __builtin_dynamic_object_size (&s9, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a, 0) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a" ", %i) == %zu, got %zu\n", 184, 0, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9), __builtin_dynamic_object_size (s9.a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a, 1) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a" ", %i) == %zu, got %zu\n", 184, 1, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9), __builtin_dynamic_object_size (s9.a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a, 2) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a" ", %i) == %zu, got %zu\n", 184, 2, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9), __builtin_dynamic_object_size (s9.a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a, 3) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a" ", %i) == %zu, got %zu\n", 184, 3, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9), __builtin_dynamic_object_size (s9.a, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 0, 0) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 0" ", %i) == %zu, got %zu\n", 185, 0, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9), __builtin_dynamic_object_size (s9.a + 0, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 0, 1) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 0" ", %i) == %zu, got %zu\n", 185, 1, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9), __builtin_dynamic_object_size (s9.a + 0, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 0, 2) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 0" ", %i) == %zu, got %zu\n", 185, 2, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9), __builtin_dynamic_object_size (s9.a + 0, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 0, 3) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 0" ", %i) == %zu, got %zu\n", 185, 3, ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9), __builtin_dynamic_object_size (s9.a + 0, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 1, 0) != ((size_t)8 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)8)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 1" ", %i) == %zu, got %zu\n", 186, 0, ((size_t)8 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)8), __builtin_dynamic_object_size (s9.a + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 1" ", %i) == %zu, got %zu\n", 186, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)-1), __builtin_dynamic_object_size (s9.a + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 1, 2) != ((size_t)8 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)8)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 1" ", %i) == %zu, got %zu\n", 186, 2, ((size_t)8 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)8), __builtin_dynamic_object_size (s9.a + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 1" ", %i) == %zu, got %zu\n", 186, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)0), __builtin_dynamic_object_size (s9.a + 1, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 2, 0) != ((size_t)7 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)7)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 2" ", %i) == %zu, got %zu\n", 187, 0, ((size_t)7 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)7), __builtin_dynamic_object_size (s9.a + 2, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 2, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 2" ", %i) == %zu, got %zu\n", 187, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)-1), __builtin_dynamic_object_size (s9.a + 2, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 2, 2) != ((size_t)7 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)7)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 2" ", %i) == %zu, got %zu\n", 187, 2, ((size_t)7 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)7), __builtin_dynamic_object_size (s9.a + 2, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 2, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 2" ", %i) == %zu, got %zu\n", 187, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)0), __builtin_dynamic_object_size (s9.a + 2, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 9, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 9" ", %i) == %zu, got %zu\n", 188, 0, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0), __builtin_dynamic_object_size (s9.a + 9, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 9, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 9" ", %i) == %zu, got %zu\n", 188, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)-1), __builtin_dynamic_object_size (s9.a + 9, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 9, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 9" ", %i) == %zu, got %zu\n", 188, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0), __builtin_dynamic_object_size (s9.a + 9, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (s9.a + 9, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "s9.a + 9" ", %i) == %zu, got %zu\n", 188, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0), __builtin_dynamic_object_size (s9.a + 9, 3)), ++nfails; } while (0); } while (0);


  do { do { if (__builtin_dynamic_object_size (ps9, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9" ", %i) == %zu, got %zu\n", 191, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)-1), __builtin_dynamic_object_size (ps9, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9" ", %i) == %zu, got %zu\n", 191, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)-1), __builtin_dynamic_object_size (ps9, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9" ", %i) == %zu, got %zu\n", 191, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)0), __builtin_dynamic_object_size (ps9, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9" ", %i) == %zu, got %zu\n", 191, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9 : (size_t)0), __builtin_dynamic_object_size (ps9, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ps9->a, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a" ", %i) == %zu, got %zu\n", 192, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)-1), __builtin_dynamic_object_size (ps9->a, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9->a, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a" ", %i) == %zu, got %zu\n", 192, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)-1), __builtin_dynamic_object_size (ps9->a, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9->a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a" ", %i) == %zu, got %zu\n", 192, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)0), __builtin_dynamic_object_size (ps9->a, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9->a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a" ", %i) == %zu, got %zu\n", 192, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a : (size_t)0), __builtin_dynamic_object_size (ps9->a, 3)), ++nfails; } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ps9->a + 1, 0) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a + 1" ", %i) == %zu, got %zu\n", 193, 0, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)-1), __builtin_dynamic_object_size (ps9->a + 1, 0)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9->a + 1, 1) != ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)-1)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a + 1" ", %i) == %zu, got %zu\n", 193, 1, ((size_t)-1 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)-1), __builtin_dynamic_object_size (ps9->a + 1, 1)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9->a + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a + 1" ", %i) == %zu, got %zu\n", 193, 2, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)0), __builtin_dynamic_object_size (ps9->a + 1, 2)), ++nfails; } while (0); do { if (__builtin_dynamic_object_size (ps9->a + 1, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)0)) __builtin_printf ("FAIL: line %i: __builtin_object_size(" "ps9->a + 1" ", %i) == %zu, got %zu\n", 193, 3, ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ps9->a + 1 : (size_t)0), __builtin_dynamic_object_size (ps9->a + 1, 3)), ++nfails; } while (0); } while (0);
}

int
main()
{
  test_arrays ();

  test_structs (&sx, &s0, &s1, &s9);

  if (nfails)
    __builtin_abort ();

  return 0;
}
# 7 "./builtin-dynamic-object-size-16.c" 2
