//type: fp
//options: 
# 0 "./builtin-dynamic-object-size-17.c"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "./builtin-dynamic-object-size-17.c"



char ax2[];

# 1 "./builtin-object-size-17.c" 1
# 49 "./builtin-object-size-17.c"
typedef long unsigned int size_t;

extern char ax[];




extern char a0[0];
static char a1[1];
static char a2[2];
static char a9[9];






extern int ia0[0];
static int ia1[1];
static int ia9[9];






static char a2x2[2][2];
static char a3x5[3][5];

struct Sx { char n, a[]; } sx;
struct S0 { char n, a[0]; } s0;
struct S1 { char n, a[1]; } s1;
struct S2 { char n, a[2]; } s2;
struct S9 { char n, a[9]; } s9;

struct S2x2 { char n, a[2][2]; } s2x2;
struct S3x5 { char n, a[3][5]; } s3x5;

static __attribute__ ((noclone, noinline)) void
test_arrays ()
{
  do { do { if (__builtin_dynamic_object_size (ax2, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_90_type_0(void); failure_on_line_90_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ax2, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_90_type_1(void); failure_on_line_90_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ax2, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_90_type_2(void); failure_on_line_90_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ax2, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_90_type_3(void); failure_on_line_90_type_3(); } while (0); } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a1, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) do { extern void failure_on_line_92_type_0(void); failure_on_line_92_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a1, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) do { extern void failure_on_line_92_type_1(void); failure_on_line_92_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a1, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) do { extern void failure_on_line_92_type_2(void); failure_on_line_92_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a1, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 : (size_t)1)) do { extern void failure_on_line_92_type_3(void); failure_on_line_92_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a2, 0) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) do { extern void failure_on_line_93_type_0(void); failure_on_line_93_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2, 1) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) do { extern void failure_on_line_93_type_1(void); failure_on_line_93_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2, 2) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) do { extern void failure_on_line_93_type_2(void); failure_on_line_93_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2, 3) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 : (size_t)2)) do { extern void failure_on_line_93_type_3(void); failure_on_line_93_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a9, 0) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) do { extern void failure_on_line_94_type_0(void); failure_on_line_94_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a9, 1) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) do { extern void failure_on_line_94_type_1(void); failure_on_line_94_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a9, 2) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) do { extern void failure_on_line_94_type_2(void); failure_on_line_94_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a9, 3) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *a9 : (size_t)9)) do { extern void failure_on_line_94_type_3(void); failure_on_line_94_type_3(); } while (0); } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a0, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) do { extern void failure_on_line_96_type_0(void); failure_on_line_96_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a0, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) do { extern void failure_on_line_96_type_1(void); failure_on_line_96_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a0, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) do { extern void failure_on_line_96_type_2(void); failure_on_line_96_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a0, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a0 : (size_t)0)) do { extern void failure_on_line_96_type_3(void); failure_on_line_96_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ax2, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_97_type_0(void); failure_on_line_97_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ax2, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_97_type_1(void); failure_on_line_97_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ax2, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_97_type_2(void); failure_on_line_97_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ax2, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *ax2 : (size_t)1)) do { extern void failure_on_line_97_type_3(void); failure_on_line_97_type_3(); } while (0); } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (ia0, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) do { extern void failure_on_line_99_type_0(void); failure_on_line_99_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia0, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) do { extern void failure_on_line_99_type_1(void); failure_on_line_99_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia0, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) do { extern void failure_on_line_99_type_2(void); failure_on_line_99_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia0, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *ia0 : (size_t)0)) do { extern void failure_on_line_99_type_3(void); failure_on_line_99_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ia1, 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) do { extern void failure_on_line_100_type_0(void); failure_on_line_100_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia1, 1) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) do { extern void failure_on_line_100_type_1(void); failure_on_line_100_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia1, 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) do { extern void failure_on_line_100_type_2(void); failure_on_line_100_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia1, 3) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *ia1 : (size_t)4)) do { extern void failure_on_line_100_type_3(void); failure_on_line_100_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (ia9, 0) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) do { extern void failure_on_line_101_type_0(void); failure_on_line_101_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia9, 1) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) do { extern void failure_on_line_101_type_1(void); failure_on_line_101_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia9, 2) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) do { extern void failure_on_line_101_type_2(void); failure_on_line_101_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (ia9, 3) != ((size_t)36 == (size_t)0xdeadbeef ? sizeof *ia9 : (size_t)36)) do { extern void failure_on_line_101_type_3(void); failure_on_line_101_type_3(); } while (0); } while (0); } while (0);




  do { do { if (__builtin_dynamic_object_size (a2x2, 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) do { extern void failure_on_line_106_type_0(void); failure_on_line_106_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2x2, 1) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) do { extern void failure_on_line_106_type_1(void); failure_on_line_106_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2x2, 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) do { extern void failure_on_line_106_type_2(void); failure_on_line_106_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2x2, 3) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *a2x2 : (size_t)4)) do { extern void failure_on_line_106_type_3(void); failure_on_line_106_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0], 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) do { extern void failure_on_line_107_type_0(void); failure_on_line_107_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0], 1) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) do { extern void failure_on_line_107_type_1(void); failure_on_line_107_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0], 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) do { extern void failure_on_line_107_type_2(void); failure_on_line_107_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0], 3) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] : (size_t)4)) do { extern void failure_on_line_107_type_3(void); failure_on_line_107_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0][0], 0) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)4)) do { extern void failure_on_line_108_type_0(void); failure_on_line_108_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0], 1) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)2)) do { extern void failure_on_line_108_type_1(void); failure_on_line_108_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0], 2) != ((size_t)4 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)4)) do { extern void failure_on_line_108_type_2(void); failure_on_line_108_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0], 3) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] : (size_t)2)) do { extern void failure_on_line_108_type_3(void); failure_on_line_108_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2 + 1, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0)) do { extern void failure_on_line_109_type_0(void); failure_on_line_109_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2 + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a2x2 + 1 : (size_t)0)) do { extern void failure_on_line_109_type_2(void); failure_on_line_109_type_2(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0] + 1, 0) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)2)) do { extern void failure_on_line_110_type_0(void); failure_on_line_110_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0] + 1, 2) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *&a2x2[0] + 1 : (size_t)2)) do { extern void failure_on_line_110_type_2(void); failure_on_line_110_type_2(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a2x2[0][0] + 1, 0) != ((size_t)3 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)3)) do { extern void failure_on_line_111_type_0(void); failure_on_line_111_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a2x2[0][0] + 1, 2) != ((size_t)3 == (size_t)0xdeadbeef ? sizeof *&a2x2[0][0] + 1 : (size_t)3)) do { extern void failure_on_line_111_type_2(void); failure_on_line_111_type_2(); } while (0); } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a3x5, 0) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) do { extern void failure_on_line_113_type_0(void); failure_on_line_113_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a3x5, 1) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) do { extern void failure_on_line_113_type_1(void); failure_on_line_113_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a3x5, 2) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) do { extern void failure_on_line_113_type_2(void); failure_on_line_113_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a3x5, 3) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *a3x5 : (size_t)15)) do { extern void failure_on_line_113_type_3(void); failure_on_line_113_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 0) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)15)) do { extern void failure_on_line_114_type_0(void); failure_on_line_114_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 1) != ((size_t)5 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)5)) do { extern void failure_on_line_114_type_1(void); failure_on_line_114_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 2) != ((size_t)15 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)15)) do { extern void failure_on_line_114_type_2(void); failure_on_line_114_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 0, 3) != ((size_t)5 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 0 : (size_t)5)) do { extern void failure_on_line_114_type_3(void); failure_on_line_114_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 1, 0) != ((size_t)14 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)14)) do { extern void failure_on_line_115_type_0(void); failure_on_line_115_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a3x5[0][0] + 1, 2) != ((size_t)14 == (size_t)0xdeadbeef ? sizeof *&a3x5[0][0] + 1 : (size_t)14)) do { extern void failure_on_line_115_type_2(void); failure_on_line_115_type_2(); } while (0); } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (a1 + 0, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) do { extern void failure_on_line_117_type_0(void); failure_on_line_117_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a1 + 0, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) do { extern void failure_on_line_117_type_1(void); failure_on_line_117_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a1 + 0, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) do { extern void failure_on_line_117_type_2(void); failure_on_line_117_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a1 + 0, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a1 + 0 : (size_t)1)) do { extern void failure_on_line_117_type_3(void); failure_on_line_117_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (&a1 + 1, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0)) do { extern void failure_on_line_118_type_0(void); failure_on_line_118_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&a1 + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *&a1 + 1 : (size_t)0)) do { extern void failure_on_line_118_type_2(void); failure_on_line_118_type_2(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a2 + 0, 0) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) do { extern void failure_on_line_119_type_0(void); failure_on_line_119_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2 + 0, 1) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) do { extern void failure_on_line_119_type_1(void); failure_on_line_119_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2 + 0, 2) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) do { extern void failure_on_line_119_type_2(void); failure_on_line_119_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2 + 0, 3) != ((size_t)2 == (size_t)0xdeadbeef ? sizeof *a2 + 0 : (size_t)2)) do { extern void failure_on_line_119_type_3(void); failure_on_line_119_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a2 + 1, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)1)) do { extern void failure_on_line_120_type_0(void); failure_on_line_120_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2 + 1, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *a2 + 1 : (size_t)1)) do { extern void failure_on_line_120_type_2(void); failure_on_line_120_type_2(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (a2 + 2, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0)) do { extern void failure_on_line_121_type_0(void); failure_on_line_121_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (a2 + 2, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *a2 + 2 : (size_t)0)) do { extern void failure_on_line_121_type_2(void); failure_on_line_121_type_2(); } while (0); } while (0); } while (0);
}

static __attribute__ ((noclone, noinline)) void
test_structs (void)
{


  do { do { if (__builtin_dynamic_object_size (&sx, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_129_type_0(void); failure_on_line_129_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&sx, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_129_type_1(void); failure_on_line_129_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&sx, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_129_type_2(void); failure_on_line_129_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&sx, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&sx : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_129_type_3(void); failure_on_line_129_type_3(); } while (0); } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (sx.a, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) do { extern void failure_on_line_133_type_0(void); failure_on_line_133_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (sx.a, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) do { extern void failure_on_line_133_type_1(void); failure_on_line_133_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (sx.a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) do { extern void failure_on_line_133_type_2(void); failure_on_line_133_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (sx.a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *sx.a : (size_t)0)) do { extern void failure_on_line_133_type_3(void); failure_on_line_133_type_3(); } while (0); } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (&s0, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_137_type_0(void); failure_on_line_137_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s0, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_137_type_1(void); failure_on_line_137_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s0, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_137_type_2(void); failure_on_line_137_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s0, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s0 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_137_type_3(void); failure_on_line_137_type_3(); } while (0); } while (0); } while (0);



  do { do { if (__builtin_dynamic_object_size (s0.a, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) do { extern void failure_on_line_141_type_0(void); failure_on_line_141_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s0.a, 1) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) do { extern void failure_on_line_141_type_1(void); failure_on_line_141_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s0.a, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) do { extern void failure_on_line_141_type_2(void); failure_on_line_141_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s0.a, 3) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s0.a : (size_t)0)) do { extern void failure_on_line_141_type_3(void); failure_on_line_141_type_3(); } while (0); } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (&s1, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_143_type_0(void); failure_on_line_143_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s1, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_143_type_1(void); failure_on_line_143_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s1, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_143_type_2(void); failure_on_line_143_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s1, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s1 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_143_type_3(void); failure_on_line_143_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s1.a, 0) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) do { extern void failure_on_line_144_type_0(void); failure_on_line_144_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s1.a, 1) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) do { extern void failure_on_line_144_type_1(void); failure_on_line_144_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s1.a, 2) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) do { extern void failure_on_line_144_type_2(void); failure_on_line_144_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s1.a, 3) != ((size_t)1 == (size_t)0xdeadbeef ? sizeof *s1.a : (size_t)1)) do { extern void failure_on_line_144_type_3(void); failure_on_line_144_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s1.a + 1, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0)) do { extern void failure_on_line_145_type_0(void); failure_on_line_145_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s1.a + 1, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s1.a + 1 : (size_t)0)) do { extern void failure_on_line_145_type_2(void); failure_on_line_145_type_2(); } while (0); } while (0); } while (0);

  do { do { if (__builtin_dynamic_object_size (&s9, 0) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_147_type_0(void); failure_on_line_147_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s9, 1) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_147_type_1(void); failure_on_line_147_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s9, 2) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_147_type_2(void); failure_on_line_147_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (&s9, 3) != ((size_t)(size_t)0xdeadbeef == (size_t)0xdeadbeef ? sizeof *&s9 : (size_t)(size_t)0xdeadbeef)) do { extern void failure_on_line_147_type_3(void); failure_on_line_147_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a, 0) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) do { extern void failure_on_line_148_type_0(void); failure_on_line_148_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a, 1) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) do { extern void failure_on_line_148_type_1(void); failure_on_line_148_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a, 2) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) do { extern void failure_on_line_148_type_2(void); failure_on_line_148_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a, 3) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a : (size_t)9)) do { extern void failure_on_line_148_type_3(void); failure_on_line_148_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 0, 0) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) do { extern void failure_on_line_149_type_0(void); failure_on_line_149_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a + 0, 1) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) do { extern void failure_on_line_149_type_1(void); failure_on_line_149_type_1(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a + 0, 2) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) do { extern void failure_on_line_149_type_2(void); failure_on_line_149_type_2(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a + 0, 3) != ((size_t)9 == (size_t)0xdeadbeef ? sizeof *s9.a + 0 : (size_t)9)) do { extern void failure_on_line_149_type_3(void); failure_on_line_149_type_3(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 1, 0) != ((size_t)8 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)8)) do { extern void failure_on_line_150_type_0(void); failure_on_line_150_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a + 1, 2) != ((size_t)8 == (size_t)0xdeadbeef ? sizeof *s9.a + 1 : (size_t)8)) do { extern void failure_on_line_150_type_2(void); failure_on_line_150_type_2(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 2, 0) != ((size_t)7 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)7)) do { extern void failure_on_line_151_type_0(void); failure_on_line_151_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a + 2, 2) != ((size_t)7 == (size_t)0xdeadbeef ? sizeof *s9.a + 2 : (size_t)7)) do { extern void failure_on_line_151_type_2(void); failure_on_line_151_type_2(); } while (0); } while (0); } while (0);
  do { do { if (__builtin_dynamic_object_size (s9.a + 9, 0) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0)) do { extern void failure_on_line_152_type_0(void); failure_on_line_152_type_0(); } while (0); } while (0); do { if (__builtin_dynamic_object_size (s9.a + 9, 2) != ((size_t)0 == (size_t)0xdeadbeef ? sizeof *s9.a + 9 : (size_t)0)) do { extern void failure_on_line_152_type_2(void); failure_on_line_152_type_2(); } while (0); } while (0); } while (0);
}

int
main()
{
  test_arrays ();
  test_structs ();

  return 0;
}
# 7 "./builtin-dynamic-object-size-17.c" 2
