//type: fp
//options: 
# 0 "./strlenopt-50.c"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "./strlenopt-50.c"





# 1 "./strlenopt.h" 1





typedef long unsigned int size_t;
extern void abort (void);
void *calloc (size_t, size_t);
void *malloc (size_t);
void free (void *);
char *strdup (const char *);
size_t strlen (const char *);
size_t strnlen (const char *, size_t);
void *memcpy (void *__restrict, const void *__restrict, size_t);
void *memmove (void *, const void *, size_t);
char *strcpy (char *__restrict, const char *__restrict);
char *strcat (char *__restrict, const char *__restrict);
char *strchr (const char *, int);
int strcmp (const char *, const char *);
int strncmp (const char *, const char *, size_t);
void *memset (void *, int, size_t);
int memcmp (const void *, const void *, size_t);
int strcmp (const char *, const char *);





int sprintf (char * __restrict, const char *__restrict, ...);
int snprintf (char * __restrict, size_t, const char *__restrict, ...);
# 7 "./strlenopt-50.c" 2
# 31 "./strlenopt-50.c"
const char a[] = "1\00012\000123\0001234\0";
const char b[20] = "1\00012\000123\0001234\0";

void test_literal (void)
{


  if (!(strlen ("1\00012\000123\0001234\0") == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_38 (void); call_in_true_branch_not_eliminated_on_line_38(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_38 (void); call_in_true_branch_not_eliminated_on_line_38(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 2) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_38 (void); call_in_true_branch_not_eliminated_on_line_38(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 3) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_38 (void); call_in_true_branch_not_eliminated_on_line_38(); } while (0); else (void)0;
  if (!(strlen ("1\00012\000123\0001234\0" + 4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_39 (void); call_in_true_branch_not_eliminated_on_line_39(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 5) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_39 (void); call_in_true_branch_not_eliminated_on_line_39(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 6) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_39 (void); call_in_true_branch_not_eliminated_on_line_39(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 7) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_39 (void); call_in_true_branch_not_eliminated_on_line_39(); } while (0); else (void)0;
  if (!(strlen ("1\00012\000123\0001234\0" + 8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_40 (void); call_in_true_branch_not_eliminated_on_line_40(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 9) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_40 (void); call_in_true_branch_not_eliminated_on_line_40(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 10) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_40 (void); call_in_true_branch_not_eliminated_on_line_40(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 11) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_40 (void); call_in_true_branch_not_eliminated_on_line_40(); } while (0); else (void)0;
  if (!(strlen ("1\00012\000123\0001234\0" + 12) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_41 (void); call_in_true_branch_not_eliminated_on_line_41(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 13) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_41 (void); call_in_true_branch_not_eliminated_on_line_41(); } while (0); else (void)0; if (!(strlen ("1\00012\000123\0001234\0" + 14) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_41 (void); call_in_true_branch_not_eliminated_on_line_41(); } while (0); else (void)0;

  if (!(strlen (&("1\00012\000123\0001234\0"[0])) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_43 (void); call_in_true_branch_not_eliminated_on_line_43(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 1])) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_43 (void); call_in_true_branch_not_eliminated_on_line_43(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 2])) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_43 (void); call_in_true_branch_not_eliminated_on_line_43(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[ 3])) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_44 (void); call_in_true_branch_not_eliminated_on_line_44(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 4])) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_44 (void); call_in_true_branch_not_eliminated_on_line_44(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 5])) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_44 (void); call_in_true_branch_not_eliminated_on_line_44(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[ 6])) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_45 (void); call_in_true_branch_not_eliminated_on_line_45(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 7])) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_45 (void); call_in_true_branch_not_eliminated_on_line_45(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 8])) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_45 (void); call_in_true_branch_not_eliminated_on_line_45(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[ 9])) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_46 (void); call_in_true_branch_not_eliminated_on_line_46(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[10])) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_46 (void); call_in_true_branch_not_eliminated_on_line_46(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[11])) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_46 (void); call_in_true_branch_not_eliminated_on_line_46(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[12])) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_47 (void); call_in_true_branch_not_eliminated_on_line_47(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[13])) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_47 (void); call_in_true_branch_not_eliminated_on_line_47(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[14])) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_47 (void); call_in_true_branch_not_eliminated_on_line_47(); } while (0); else (void)0;

  if (!(strlen (&("1\00012\000123\0001234\0"[0]) + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_49 (void); call_in_true_branch_not_eliminated_on_line_49(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 1]) + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_49 (void); call_in_true_branch_not_eliminated_on_line_49(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 2]) + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_49 (void); call_in_true_branch_not_eliminated_on_line_49(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[ 3]) + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_50 (void); call_in_true_branch_not_eliminated_on_line_50(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 4]) + 1) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_50 (void); call_in_true_branch_not_eliminated_on_line_50(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 5]) + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_50 (void); call_in_true_branch_not_eliminated_on_line_50(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[ 6]) + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_51 (void); call_in_true_branch_not_eliminated_on_line_51(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 7]) + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_51 (void); call_in_true_branch_not_eliminated_on_line_51(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[ 8]) + 1) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_51 (void); call_in_true_branch_not_eliminated_on_line_51(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[ 9]) + 1) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_52 (void); call_in_true_branch_not_eliminated_on_line_52(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[10]) + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_52 (void); call_in_true_branch_not_eliminated_on_line_52(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[11]) + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_52 (void); call_in_true_branch_not_eliminated_on_line_52(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[12]) + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_53 (void); call_in_true_branch_not_eliminated_on_line_53(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[13]) + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_53 (void); call_in_true_branch_not_eliminated_on_line_53(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[13]) - 13) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_53 (void); call_in_true_branch_not_eliminated_on_line_53(); } while (0); else (void)0;
  if (!(strlen (&("1\00012\000123\0001234\0"[13]) - 12) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_54 (void); call_in_true_branch_not_eliminated_on_line_54(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[13]) - 11) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_54 (void); call_in_true_branch_not_eliminated_on_line_54(); } while (0); else (void)0; if (!(strlen (&("1\00012\000123\0001234\0"[13]) - 10) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_54 (void); call_in_true_branch_not_eliminated_on_line_54(); } while (0); else (void)0;
}

void test_array (void)
{


  if (!(strlen (a) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_61 (void); call_in_true_branch_not_eliminated_on_line_61(); } while (0); else (void)0; if (!(strlen (a + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_61 (void); call_in_true_branch_not_eliminated_on_line_61(); } while (0); else (void)0; if (!(strlen (a + 2) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_61 (void); call_in_true_branch_not_eliminated_on_line_61(); } while (0); else (void)0; if (!(strlen (a + 3) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_61 (void); call_in_true_branch_not_eliminated_on_line_61(); } while (0); else (void)0;
  if (!(strlen (a + 4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_62 (void); call_in_true_branch_not_eliminated_on_line_62(); } while (0); else (void)0; if (!(strlen (a + 5) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_62 (void); call_in_true_branch_not_eliminated_on_line_62(); } while (0); else (void)0; if (!(strlen (a + 6) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_62 (void); call_in_true_branch_not_eliminated_on_line_62(); } while (0); else (void)0; if (!(strlen (a + 7) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_62 (void); call_in_true_branch_not_eliminated_on_line_62(); } while (0); else (void)0;
  if (!(strlen (a + 8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_63 (void); call_in_true_branch_not_eliminated_on_line_63(); } while (0); else (void)0; if (!(strlen (a + 9) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_63 (void); call_in_true_branch_not_eliminated_on_line_63(); } while (0); else (void)0; if (!(strlen (a + 10) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_63 (void); call_in_true_branch_not_eliminated_on_line_63(); } while (0); else (void)0; if (!(strlen (a + 11) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_63 (void); call_in_true_branch_not_eliminated_on_line_63(); } while (0); else (void)0;
  if (!(strlen (a + 12) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_64 (void); call_in_true_branch_not_eliminated_on_line_64(); } while (0); else (void)0; if (!(strlen (a + 13) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_64 (void); call_in_true_branch_not_eliminated_on_line_64(); } while (0); else (void)0; if (!(strlen (a + 14) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_64 (void); call_in_true_branch_not_eliminated_on_line_64(); } while (0); else (void)0;




  if (!(strlen (b) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_69 (void); call_in_true_branch_not_eliminated_on_line_69(); } while (0); else (void)0; if (!(strlen (b + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_69 (void); call_in_true_branch_not_eliminated_on_line_69(); } while (0); else (void)0; if (!(strlen (b + 2) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_69 (void); call_in_true_branch_not_eliminated_on_line_69(); } while (0); else (void)0; if (!(strlen (b + 3) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_69 (void); call_in_true_branch_not_eliminated_on_line_69(); } while (0); else (void)0;
  if (!(strlen (b + 4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_70 (void); call_in_true_branch_not_eliminated_on_line_70(); } while (0); else (void)0; if (!(strlen (b + 5) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_70 (void); call_in_true_branch_not_eliminated_on_line_70(); } while (0); else (void)0; if (!(strlen (b + 6) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_70 (void); call_in_true_branch_not_eliminated_on_line_70(); } while (0); else (void)0; if (!(strlen (b + 7) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_70 (void); call_in_true_branch_not_eliminated_on_line_70(); } while (0); else (void)0;
  if (!(strlen (b + 8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_71 (void); call_in_true_branch_not_eliminated_on_line_71(); } while (0); else (void)0; if (!(strlen (b + 9) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_71 (void); call_in_true_branch_not_eliminated_on_line_71(); } while (0); else (void)0; if (!(strlen (b + 10) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_71 (void); call_in_true_branch_not_eliminated_on_line_71(); } while (0); else (void)0; if (!(strlen (b + 11) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_71 (void); call_in_true_branch_not_eliminated_on_line_71(); } while (0); else (void)0;
  if (!(strlen (b + 12) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_72 (void); call_in_true_branch_not_eliminated_on_line_72(); } while (0); else (void)0; if (!(strlen (b + 13) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_72 (void); call_in_true_branch_not_eliminated_on_line_72(); } while (0); else (void)0; if (!(strlen (b + 14) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_72 (void); call_in_true_branch_not_eliminated_on_line_72(); } while (0); else (void)0; if (!(strlen (b + 15) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_72 (void); call_in_true_branch_not_eliminated_on_line_72(); } while (0); else (void)0;
  if (!(strlen (b + 16) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_73 (void); call_in_true_branch_not_eliminated_on_line_73(); } while (0); else (void)0; if (!(strlen (b + 17) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_73 (void); call_in_true_branch_not_eliminated_on_line_73(); } while (0); else (void)0; if (!(strlen (b + 18) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_73 (void); call_in_true_branch_not_eliminated_on_line_73(); } while (0); else (void)0; if (!(strlen (b + 19) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_73 (void); call_in_true_branch_not_eliminated_on_line_73(); } while (0); else (void)0;
}

void test_array_ref_plus (void)
{



  if (!(strlen (&a[ 0]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_81 (void); call_in_true_branch_not_eliminated_on_line_81(); } while (0); else (void)0; if (!(strlen (&a[ 0] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_81 (void); call_in_true_branch_not_eliminated_on_line_81(); } while (0); else (void)0;
  if (!(strlen (&a[ 1]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_82 (void); call_in_true_branch_not_eliminated_on_line_82(); } while (0); else (void)0; if (!(strlen (&a[ 1] + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_82 (void); call_in_true_branch_not_eliminated_on_line_82(); } while (0); else (void)0;
  if (!(strlen (&a[ 2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_83 (void); call_in_true_branch_not_eliminated_on_line_83(); } while (0); else (void)0; if (!(strlen (&a[ 2] + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_83 (void); call_in_true_branch_not_eliminated_on_line_83(); } while (0); else (void)0; if (!(strlen (&a[ 2] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_83 (void); call_in_true_branch_not_eliminated_on_line_83(); } while (0); else (void)0;
  if (!(strlen (&a[ 3]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_84 (void); call_in_true_branch_not_eliminated_on_line_84(); } while (0); else (void)0; if (!(strlen (&a[ 3] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_84 (void); call_in_true_branch_not_eliminated_on_line_84(); } while (0); else (void)0;
  if (!(strlen (&a[ 4]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_85 (void); call_in_true_branch_not_eliminated_on_line_85(); } while (0); else (void)0; if (!(strlen (&a[ 4] + 1) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_85 (void); call_in_true_branch_not_eliminated_on_line_85(); } while (0); else (void)0;
  if (!(strlen (&a[ 5]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_86 (void); call_in_true_branch_not_eliminated_on_line_86(); } while (0); else (void)0; if (!(strlen (&a[ 5] + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_86 (void); call_in_true_branch_not_eliminated_on_line_86(); } while (0); else (void)0;
  if (!(strlen (&a[ 5] + 2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_87 (void); call_in_true_branch_not_eliminated_on_line_87(); } while (0); else (void)0; if (!(strlen (&a[ 5] + 3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_87 (void); call_in_true_branch_not_eliminated_on_line_87(); } while (0); else (void)0; if (!(strlen (&a[ 5] + 4) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_87 (void); call_in_true_branch_not_eliminated_on_line_87(); } while (0); else (void)0;
  if (!(strlen (&a[ 6]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_88 (void); call_in_true_branch_not_eliminated_on_line_88(); } while (0); else (void)0; if (!(strlen (&a[ 6] + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_88 (void); call_in_true_branch_not_eliminated_on_line_88(); } while (0); else (void)0; if (!(strlen (&a[ 6] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_88 (void); call_in_true_branch_not_eliminated_on_line_88(); } while (0); else (void)0;
  if (!(strlen (&a[ 7]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_89 (void); call_in_true_branch_not_eliminated_on_line_89(); } while (0); else (void)0; if (!(strlen (&a[ 7] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_89 (void); call_in_true_branch_not_eliminated_on_line_89(); } while (0); else (void)0;
  if (!(strlen (&a[ 8]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_90 (void); call_in_true_branch_not_eliminated_on_line_90(); } while (0); else (void)0; if (!(strlen (&a[ 8] + 1) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_90 (void); call_in_true_branch_not_eliminated_on_line_90(); } while (0); else (void)0;
  if (!(strlen (&a[ 9]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_91 (void); call_in_true_branch_not_eliminated_on_line_91(); } while (0); else (void)0; if (!(strlen (&a[ 9] + 1) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_91 (void); call_in_true_branch_not_eliminated_on_line_91(); } while (0); else (void)0; if (!(strlen (&a[ 9] + 2) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_91 (void); call_in_true_branch_not_eliminated_on_line_91(); } while (0); else (void)0;
  if (!(strlen (&a[ 9] + 3) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_92 (void); call_in_true_branch_not_eliminated_on_line_92(); } while (0); else (void)0; if (!(strlen (&a[ 9] + 4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_92 (void); call_in_true_branch_not_eliminated_on_line_92(); } while (0); else (void)0; if (!(strlen (&a[ 9] + 5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_92 (void); call_in_true_branch_not_eliminated_on_line_92(); } while (0); else (void)0;
  if (!(strlen (&a[10]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_93 (void); call_in_true_branch_not_eliminated_on_line_93(); } while (0); else (void)0; if (!(strlen (&a[10] + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_93 (void); call_in_true_branch_not_eliminated_on_line_93(); } while (0); else (void)0; if (!(strlen (&a[10] + 2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_93 (void); call_in_true_branch_not_eliminated_on_line_93(); } while (0); else (void)0;
  if (!(strlen (&a[10] + 3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_94 (void); call_in_true_branch_not_eliminated_on_line_94(); } while (0); else (void)0; if (!(strlen (&a[10] + 4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_94 (void); call_in_true_branch_not_eliminated_on_line_94(); } while (0); else (void)0;
  if (!(strlen (&a[11]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_95 (void); call_in_true_branch_not_eliminated_on_line_95(); } while (0); else (void)0; if (!(strlen (&a[11] + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_95 (void); call_in_true_branch_not_eliminated_on_line_95(); } while (0); else (void)0; if (!(strlen (&a[11] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_95 (void); call_in_true_branch_not_eliminated_on_line_95(); } while (0); else (void)0;
  if (!(strlen (&a[12]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_96 (void); call_in_true_branch_not_eliminated_on_line_96(); } while (0); else (void)0; if (!(strlen (&a[12] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_96 (void); call_in_true_branch_not_eliminated_on_line_96(); } while (0); else (void)0; if (!(strlen (&a[12] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_96 (void); call_in_true_branch_not_eliminated_on_line_96(); } while (0); else (void)0;
  if (!(strlen (&a[13]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_97 (void); call_in_true_branch_not_eliminated_on_line_97(); } while (0); else (void)0; if (!(strlen (&a[13] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_97 (void); call_in_true_branch_not_eliminated_on_line_97(); } while (0); else (void)0;
  if (!(strlen (&a[14]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_98 (void); call_in_true_branch_not_eliminated_on_line_98(); } while (0); else (void)0;
}

void test_array_ref (void)
{
  if (!(strlen (&a[ 0]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_103 (void); call_in_true_branch_not_eliminated_on_line_103(); } while (0); else (void)0; if (!(strlen (&a[ 1]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_103 (void); call_in_true_branch_not_eliminated_on_line_103(); } while (0); else (void)0; if (!(strlen (&a[ 2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_103 (void); call_in_true_branch_not_eliminated_on_line_103(); } while (0); else (void)0; if (!(strlen (&a[ 3]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_103 (void); call_in_true_branch_not_eliminated_on_line_103(); } while (0); else (void)0;
  if (!(strlen (&a[ 4]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_104 (void); call_in_true_branch_not_eliminated_on_line_104(); } while (0); else (void)0; if (!(strlen (&a[ 5]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_104 (void); call_in_true_branch_not_eliminated_on_line_104(); } while (0); else (void)0; if (!(strlen (&a[ 6]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_104 (void); call_in_true_branch_not_eliminated_on_line_104(); } while (0); else (void)0; if (!(strlen (&a[ 7]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_104 (void); call_in_true_branch_not_eliminated_on_line_104(); } while (0); else (void)0;
  if (!(strlen (&a[ 8]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_105 (void); call_in_true_branch_not_eliminated_on_line_105(); } while (0); else (void)0; if (!(strlen (&a[ 9]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_105 (void); call_in_true_branch_not_eliminated_on_line_105(); } while (0); else (void)0; if (!(strlen (&a[10]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_105 (void); call_in_true_branch_not_eliminated_on_line_105(); } while (0); else (void)0; if (!(strlen (&a[11]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_105 (void); call_in_true_branch_not_eliminated_on_line_105(); } while (0); else (void)0;
  if (!(strlen (&a[12]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_106 (void); call_in_true_branch_not_eliminated_on_line_106(); } while (0); else (void)0; if (!(strlen (&a[13]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_106 (void); call_in_true_branch_not_eliminated_on_line_106(); } while (0); else (void)0; if (!(strlen (&a[14]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_106 (void); call_in_true_branch_not_eliminated_on_line_106(); } while (0); else (void)0;

  if (!(strlen (&b[ 0]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_108 (void); call_in_true_branch_not_eliminated_on_line_108(); } while (0); else (void)0; if (!(strlen (&b[ 1]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_108 (void); call_in_true_branch_not_eliminated_on_line_108(); } while (0); else (void)0; if (!(strlen (&b[ 2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_108 (void); call_in_true_branch_not_eliminated_on_line_108(); } while (0); else (void)0; if (!(strlen (&b[ 3]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_108 (void); call_in_true_branch_not_eliminated_on_line_108(); } while (0); else (void)0;
  if (!(strlen (&b[ 4]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_109 (void); call_in_true_branch_not_eliminated_on_line_109(); } while (0); else (void)0; if (!(strlen (&b[ 5]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_109 (void); call_in_true_branch_not_eliminated_on_line_109(); } while (0); else (void)0; if (!(strlen (&b[ 6]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_109 (void); call_in_true_branch_not_eliminated_on_line_109(); } while (0); else (void)0; if (!(strlen (&b[ 7]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_109 (void); call_in_true_branch_not_eliminated_on_line_109(); } while (0); else (void)0;
  if (!(strlen (&b[ 8]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_110 (void); call_in_true_branch_not_eliminated_on_line_110(); } while (0); else (void)0; if (!(strlen (&b[ 9]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_110 (void); call_in_true_branch_not_eliminated_on_line_110(); } while (0); else (void)0; if (!(strlen (&b[10]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_110 (void); call_in_true_branch_not_eliminated_on_line_110(); } while (0); else (void)0; if (!(strlen (&b[11]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_110 (void); call_in_true_branch_not_eliminated_on_line_110(); } while (0); else (void)0;
  if (!(strlen (&b[12]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_111 (void); call_in_true_branch_not_eliminated_on_line_111(); } while (0); else (void)0; if (!(strlen (&b[13]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_111 (void); call_in_true_branch_not_eliminated_on_line_111(); } while (0); else (void)0; if (!(strlen (&b[14]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_111 (void); call_in_true_branch_not_eliminated_on_line_111(); } while (0); else (void)0; if (!(strlen (&b[15]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_111 (void); call_in_true_branch_not_eliminated_on_line_111(); } while (0); else (void)0;
  if (!(strlen (&b[16]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_112 (void); call_in_true_branch_not_eliminated_on_line_112(); } while (0); else (void)0; if (!(strlen (&b[17]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_112 (void); call_in_true_branch_not_eliminated_on_line_112(); } while (0); else (void)0; if (!(strlen (&b[18]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_112 (void); call_in_true_branch_not_eliminated_on_line_112(); } while (0); else (void)0; if (!(strlen (&b[19]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_112 (void); call_in_true_branch_not_eliminated_on_line_112(); } while (0); else (void)0;
}
