//type: fp
//options: 
# 0 "./strlenopt-52.c"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "./strlenopt-52.c"




# 1 "./strlenopt.h" 1





typedef long unsigned int size_t;
extern void abort (void);
void *calloc (size_t, size_t);
void *malloc (size_t);
void free (void *);
char *strdup (const char *);
size_t strlen (const char *);
size_t strnlen (const char *, size_t);
void *memcpy (void *__restrict, const void *__restrict, size_t);
void *memmove (void *, const void *, size_t);
char *strcpy (char *__restrict, const char *__restrict);
char *strcat (char *__restrict, const char *__restrict);
char *strchr (const char *, int);
int strcmp (const char *, const char *);
int strncmp (const char *, const char *, size_t);
void *memset (void *, int, size_t);
int memcmp (const void *, const void *, size_t);
int strcmp (const char *, const char *);





int sprintf (char * __restrict, const char *__restrict, ...);
int snprintf (char * __restrict, size_t, const char *__restrict, ...);
# 6 "./strlenopt-52.c" 2
# 27 "./strlenopt-52.c"
struct S
{
  char a1[1], a2[2], a3[3], a4[4], a5[5], a6[6], a7[7], a8[8], a9[9];
};
# 42 "./strlenopt-52.c"
const char a9[][9] = { "", "1", "12", "123", "1234", "12345", "123456", "1234567", "12345678" };

const char a_1_9[1][9] = { "12345678" };
const char a_2_9[2][9] = { "12345678", "1234567"};

const char a9_9[][9][9] = {
  { "", "", "", "", "", "", "", "", "" },
  { "", "1", "1", "1", "1", "1", "1", "1", "1" },
  { "", "1", "12", "12", "12", "12", "12", "12", "12" },
  { "", "1", "12", "123", "123", "123", "123", "123", "123" },
  { "", "1", "12", "123", "1234", "1234", "1234", "1234", "1234" },
  { "", "1", "12", "123", "1234", "12345", "12345", "12345", "12345" },
  { "", "1", "12", "123", "1234", "12345", "123456", "123456", "123456" },
  { "", "1", "12", "123", "1234", "12345", "123456", "1234567", "1234567" },
  { "", "1", "12", "123", "1234", "12345", "123456", "1234567", "12345678" }
};

const struct S s = { "", "1", "12", "123", "1234", "12345", "123456", "1234567", "12345678" };

const struct S sa[9] = {
  { "", "", "", "", "", "", "", "", "" },
  { "", "1", "1", "1", "1", "1", "1", "1", "1" },
  { "", "1", "12", "12", "12", "12", "12", "12", "12" },
  { "", "1", "12", "123", "123", "123", "123", "123", "123" },
  { "", "1", "12", "123", "1234", "1234", "1234", "1234", "1234" },
  { "", "1", "12", "123", "1234", "12345", "12345", "12345", "12345" },
  { "", "1", "12", "123", "1234", "12345", "123456", "123456", "123456" },
  { "", "1", "12", "123", "1234", "12345", "123456", "1234567", "1234567" },
  { "", "1", "12", "123", "1234", "12345", "123456", "1234567", "12345678" }
};

const struct S sa3_5_7[3][5][7] = {
  [1][2][3].a2 = "1", [1][3][5].a3 = "12", [2][4][5].a4 = "123"
};


void test_global_array (void)
{
  if (!(strlen (a9[0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_80 (void); call_in_true_branch_not_eliminated_on_line_80(); } while (0); else (void)0; if (!(strlen (a9[0] + 0) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_80 (void); call_in_true_branch_not_eliminated_on_line_80(); } while (0); else (void)0; if (!(strlen (a9[0] + 0) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_80 (void); call_in_true_branch_not_eliminated_on_line_80(); } while (0); else (void)0; if (!(strlen (a9[0] + 0) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_80 (void); call_in_true_branch_not_eliminated_on_line_80(); } while (0); else (void)0;
  if (!(strlen (a9[1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_81 (void); call_in_true_branch_not_eliminated_on_line_81(); } while (0); else (void)0; if (!(strlen (a9[1] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_81 (void); call_in_true_branch_not_eliminated_on_line_81(); } while (0); else (void)0; if (!(strlen (a9[1] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_81 (void); call_in_true_branch_not_eliminated_on_line_81(); } while (0); else (void)0; if (!(strlen (a9[1] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_81 (void); call_in_true_branch_not_eliminated_on_line_81(); } while (0); else (void)0;
  if (!(strlen (a9[2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_82 (void); call_in_true_branch_not_eliminated_on_line_82(); } while (0); else (void)0;
  if (!(strlen (a9[2] + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_83 (void); call_in_true_branch_not_eliminated_on_line_83(); } while (0); else (void)0;
  if (!(strlen (a9[2] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_84 (void); call_in_true_branch_not_eliminated_on_line_84(); } while (0); else (void)0;
  if (!(strlen (a9[2] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_85 (void); call_in_true_branch_not_eliminated_on_line_85(); } while (0); else (void)0;

  if (!(strlen (a9[3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_87 (void); call_in_true_branch_not_eliminated_on_line_87(); } while (0); else (void)0; if (!(strlen (a9[3] + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_87 (void); call_in_true_branch_not_eliminated_on_line_87(); } while (0); else (void)0; if (!(strlen (a9[3] + 2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_87 (void); call_in_true_branch_not_eliminated_on_line_87(); } while (0); else (void)0; if (!(strlen (a9[3] + 3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_87 (void); call_in_true_branch_not_eliminated_on_line_87(); } while (0); else (void)0;
  if (!(strlen (a9[4]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_88 (void); call_in_true_branch_not_eliminated_on_line_88(); } while (0); else (void)0; if (!(strlen (a9[4] + 1) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_88 (void); call_in_true_branch_not_eliminated_on_line_88(); } while (0); else (void)0; if (!(strlen (a9[4] + 2) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_88 (void); call_in_true_branch_not_eliminated_on_line_88(); } while (0); else (void)0; if (!(strlen (a9[4] + 3) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_88 (void); call_in_true_branch_not_eliminated_on_line_88(); } while (0); else (void)0;
  if (!(strlen (a9[5]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_89 (void); call_in_true_branch_not_eliminated_on_line_89(); } while (0); else (void)0; if (!(strlen (a9[5] + 1) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_89 (void); call_in_true_branch_not_eliminated_on_line_89(); } while (0); else (void)0; if (!(strlen (a9[5] + 2) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_89 (void); call_in_true_branch_not_eliminated_on_line_89(); } while (0); else (void)0; if (!(strlen (a9[5] + 3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_89 (void); call_in_true_branch_not_eliminated_on_line_89(); } while (0); else (void)0;
  if (!(strlen (a9[6]) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_90 (void); call_in_true_branch_not_eliminated_on_line_90(); } while (0); else (void)0; if (!(strlen (a9[6] + 1) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_90 (void); call_in_true_branch_not_eliminated_on_line_90(); } while (0); else (void)0; if (!(strlen (a9[6] + 2) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_90 (void); call_in_true_branch_not_eliminated_on_line_90(); } while (0); else (void)0; if (!(strlen (a9[6] + 3) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_90 (void); call_in_true_branch_not_eliminated_on_line_90(); } while (0); else (void)0;
  if (!(strlen (a9[7]) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_91 (void); call_in_true_branch_not_eliminated_on_line_91(); } while (0); else (void)0; if (!(strlen (a9[7] + 1) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_91 (void); call_in_true_branch_not_eliminated_on_line_91(); } while (0); else (void)0; if (!(strlen (a9[7] + 2) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_91 (void); call_in_true_branch_not_eliminated_on_line_91(); } while (0); else (void)0; if (!(strlen (a9[7] + 3) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_91 (void); call_in_true_branch_not_eliminated_on_line_91(); } while (0); else (void)0;
  if (!(strlen (a9[8]) == 8)) do { extern void call_in_true_branch_not_eliminated_on_line_92 (void); call_in_true_branch_not_eliminated_on_line_92(); } while (0); else (void)0; if (!(strlen (a9[8] + 1) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_92 (void); call_in_true_branch_not_eliminated_on_line_92(); } while (0); else (void)0; if (!(strlen (a9[8] + 2) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_92 (void); call_in_true_branch_not_eliminated_on_line_92(); } while (0); else (void)0; if (!(strlen (a9[8] + 3) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_92 (void); call_in_true_branch_not_eliminated_on_line_92(); } while (0); else (void)0;

  if (!(strlen (a_1_9[0]) == 8)) do { extern void call_in_true_branch_not_eliminated_on_line_94 (void); call_in_true_branch_not_eliminated_on_line_94(); } while (0); else (void)0;
  if (!(strlen (a_1_9[0] + 1) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_95 (void); call_in_true_branch_not_eliminated_on_line_95(); } while (0); else (void)0;
  if (!(strlen (a_1_9[0] + 7) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_96 (void); call_in_true_branch_not_eliminated_on_line_96(); } while (0); else (void)0;
  if (!(strlen (a_1_9[0] + 8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_97 (void); call_in_true_branch_not_eliminated_on_line_97(); } while (0); else (void)0;

  if (!(strlen (a_2_9[0]) == 8)) do { extern void call_in_true_branch_not_eliminated_on_line_99 (void); call_in_true_branch_not_eliminated_on_line_99(); } while (0); else (void)0;
  if (!(strlen (a_2_9[0] + 1) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_100 (void); call_in_true_branch_not_eliminated_on_line_100(); } while (0); else (void)0;
  if (!(strlen (a_2_9[0] + 7) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_101 (void); call_in_true_branch_not_eliminated_on_line_101(); } while (0); else (void)0;
  if (!(strlen (a_2_9[0] + 8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_102 (void); call_in_true_branch_not_eliminated_on_line_102(); } while (0); else (void)0;

  if (!(strlen (a_2_9[1]) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_104 (void); call_in_true_branch_not_eliminated_on_line_104(); } while (0); else (void)0;
  if (!(strlen (a_2_9[1] + 1) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_105 (void); call_in_true_branch_not_eliminated_on_line_105(); } while (0); else (void)0;
  if (!(strlen (a_2_9[1] + 6) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_106 (void); call_in_true_branch_not_eliminated_on_line_106(); } while (0); else (void)0;
  if (!(strlen (a_2_9[1] + 7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_107 (void); call_in_true_branch_not_eliminated_on_line_107(); } while (0); else (void)0;
  if (!(strlen (a_2_9[1] + 8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_108 (void); call_in_true_branch_not_eliminated_on_line_108(); } while (0); else (void)0;
}

void test_global_array_array (void)
{
  if (!(strlen (a9_9[0][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_113 (void); call_in_true_branch_not_eliminated_on_line_113(); } while (0); else (void)0; if (!(strlen (a9_9[1][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_113 (void); call_in_true_branch_not_eliminated_on_line_113(); } while (0); else (void)0; if (!(strlen (a9_9[2][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_113 (void); call_in_true_branch_not_eliminated_on_line_113(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][1]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_114 (void); call_in_true_branch_not_eliminated_on_line_114(); } while (0); else (void)0; if (!(strlen (a9_9[1][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_114 (void); call_in_true_branch_not_eliminated_on_line_114(); } while (0); else (void)0; if (!(strlen (a9_9[2][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_114 (void); call_in_true_branch_not_eliminated_on_line_114(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][2]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_115 (void); call_in_true_branch_not_eliminated_on_line_115(); } while (0); else (void)0; if (!(strlen (a9_9[1][2]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_115 (void); call_in_true_branch_not_eliminated_on_line_115(); } while (0); else (void)0; if (!(strlen (a9_9[2][2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_115 (void); call_in_true_branch_not_eliminated_on_line_115(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][3]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_116 (void); call_in_true_branch_not_eliminated_on_line_116(); } while (0); else (void)0; if (!(strlen (a9_9[1][3]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_116 (void); call_in_true_branch_not_eliminated_on_line_116(); } while (0); else (void)0; if (!(strlen (a9_9[2][3]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_116 (void); call_in_true_branch_not_eliminated_on_line_116(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][4]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_117 (void); call_in_true_branch_not_eliminated_on_line_117(); } while (0); else (void)0; if (!(strlen (a9_9[1][4]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_117 (void); call_in_true_branch_not_eliminated_on_line_117(); } while (0); else (void)0; if (!(strlen (a9_9[2][4]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_117 (void); call_in_true_branch_not_eliminated_on_line_117(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][5]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_118 (void); call_in_true_branch_not_eliminated_on_line_118(); } while (0); else (void)0; if (!(strlen (a9_9[1][5]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_118 (void); call_in_true_branch_not_eliminated_on_line_118(); } while (0); else (void)0; if (!(strlen (a9_9[2][5]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_118 (void); call_in_true_branch_not_eliminated_on_line_118(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][6]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_119 (void); call_in_true_branch_not_eliminated_on_line_119(); } while (0); else (void)0; if (!(strlen (a9_9[1][6]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_119 (void); call_in_true_branch_not_eliminated_on_line_119(); } while (0); else (void)0; if (!(strlen (a9_9[2][6]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_119 (void); call_in_true_branch_not_eliminated_on_line_119(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][7]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_120 (void); call_in_true_branch_not_eliminated_on_line_120(); } while (0); else (void)0; if (!(strlen (a9_9[1][7]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_120 (void); call_in_true_branch_not_eliminated_on_line_120(); } while (0); else (void)0; if (!(strlen (a9_9[2][7]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_120 (void); call_in_true_branch_not_eliminated_on_line_120(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][8]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_121 (void); call_in_true_branch_not_eliminated_on_line_121(); } while (0); else (void)0; if (!(strlen (a9_9[1][8]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_121 (void); call_in_true_branch_not_eliminated_on_line_121(); } while (0); else (void)0; if (!(strlen (a9_9[2][8]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_121 (void); call_in_true_branch_not_eliminated_on_line_121(); } while (0); else (void)0;

  if (!(strlen (a9_9[3][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_123 (void); call_in_true_branch_not_eliminated_on_line_123(); } while (0); else (void)0; if (!(strlen (a9_9[4][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_123 (void); call_in_true_branch_not_eliminated_on_line_123(); } while (0); else (void)0; if (!(strlen (a9_9[5][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_123 (void); call_in_true_branch_not_eliminated_on_line_123(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_124 (void); call_in_true_branch_not_eliminated_on_line_124(); } while (0); else (void)0; if (!(strlen (a9_9[4][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_124 (void); call_in_true_branch_not_eliminated_on_line_124(); } while (0); else (void)0; if (!(strlen (a9_9[5][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_124 (void); call_in_true_branch_not_eliminated_on_line_124(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_125 (void); call_in_true_branch_not_eliminated_on_line_125(); } while (0); else (void)0; if (!(strlen (a9_9[4][2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_125 (void); call_in_true_branch_not_eliminated_on_line_125(); } while (0); else (void)0; if (!(strlen (a9_9[5][2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_125 (void); call_in_true_branch_not_eliminated_on_line_125(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_126 (void); call_in_true_branch_not_eliminated_on_line_126(); } while (0); else (void)0; if (!(strlen (a9_9[4][3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_126 (void); call_in_true_branch_not_eliminated_on_line_126(); } while (0); else (void)0; if (!(strlen (a9_9[5][3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_126 (void); call_in_true_branch_not_eliminated_on_line_126(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][4]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_127 (void); call_in_true_branch_not_eliminated_on_line_127(); } while (0); else (void)0; if (!(strlen (a9_9[4][4]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_127 (void); call_in_true_branch_not_eliminated_on_line_127(); } while (0); else (void)0; if (!(strlen (a9_9[5][4]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_127 (void); call_in_true_branch_not_eliminated_on_line_127(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][5]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_128 (void); call_in_true_branch_not_eliminated_on_line_128(); } while (0); else (void)0; if (!(strlen (a9_9[4][5]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_128 (void); call_in_true_branch_not_eliminated_on_line_128(); } while (0); else (void)0; if (!(strlen (a9_9[5][5]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_128 (void); call_in_true_branch_not_eliminated_on_line_128(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][6]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_129 (void); call_in_true_branch_not_eliminated_on_line_129(); } while (0); else (void)0; if (!(strlen (a9_9[4][6]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_129 (void); call_in_true_branch_not_eliminated_on_line_129(); } while (0); else (void)0; if (!(strlen (a9_9[5][6]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_129 (void); call_in_true_branch_not_eliminated_on_line_129(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][7]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_130 (void); call_in_true_branch_not_eliminated_on_line_130(); } while (0); else (void)0; if (!(strlen (a9_9[4][7]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_130 (void); call_in_true_branch_not_eliminated_on_line_130(); } while (0); else (void)0; if (!(strlen (a9_9[5][7]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_130 (void); call_in_true_branch_not_eliminated_on_line_130(); } while (0); else (void)0;
  if (!(strlen (a9_9[3][8]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_131 (void); call_in_true_branch_not_eliminated_on_line_131(); } while (0); else (void)0; if (!(strlen (a9_9[4][8]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_131 (void); call_in_true_branch_not_eliminated_on_line_131(); } while (0); else (void)0; if (!(strlen (a9_9[5][8]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_131 (void); call_in_true_branch_not_eliminated_on_line_131(); } while (0); else (void)0;

  if (!(strlen (a9_9[6][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_133 (void); call_in_true_branch_not_eliminated_on_line_133(); } while (0); else (void)0; if (!(strlen (a9_9[7][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_133 (void); call_in_true_branch_not_eliminated_on_line_133(); } while (0); else (void)0; if (!(strlen (a9_9[8][0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_133 (void); call_in_true_branch_not_eliminated_on_line_133(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_134 (void); call_in_true_branch_not_eliminated_on_line_134(); } while (0); else (void)0; if (!(strlen (a9_9[7][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_134 (void); call_in_true_branch_not_eliminated_on_line_134(); } while (0); else (void)0; if (!(strlen (a9_9[8][1]) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_134 (void); call_in_true_branch_not_eliminated_on_line_134(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_135 (void); call_in_true_branch_not_eliminated_on_line_135(); } while (0); else (void)0; if (!(strlen (a9_9[7][2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_135 (void); call_in_true_branch_not_eliminated_on_line_135(); } while (0); else (void)0; if (!(strlen (a9_9[8][2]) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_135 (void); call_in_true_branch_not_eliminated_on_line_135(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_136 (void); call_in_true_branch_not_eliminated_on_line_136(); } while (0); else (void)0; if (!(strlen (a9_9[7][3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_136 (void); call_in_true_branch_not_eliminated_on_line_136(); } while (0); else (void)0; if (!(strlen (a9_9[8][3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_136 (void); call_in_true_branch_not_eliminated_on_line_136(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][4]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_137 (void); call_in_true_branch_not_eliminated_on_line_137(); } while (0); else (void)0; if (!(strlen (a9_9[7][4]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_137 (void); call_in_true_branch_not_eliminated_on_line_137(); } while (0); else (void)0; if (!(strlen (a9_9[8][4]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_137 (void); call_in_true_branch_not_eliminated_on_line_137(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][5]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_138 (void); call_in_true_branch_not_eliminated_on_line_138(); } while (0); else (void)0; if (!(strlen (a9_9[7][5]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_138 (void); call_in_true_branch_not_eliminated_on_line_138(); } while (0); else (void)0; if (!(strlen (a9_9[8][5]) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_138 (void); call_in_true_branch_not_eliminated_on_line_138(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][6]) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_139 (void); call_in_true_branch_not_eliminated_on_line_139(); } while (0); else (void)0; if (!(strlen (a9_9[7][6]) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_139 (void); call_in_true_branch_not_eliminated_on_line_139(); } while (0); else (void)0; if (!(strlen (a9_9[8][6]) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_139 (void); call_in_true_branch_not_eliminated_on_line_139(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][7]) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_140 (void); call_in_true_branch_not_eliminated_on_line_140(); } while (0); else (void)0; if (!(strlen (a9_9[7][7]) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_140 (void); call_in_true_branch_not_eliminated_on_line_140(); } while (0); else (void)0; if (!(strlen (a9_9[8][7]) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_140 (void); call_in_true_branch_not_eliminated_on_line_140(); } while (0); else (void)0;
  if (!(strlen (a9_9[6][8]) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_141 (void); call_in_true_branch_not_eliminated_on_line_141(); } while (0); else (void)0; if (!(strlen (a9_9[7][8]) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_141 (void); call_in_true_branch_not_eliminated_on_line_141(); } while (0); else (void)0; if (!(strlen (a9_9[8][8]) == 8)) do { extern void call_in_true_branch_not_eliminated_on_line_141 (void); call_in_true_branch_not_eliminated_on_line_141(); } while (0); else (void)0;


  if (!(strlen (a9_9[0][0] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_144 (void); call_in_true_branch_not_eliminated_on_line_144(); } while (0); else (void)0; if (!(strlen (a9_9[1][0] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_144 (void); call_in_true_branch_not_eliminated_on_line_144(); } while (0); else (void)0; if (!(strlen (a9_9[2][0] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_144 (void); call_in_true_branch_not_eliminated_on_line_144(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][1] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_145 (void); call_in_true_branch_not_eliminated_on_line_145(); } while (0); else (void)0; if (!(strlen (a9_9[1][1] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_145 (void); call_in_true_branch_not_eliminated_on_line_145(); } while (0); else (void)0; if (!(strlen (a9_9[2][1] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_145 (void); call_in_true_branch_not_eliminated_on_line_145(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][2] + 3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_146 (void); call_in_true_branch_not_eliminated_on_line_146(); } while (0); else (void)0; if (!(strlen (a9_9[1][2] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_146 (void); call_in_true_branch_not_eliminated_on_line_146(); } while (0); else (void)0; if (!(strlen (a9_9[2][2] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_146 (void); call_in_true_branch_not_eliminated_on_line_146(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][3] + 4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_147 (void); call_in_true_branch_not_eliminated_on_line_147(); } while (0); else (void)0; if (!(strlen (a9_9[1][3] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_147 (void); call_in_true_branch_not_eliminated_on_line_147(); } while (0); else (void)0; if (!(strlen (a9_9[2][3] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_147 (void); call_in_true_branch_not_eliminated_on_line_147(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][4] + 5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_148 (void); call_in_true_branch_not_eliminated_on_line_148(); } while (0); else (void)0; if (!(strlen (a9_9[1][4] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_148 (void); call_in_true_branch_not_eliminated_on_line_148(); } while (0); else (void)0; if (!(strlen (a9_9[2][4] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_148 (void); call_in_true_branch_not_eliminated_on_line_148(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][5] + 6) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_149 (void); call_in_true_branch_not_eliminated_on_line_149(); } while (0); else (void)0; if (!(strlen (a9_9[1][5] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_149 (void); call_in_true_branch_not_eliminated_on_line_149(); } while (0); else (void)0; if (!(strlen (a9_9[2][5] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_149 (void); call_in_true_branch_not_eliminated_on_line_149(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][6] + 7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_150 (void); call_in_true_branch_not_eliminated_on_line_150(); } while (0); else (void)0; if (!(strlen (a9_9[1][6] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_150 (void); call_in_true_branch_not_eliminated_on_line_150(); } while (0); else (void)0; if (!(strlen (a9_9[2][6] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_150 (void); call_in_true_branch_not_eliminated_on_line_150(); } while (0); else (void)0;
  if (!(strlen (a9_9[0][7] + 8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_151 (void); call_in_true_branch_not_eliminated_on_line_151(); } while (0); else (void)0; if (!(strlen (a9_9[1][7] + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_151 (void); call_in_true_branch_not_eliminated_on_line_151(); } while (0); else (void)0; if (!(strlen (a9_9[2][7] + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_151 (void); call_in_true_branch_not_eliminated_on_line_151(); } while (0); else (void)0;
}

void test_global_struct (void)
{
  if (!(strlen (s.a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_156 (void); call_in_true_branch_not_eliminated_on_line_156(); } while (0); else (void)0;
  if (!(strlen (s.a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_157 (void); call_in_true_branch_not_eliminated_on_line_157(); } while (0); else (void)0;
  if (!(strlen (s.a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_158 (void); call_in_true_branch_not_eliminated_on_line_158(); } while (0); else (void)0;
  if (!(strlen (s.a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_159 (void); call_in_true_branch_not_eliminated_on_line_159(); } while (0); else (void)0;
  if (!(strlen (s.a5) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_160 (void); call_in_true_branch_not_eliminated_on_line_160(); } while (0); else (void)0;
  if (!(strlen (s.a6) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_161 (void); call_in_true_branch_not_eliminated_on_line_161(); } while (0); else (void)0;
  if (!(strlen (s.a7) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_162 (void); call_in_true_branch_not_eliminated_on_line_162(); } while (0); else (void)0;
  if (!(strlen (s.a8) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_163 (void); call_in_true_branch_not_eliminated_on_line_163(); } while (0); else (void)0;
  if (!(strlen (s.a9) == 8)) do { extern void call_in_true_branch_not_eliminated_on_line_164 (void); call_in_true_branch_not_eliminated_on_line_164(); } while (0); else (void)0;
}

void test_global_struct_array (void)
{
  if (!(strlen (sa[0].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_169 (void); call_in_true_branch_not_eliminated_on_line_169(); } while (0); else (void)0; if (!(strlen (sa[1].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_169 (void); call_in_true_branch_not_eliminated_on_line_169(); } while (0); else (void)0; if (!(strlen (sa[2].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_169 (void); call_in_true_branch_not_eliminated_on_line_169(); } while (0); else (void)0; if (!(strlen (sa[3].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_169 (void); call_in_true_branch_not_eliminated_on_line_169(); } while (0); else (void)0;
  if (!(strlen (sa[0].a2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_170 (void); call_in_true_branch_not_eliminated_on_line_170(); } while (0); else (void)0; if (!(strlen (sa[1].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_170 (void); call_in_true_branch_not_eliminated_on_line_170(); } while (0); else (void)0; if (!(strlen (sa[2].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_170 (void); call_in_true_branch_not_eliminated_on_line_170(); } while (0); else (void)0; if (!(strlen (sa[3].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_170 (void); call_in_true_branch_not_eliminated_on_line_170(); } while (0); else (void)0;
  if (!(strlen (sa[0].a3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_171 (void); call_in_true_branch_not_eliminated_on_line_171(); } while (0); else (void)0; if (!(strlen (sa[1].a3) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_171 (void); call_in_true_branch_not_eliminated_on_line_171(); } while (0); else (void)0; if (!(strlen (sa[2].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_171 (void); call_in_true_branch_not_eliminated_on_line_171(); } while (0); else (void)0; if (!(strlen (sa[3].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_171 (void); call_in_true_branch_not_eliminated_on_line_171(); } while (0); else (void)0;
  if (!(strlen (sa[0].a4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_172 (void); call_in_true_branch_not_eliminated_on_line_172(); } while (0); else (void)0; if (!(strlen (sa[1].a4) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_172 (void); call_in_true_branch_not_eliminated_on_line_172(); } while (0); else (void)0; if (!(strlen (sa[2].a4) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_172 (void); call_in_true_branch_not_eliminated_on_line_172(); } while (0); else (void)0; if (!(strlen (sa[3].a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_172 (void); call_in_true_branch_not_eliminated_on_line_172(); } while (0); else (void)0;
  if (!(strlen (sa[0].a5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_173 (void); call_in_true_branch_not_eliminated_on_line_173(); } while (0); else (void)0; if (!(strlen (sa[1].a5) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_173 (void); call_in_true_branch_not_eliminated_on_line_173(); } while (0); else (void)0; if (!(strlen (sa[2].a5) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_173 (void); call_in_true_branch_not_eliminated_on_line_173(); } while (0); else (void)0; if (!(strlen (sa[3].a5) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_173 (void); call_in_true_branch_not_eliminated_on_line_173(); } while (0); else (void)0;
  if (!(strlen (sa[0].a6) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_174 (void); call_in_true_branch_not_eliminated_on_line_174(); } while (0); else (void)0; if (!(strlen (sa[1].a6) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_174 (void); call_in_true_branch_not_eliminated_on_line_174(); } while (0); else (void)0; if (!(strlen (sa[2].a6) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_174 (void); call_in_true_branch_not_eliminated_on_line_174(); } while (0); else (void)0; if (!(strlen (sa[3].a6) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_174 (void); call_in_true_branch_not_eliminated_on_line_174(); } while (0); else (void)0;
  if (!(strlen (sa[0].a7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_175 (void); call_in_true_branch_not_eliminated_on_line_175(); } while (0); else (void)0; if (!(strlen (sa[1].a7) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_175 (void); call_in_true_branch_not_eliminated_on_line_175(); } while (0); else (void)0; if (!(strlen (sa[2].a7) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_175 (void); call_in_true_branch_not_eliminated_on_line_175(); } while (0); else (void)0; if (!(strlen (sa[3].a7) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_175 (void); call_in_true_branch_not_eliminated_on_line_175(); } while (0); else (void)0;
  if (!(strlen (sa[0].a8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_176 (void); call_in_true_branch_not_eliminated_on_line_176(); } while (0); else (void)0; if (!(strlen (sa[1].a8) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_176 (void); call_in_true_branch_not_eliminated_on_line_176(); } while (0); else (void)0; if (!(strlen (sa[2].a8) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_176 (void); call_in_true_branch_not_eliminated_on_line_176(); } while (0); else (void)0; if (!(strlen (sa[3].a8) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_176 (void); call_in_true_branch_not_eliminated_on_line_176(); } while (0); else (void)0;
  if (!(strlen (sa[0].a9) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_177 (void); call_in_true_branch_not_eliminated_on_line_177(); } while (0); else (void)0; if (!(strlen (sa[1].a9) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_177 (void); call_in_true_branch_not_eliminated_on_line_177(); } while (0); else (void)0; if (!(strlen (sa[2].a9) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_177 (void); call_in_true_branch_not_eliminated_on_line_177(); } while (0); else (void)0; if (!(strlen (sa[3].a9) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_177 (void); call_in_true_branch_not_eliminated_on_line_177(); } while (0); else (void)0;

  if (!(strlen (sa[4].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_179 (void); call_in_true_branch_not_eliminated_on_line_179(); } while (0); else (void)0; if (!(strlen (sa[5].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_179 (void); call_in_true_branch_not_eliminated_on_line_179(); } while (0); else (void)0; if (!(strlen (sa[6].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_179 (void); call_in_true_branch_not_eliminated_on_line_179(); } while (0); else (void)0; if (!(strlen (sa[7].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_179 (void); call_in_true_branch_not_eliminated_on_line_179(); } while (0); else (void)0;
  if (!(strlen (sa[4].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_180 (void); call_in_true_branch_not_eliminated_on_line_180(); } while (0); else (void)0; if (!(strlen (sa[5].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_180 (void); call_in_true_branch_not_eliminated_on_line_180(); } while (0); else (void)0; if (!(strlen (sa[6].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_180 (void); call_in_true_branch_not_eliminated_on_line_180(); } while (0); else (void)0; if (!(strlen (sa[7].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_180 (void); call_in_true_branch_not_eliminated_on_line_180(); } while (0); else (void)0;
  if (!(strlen (sa[4].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_181 (void); call_in_true_branch_not_eliminated_on_line_181(); } while (0); else (void)0; if (!(strlen (sa[5].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_181 (void); call_in_true_branch_not_eliminated_on_line_181(); } while (0); else (void)0; if (!(strlen (sa[6].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_181 (void); call_in_true_branch_not_eliminated_on_line_181(); } while (0); else (void)0; if (!(strlen (sa[7].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_181 (void); call_in_true_branch_not_eliminated_on_line_181(); } while (0); else (void)0;
  if (!(strlen (sa[4].a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_182 (void); call_in_true_branch_not_eliminated_on_line_182(); } while (0); else (void)0; if (!(strlen (sa[5].a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_182 (void); call_in_true_branch_not_eliminated_on_line_182(); } while (0); else (void)0; if (!(strlen (sa[6].a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_182 (void); call_in_true_branch_not_eliminated_on_line_182(); } while (0); else (void)0; if (!(strlen (sa[7].a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_182 (void); call_in_true_branch_not_eliminated_on_line_182(); } while (0); else (void)0;
  if (!(strlen (sa[4].a5) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_183 (void); call_in_true_branch_not_eliminated_on_line_183(); } while (0); else (void)0; if (!(strlen (sa[5].a5) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_183 (void); call_in_true_branch_not_eliminated_on_line_183(); } while (0); else (void)0; if (!(strlen (sa[6].a5) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_183 (void); call_in_true_branch_not_eliminated_on_line_183(); } while (0); else (void)0; if (!(strlen (sa[7].a5) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_183 (void); call_in_true_branch_not_eliminated_on_line_183(); } while (0); else (void)0;
  if (!(strlen (sa[4].a6) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_184 (void); call_in_true_branch_not_eliminated_on_line_184(); } while (0); else (void)0; if (!(strlen (sa[5].a6) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_184 (void); call_in_true_branch_not_eliminated_on_line_184(); } while (0); else (void)0; if (!(strlen (sa[6].a6) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_184 (void); call_in_true_branch_not_eliminated_on_line_184(); } while (0); else (void)0; if (!(strlen (sa[7].a6) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_184 (void); call_in_true_branch_not_eliminated_on_line_184(); } while (0); else (void)0;
  if (!(strlen (sa[4].a7) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_185 (void); call_in_true_branch_not_eliminated_on_line_185(); } while (0); else (void)0; if (!(strlen (sa[5].a7) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_185 (void); call_in_true_branch_not_eliminated_on_line_185(); } while (0); else (void)0; if (!(strlen (sa[6].a7) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_185 (void); call_in_true_branch_not_eliminated_on_line_185(); } while (0); else (void)0; if (!(strlen (sa[7].a7) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_185 (void); call_in_true_branch_not_eliminated_on_line_185(); } while (0); else (void)0;
  if (!(strlen (sa[4].a8) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_186 (void); call_in_true_branch_not_eliminated_on_line_186(); } while (0); else (void)0; if (!(strlen (sa[5].a8) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_186 (void); call_in_true_branch_not_eliminated_on_line_186(); } while (0); else (void)0; if (!(strlen (sa[6].a8) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_186 (void); call_in_true_branch_not_eliminated_on_line_186(); } while (0); else (void)0; if (!(strlen (sa[7].a8) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_186 (void); call_in_true_branch_not_eliminated_on_line_186(); } while (0); else (void)0;
  if (!(strlen (sa[4].a9) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_187 (void); call_in_true_branch_not_eliminated_on_line_187(); } while (0); else (void)0; if (!(strlen (sa[5].a9) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_187 (void); call_in_true_branch_not_eliminated_on_line_187(); } while (0); else (void)0; if (!(strlen (sa[6].a9) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_187 (void); call_in_true_branch_not_eliminated_on_line_187(); } while (0); else (void)0; if (!(strlen (sa[7].a9) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_187 (void); call_in_true_branch_not_eliminated_on_line_187(); } while (0); else (void)0;

  if (!(strlen (sa[8].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_189 (void); call_in_true_branch_not_eliminated_on_line_189(); } while (0); else (void)0;
  if (!(strlen (sa[8].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_190 (void); call_in_true_branch_not_eliminated_on_line_190(); } while (0); else (void)0; if (!(strlen (sa[8].a2 + 1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_190 (void); call_in_true_branch_not_eliminated_on_line_190(); } while (0); else (void)0;
  if (!(strlen (sa[8].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_191 (void); call_in_true_branch_not_eliminated_on_line_191(); } while (0); else (void)0; if (!(strlen (sa[8].a3 + 1) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_191 (void); call_in_true_branch_not_eliminated_on_line_191(); } while (0); else (void)0; if (!(strlen (sa[8].a3 + 2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_191 (void); call_in_true_branch_not_eliminated_on_line_191(); } while (0); else (void)0;
  if (!(strlen (sa[8].a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_192 (void); call_in_true_branch_not_eliminated_on_line_192(); } while (0); else (void)0; if (!(strlen (sa[8].a4 + 1) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_192 (void); call_in_true_branch_not_eliminated_on_line_192(); } while (0); else (void)0; if (!(strlen (sa[8].a4 + 2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_192 (void); call_in_true_branch_not_eliminated_on_line_192(); } while (0); else (void)0;
  if (!(strlen (sa[8].a5) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_193 (void); call_in_true_branch_not_eliminated_on_line_193(); } while (0); else (void)0; if (!(strlen (sa[8].a5 + 1) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_193 (void); call_in_true_branch_not_eliminated_on_line_193(); } while (0); else (void)0; if (!(strlen (sa[8].a5 + 2) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_193 (void); call_in_true_branch_not_eliminated_on_line_193(); } while (0); else (void)0;
  if (!(strlen (sa[8].a6) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_194 (void); call_in_true_branch_not_eliminated_on_line_194(); } while (0); else (void)0; if (!(strlen (sa[8].a6 + 1) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_194 (void); call_in_true_branch_not_eliminated_on_line_194(); } while (0); else (void)0; if (!(strlen (sa[8].a6 + 2) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_194 (void); call_in_true_branch_not_eliminated_on_line_194(); } while (0); else (void)0;
  if (!(strlen (sa[8].a7) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_195 (void); call_in_true_branch_not_eliminated_on_line_195(); } while (0); else (void)0; if (!(strlen (sa[8].a7 + 1) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_195 (void); call_in_true_branch_not_eliminated_on_line_195(); } while (0); else (void)0; if (!(strlen (sa[8].a7 + 2) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_195 (void); call_in_true_branch_not_eliminated_on_line_195(); } while (0); else (void)0;
  if (!(strlen (sa[8].a8) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_196 (void); call_in_true_branch_not_eliminated_on_line_196(); } while (0); else (void)0; if (!(strlen (sa[8].a8 + 1) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_196 (void); call_in_true_branch_not_eliminated_on_line_196(); } while (0); else (void)0; if (!(strlen (sa[8].a8 + 2) == 5)) do { extern void call_in_true_branch_not_eliminated_on_line_196 (void); call_in_true_branch_not_eliminated_on_line_196(); } while (0); else (void)0;
  if (!(strlen (sa[8].a9) == 8)) do { extern void call_in_true_branch_not_eliminated_on_line_197 (void); call_in_true_branch_not_eliminated_on_line_197(); } while (0); else (void)0; if (!(strlen (sa[8].a9 + 1) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_197 (void); call_in_true_branch_not_eliminated_on_line_197(); } while (0); else (void)0; if (!(strlen (sa[8].a9 + 2) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_197 (void); call_in_true_branch_not_eliminated_on_line_197(); } while (0); else (void)0;


  if (!(strlen (sa3_5_7[1][2][3].a2) == 1)) do { extern void call_in_true_branch_not_eliminated_on_line_200 (void); call_in_true_branch_not_eliminated_on_line_200(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][3][5].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_201 (void); call_in_true_branch_not_eliminated_on_line_201(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[2][4][5].a4) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_202 (void); call_in_true_branch_not_eliminated_on_line_202(); } while (0); else (void)0;

  if (!(strlen (sa3_5_7[0][0][0].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_204 (void); call_in_true_branch_not_eliminated_on_line_204(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_205 (void); call_in_true_branch_not_eliminated_on_line_205(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_206 (void); call_in_true_branch_not_eliminated_on_line_206(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_207 (void); call_in_true_branch_not_eliminated_on_line_207(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_208 (void); call_in_true_branch_not_eliminated_on_line_208(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a6) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_209 (void); call_in_true_branch_not_eliminated_on_line_209(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_210 (void); call_in_true_branch_not_eliminated_on_line_210(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_211 (void); call_in_true_branch_not_eliminated_on_line_211(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][0].a9) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_212 (void); call_in_true_branch_not_eliminated_on_line_212(); } while (0); else (void)0;

  if (!(strlen (sa3_5_7[0][0][1].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_214 (void); call_in_true_branch_not_eliminated_on_line_214(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_215 (void); call_in_true_branch_not_eliminated_on_line_215(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_216 (void); call_in_true_branch_not_eliminated_on_line_216(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_217 (void); call_in_true_branch_not_eliminated_on_line_217(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_218 (void); call_in_true_branch_not_eliminated_on_line_218(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a6) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_219 (void); call_in_true_branch_not_eliminated_on_line_219(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_220 (void); call_in_true_branch_not_eliminated_on_line_220(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_221 (void); call_in_true_branch_not_eliminated_on_line_221(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][0][1].a9) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_222 (void); call_in_true_branch_not_eliminated_on_line_222(); } while (0); else (void)0;

  if (!(strlen (sa3_5_7[0][1][0].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_224 (void); call_in_true_branch_not_eliminated_on_line_224(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_225 (void); call_in_true_branch_not_eliminated_on_line_225(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_226 (void); call_in_true_branch_not_eliminated_on_line_226(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_227 (void); call_in_true_branch_not_eliminated_on_line_227(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_228 (void); call_in_true_branch_not_eliminated_on_line_228(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a6) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_229 (void); call_in_true_branch_not_eliminated_on_line_229(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_230 (void); call_in_true_branch_not_eliminated_on_line_230(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_231 (void); call_in_true_branch_not_eliminated_on_line_231(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[0][1][0].a9) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_232 (void); call_in_true_branch_not_eliminated_on_line_232(); } while (0); else (void)0;

  if (!(strlen (sa3_5_7[1][0][0].a1) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_234 (void); call_in_true_branch_not_eliminated_on_line_234(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a2) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_235 (void); call_in_true_branch_not_eliminated_on_line_235(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a3) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_236 (void); call_in_true_branch_not_eliminated_on_line_236(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a4) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_237 (void); call_in_true_branch_not_eliminated_on_line_237(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_238 (void); call_in_true_branch_not_eliminated_on_line_238(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a6) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_239 (void); call_in_true_branch_not_eliminated_on_line_239(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_240 (void); call_in_true_branch_not_eliminated_on_line_240(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a8) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_241 (void); call_in_true_branch_not_eliminated_on_line_241(); } while (0); else (void)0;
  if (!(strlen (sa3_5_7[1][0][0].a9) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_242 (void); call_in_true_branch_not_eliminated_on_line_242(); } while (0); else (void)0;
}


struct SS {
  char a9[9][9];
  struct S sa9[9];
};

const struct SS ssa[] = {
  [1] = {
    .a9 = { [3] = "123", [7] = "1234567" },
    .sa9 = { [5] = { .a5 = "1234", .a7 = "123456" } }
  },
  [5] = {
    .a9 = { [1] = "12345678", [5] = "1234" },
    .sa9 = { [3] = { .a3 = "12", .a6 = "123" } }
  }
};

void test_global_struct_struct_array (void)
{
  if (!(strlen (ssa[0].a9[0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_264 (void); call_in_true_branch_not_eliminated_on_line_264(); } while (0); else (void)0;
  if (!(strlen (ssa[0].a9[3]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_265 (void); call_in_true_branch_not_eliminated_on_line_265(); } while (0); else (void)0;
  if (!(strlen (ssa[0].sa9[5].a5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_266 (void); call_in_true_branch_not_eliminated_on_line_266(); } while (0); else (void)0;
  if (!(strlen (ssa[0].sa9[5].a7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_267 (void); call_in_true_branch_not_eliminated_on_line_267(); } while (0); else (void)0;

  if (!(strlen (ssa[1].a9[0]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_269 (void); call_in_true_branch_not_eliminated_on_line_269(); } while (0); else (void)0;

  if (!(strlen (ssa[1].a9[3]) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_271 (void); call_in_true_branch_not_eliminated_on_line_271(); } while (0); else (void)0;
  if (!(strlen (ssa[1].a9[7]) == 7)) do { extern void call_in_true_branch_not_eliminated_on_line_272 (void); call_in_true_branch_not_eliminated_on_line_272(); } while (0); else (void)0;
  if (!(strlen (ssa[1].sa9[5].a5) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_273 (void); call_in_true_branch_not_eliminated_on_line_273(); } while (0); else (void)0;
  if (!(strlen (ssa[1].sa9[5].a7) == 6)) do { extern void call_in_true_branch_not_eliminated_on_line_274 (void); call_in_true_branch_not_eliminated_on_line_274(); } while (0); else (void)0;

  if (!(strlen (ssa[2].a9[3]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_276 (void); call_in_true_branch_not_eliminated_on_line_276(); } while (0); else (void)0;
  if (!(strlen (ssa[2].a9[7]) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_277 (void); call_in_true_branch_not_eliminated_on_line_277(); } while (0); else (void)0;
  if (!(strlen (ssa[2].sa9[5].a5) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_278 (void); call_in_true_branch_not_eliminated_on_line_278(); } while (0); else (void)0;
  if (!(strlen (ssa[2].sa9[5].a7) == 0)) do { extern void call_in_true_branch_not_eliminated_on_line_279 (void); call_in_true_branch_not_eliminated_on_line_279(); } while (0); else (void)0;

  if (!(strlen (ssa[5].a9[1]) == 8)) do { extern void call_in_true_branch_not_eliminated_on_line_281 (void); call_in_true_branch_not_eliminated_on_line_281(); } while (0); else (void)0;
  if (!(strlen (ssa[5].a9[5]) == 4)) do { extern void call_in_true_branch_not_eliminated_on_line_282 (void); call_in_true_branch_not_eliminated_on_line_282(); } while (0); else (void)0;
  if (!(strlen (ssa[5].sa9[3].a3) == 2)) do { extern void call_in_true_branch_not_eliminated_on_line_283 (void); call_in_true_branch_not_eliminated_on_line_283(); } while (0); else (void)0;
  if (!(strlen (ssa[5].sa9[3].a6) == 3)) do { extern void call_in_true_branch_not_eliminated_on_line_284 (void); call_in_true_branch_not_eliminated_on_line_284(); } while (0); else (void)0;
}
