//type: lp
//options: 
# 0 "./tree-ssa/log_exp.c"
# 0 "<built-in>"
# 0 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 0 "<command-line>" 2
# 1 "./tree-ssa/log_exp.c"




# 1 "/mds/gnu/build/gcc-15-20250223/lib/gcc/x86_64-pc-linux-gnu/15.0.1/include/stdbool.h" 1 3 4
# 6 "./tree-ssa/log_exp.c" 2

extern void link_error(void);
# 33 "./tree-ssa/log_exp.c"
void test_exp_log_1 (double x) { double a = 10.0; double t1 = __builtin_exp(x); bool b1 = t1 <= a; double t2 = __builtin_log(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_exp_log_2 (double x) { double a = 10.0; double t1 = __builtin_exp(x); bool b1 = t1 >= a; double t2 = __builtin_log(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_exp2_log2_1 (double x) { double a = 10.0; double t1 = __builtin_exp2(x); bool b1 = t1 <= a; double t2 = __builtin_log2(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_exp2_log2_2 (double x) { double a = 10.0; double t1 = __builtin_exp2(x); bool b1 = t1 >= a; double t2 = __builtin_log2(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_exp10_log10_1 (double x) { double a = 10.0; double t1 = __builtin_exp10(x); bool b1 = t1 <= a; double t2 = __builtin_log10(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_exp10_log10_2 (double x) { double a = 10.0; double t1 = __builtin_exp10(x); bool b1 = t1 >= a; double t2 = __builtin_log10(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_log_exp_1 (double x) { double a = 10.0; double t1 = __builtin_log(x); bool b1 = t1 <= a; double t2 = __builtin_exp(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_log_exp_2 (double x) { double a = 10.0; double t1 = __builtin_log(x); bool b1 = t1 >= a; double t2 = __builtin_exp(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_log2_exp2_1 (double x) { double a = 10.0; double t1 = __builtin_log2(x); bool b1 = t1 <= a; double t2 = __builtin_exp2(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_log2_exp2_2 (double x) { double a = 10.0; double t1 = __builtin_log2(x); bool b1 = t1 >= a; double t2 = __builtin_exp2(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_log10_exp10_1 (double x) { double a = 10.0; double t1 = __builtin_log10(x); bool b1 = t1 <= a; double t2 = __builtin_exp10(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_log10_exp10_2 (double x) { double a = 10.0; double t1 = __builtin_log10(x); bool b1 = t1 >= a; double t2 = __builtin_exp10(a); bool b2 = x >= t2; if (b1 != b2) link_error(); }
void test_expf_logf_1 (float x) { float a = 10.0f; float t1 = __builtin_expf(x); bool b1 = t1 <= a; float t2 = __builtin_logf(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_expf_logf_2 (float x) { float a = 10.0f; float t1 = __builtin_expf(x); bool b1 = t1 >= a; float t2 = __builtin_logf(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_exp2f_log2f_1 (float x) { float a = 10.0f; float t1 = __builtin_exp2f(x); bool b1 = t1 <= a; float t2 = __builtin_log2f(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_exp2f_log2f_2 (float x) { float a = 10.0f; float t1 = __builtin_exp2f(x); bool b1 = t1 >= a; float t2 = __builtin_log2f(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_exp10f_log10f_1 (float x) { float a = 10.0f; float t1 = __builtin_exp10f(x); bool b1 = t1 <= a; float t2 = __builtin_log10f(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_exp10f_log10f_2 (float x) { float a = 10.0f; float t1 = __builtin_exp10f(x); bool b1 = t1 >= a; float t2 = __builtin_log10f(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_logf_expf_1 (float x) { float a = 10.0f; float t1 = __builtin_logf(x); bool b1 = t1 <= a; float t2 = __builtin_expf(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_logf_expf_2 (float x) { float a = 10.0f; float t1 = __builtin_logf(x); bool b1 = t1 >= a; float t2 = __builtin_expf(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_log2f_exp2f_1 (float x) { float a = 10.0f; float t1 = __builtin_log2f(x); bool b1 = t1 <= a; float t2 = __builtin_exp2f(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_log2f_exp2f_2 (float x) { float a = 10.0f; float t1 = __builtin_log2f(x); bool b1 = t1 >= a; float t2 = __builtin_exp2f(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_log10f_exp10f_1 (float x) { float a = 10.0f; float t1 = __builtin_log10f(x); bool b1 = t1 <= a; float t2 = __builtin_exp10f(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_log10f_exp10f_2 (float x) { float a = 10.0f; float t1 = __builtin_log10f(x); bool b1 = t1 >= a; float t2 = __builtin_exp10f(a); bool b2 = x >= t2; if (b1 != b2) link_error(); }
void test_expl_logl_1 (long double x) { long double a = 10.0L; long double t1 = __builtin_expl(x); bool b1 = t1 <= a; long double t2 = __builtin_logl(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_expl_logl_2 (long double x) { long double a = 10.0L; long double t1 = __builtin_expl(x); bool b1 = t1 >= a; long double t2 = __builtin_logl(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_exp2l_log2l_1 (long double x) { long double a = 10.0L; long double t1 = __builtin_exp2l(x); bool b1 = t1 <= a; long double t2 = __builtin_log2l(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_exp2l_log2l_2 (long double x) { long double a = 10.0L; long double t1 = __builtin_exp2l(x); bool b1 = t1 >= a; long double t2 = __builtin_log2l(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_exp10l_log10l_1 (long double x) { long double a = 10.0L; long double t1 = __builtin_exp10l(x); bool b1 = t1 <= a; long double t2 = __builtin_log10l(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_exp10l_log10l_2 (long double x) { long double a = 10.0L; long double t1 = __builtin_exp10l(x); bool b1 = t1 >= a; long double t2 = __builtin_log10l(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_logl_expl_1 (long double x) { long double a = 10.0L; long double t1 = __builtin_logl(x); bool b1 = t1 <= a; long double t2 = __builtin_expl(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_logl_expl_2 (long double x) { long double a = 10.0L; long double t1 = __builtin_logl(x); bool b1 = t1 >= a; long double t2 = __builtin_expl(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_log2l_exp2l_1 (long double x) { long double a = 10.0L; long double t1 = __builtin_log2l(x); bool b1 = t1 <= a; long double t2 = __builtin_exp2l(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_log2l_exp2l_2 (long double x) { long double a = 10.0L; long double t1 = __builtin_log2l(x); bool b1 = t1 >= a; long double t2 = __builtin_exp2l(a); bool b2 = x >= t2; if (b1 != b2) link_error(); } void test_log10l_exp10l_1 (long double x) { long double a = 10.0L; long double t1 = __builtin_log10l(x); bool b1 = t1 <= a; long double t2 = __builtin_exp10l(a); bool b2 = x <= t2; if (b1 != b2) link_error(); } void test_log10l_exp10l_2 (long double x) { long double a = 10.0L; long double t1 = __builtin_log10l(x); bool b1 = t1 >= a; long double t2 = __builtin_exp10l(a); bool b2 = x >= t2; if (b1 != b2) link_error(); }

int main (void)
{
  return 0;
}
