//remark:Match correspondences across translation units
//type:fn
//name:
//options:
//options_all:-A --multi_trans_unit
//cases:
//source_files:d00137a_2.c d00137a_3.c d00137a_4.c d00137a_5.c
//input_files:
//output_files:
//ulimit:
//linker_options:
//execution_args:

// 14
// autogenerated

//cmdp -A -c --multi_trans_unit 1.c 2.c 3.c 4.c 5.c

void f() {}

