/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-2025 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
/*

lint.h -- Lint suppression directives.

Included from basic_hdrs.h in every compilation.

*/

/* Avoid including these declarations more than once. */
#ifndef LINT_H
#define LINT_H 1

/*
A collection of lint -esym directives with no particular ordering.  These
directives need to precede the declarations of the symbols they refer to so
this header is the first to be #include'd by basic_hdrs.h.  As a result,
configuration macro settings are not yet available so these directives are
enabled in all configurations (though often they could be restricted to
a smaller subset).
*/
/*lint -esym(767,fread_with_check)*/
/*lint -esym(756,a*_dummy_typedef)*/
/*lint -esym(755,size_of_type)*/
/*lint -esym(755,typeref_is_const_qualified)*/
/*lint -esym(755,typeref_is_volatile_qualified)*/
/*lint -esym(755,typeref_is_restrict_qualified)*/
/*lint -esym(755,DSI_NO_INPUT_FLAGS)*/
/*lint -esym(755,DSO_NO_OUTPUT_FLAGS)*/
/*lint -esym(756,a_simple_source_position_ptr)*/
/*lint -esym(755,set_macro_inv_record_ptr_to_index)*/
/*lint -esym(755,cpp0x_mode)*/
/*lint -esym(755,clangcpp_version_is)*/
/*lint -esym(755,clangc_version_is)*/
/*lint -esym(769,ec_cannot_open_pch_input_file_reason)*/
/*lint -esym(769,ec_cannot_open_temp_file_reason)*/
/*lint -esym(759,change_non_id_characters)*/
/*lint -esym(765,change_non_id_characters)*/
/*lint -esym(759,type_from_src_seq_declaration)*/
/*lint -esym(765,type_from_src_seq_declaration)*/
/*lint -esym(759,form_type_qualifier)*/
/*lint -esym(765,form_type_qualifier)*/
/*lint -esym(759,file_name_in_external_encoding)*/
/*lint -esym(765,file_name_in_external_encoding)*/
/*lint -esym(759,form_pm_constant)*/
/*lint -esym(765,form_pm_constant)*/
/*lint -esym(759,form_lvalue_address_constant)*/
/*lint -esym(765,form_lvalue_address_constant)*/
/*lint -esym(759,alloc_new_mem_block)*/
/*lint -esym(765,alloc_new_mem_block)*/
/*lint -esym(759,alloc_mem_block)*/
/*lint -esym(765,alloc_mem_block)*/
/*lint -esym(759,init_memory_region_without_initial_allocation)*/
/*lint -esym(765,init_memory_region_without_initial_allocation)*/
/*lint -esym(759,trim_memory_region)*/
/*lint -esym(765,trim_memory_region)*/
/*lint -esym(759,prep_arg_passed_via_copy_constructor)*/
/*lint -esym(765,prep_arg_passed_via_copy_constructor)*/
/*lint -esym(759,make_predeclared_function_symbol)*/
/*lint -esym(765,make_predeclared_function_symbol)*/
/*lint -esym(759,check_target_configuration)*/
/*lint -esym(765,check_target_configuration)*/
/*lint -esym(769,ec_cannot_build_temp_file_name)*/
/*lint -esym(552,total_remarks)*/
/*lint -esym(552,restrict_enabled)*/
/*lint -esym(552,logical_char_info_entries_used)*/
/*lint -esym(551,caching_tokens)*/
/*lint -esym(759,crc_32)*/
/*lint -esym(765,crc_32)*/
/*lint -esym(759,add_to_inline_namespace_list)*/
/*lint -esym(765,add_to_inline_namespace_list)*/
/*lint -esym(714,db_format_integer_value)*/
/*lint -esym(714,db_prefix)*/
/*lint -esym(714,db_prefix_ptr)*/
/*lint -esym(757,db_long_double)*/
/*lint -esym(714,db_long_double)*/
/*lint -esym(714,db_sym)*/
/*lint -esym(714,db_hash_statistics)*/
/*lint -esym(714,db_corresp)*/
/*lint -esym(714,db_stop_tokens)*/
/*lint -esym(714,db_template_param_list)*/
/*lint -esym(714,db_text_buffer)*/
/*lint -esym(714,db_scope_pragmas)*/
/*lint -esym(714,db_translation_unit)*/
/*lint -esym(714,db_translation_unit_stack)*/
/*lint -esym(714,db_variable)*/
/*lint -esym(714,db_line_for_seq)*/
/*lint -esym(714,db_name_reference)*/
/*lint -esym(714,f_db_sym_has_traced_name)*/
/*lint -esym(714,db_top_of_scope_stack)*/
/*lint -esym(714,db_pack_tokens)*/
/*lint -esym(714,db_seq_number_lookup_table)*/
/*lint -esym(714,db_internal_float_value)*/
/*lint -esym(714,db_context_stack)*/
/*lint -esym(714,db_hide_by_sig_list)*/
/*lint -esym(714,db_init_component)*/
/*lint -esym(714,db_operand_ref_entries)*/
/*lint -esym(714,db_statements)*/
/*lint -esym(759,db_operand_ref_entries)*/
/*lint -esym(765,db_operand_ref_entries)*/
/*lint -esym(714,db_ref_entries)*/
/*lint -esym(759,db_ref_entries)*/
/*lint -esym(765,db_ref_entries)*/
/*lint -esym(714,free_template_decl_info)*/
/*lint -esym(759,f_db_sym_has_traced_name)*/
/*lint -esym(759,free_template_decl_info)*/
/*lint -esym(765,f_db_sym_has_traced_name)*/
/*lint -esym(765,free_template_decl_info)*/
/*lint -esym(755,db_sym_has_traced_name)*/
/*lint -esym(759,int_kind_name_full)*/
/*lint -esym(765,int_kind_name_full)*/
/*lint -esym(755,expect_error_str)*/
/*lint -esym(755,expect_error_str2)*/
/*lint -esym(755,check_assertion_or_expect_error)*/
/*lint -esym(755,check_assertion_or_expect_error_str)*/
/*lint -esym(755,check_assertion_or_expect_error_str2)*/
/*lint -esym(759, fetch_host_fp_value)*/
/*lint -esym(765, fetch_host_fp_value)*/
/*lint -esym(759,insert_string_into_token_stream)*/
/*lint -esym(765,insert_string_into_token_stream)*/
/*lint -esym(714,insert_string_into_token_stream)*/
/*lint -esym(755,alloc_cil_of_type)*/
/*lint -esym(714,enter_assert_predicate)*/
/*lint -esym(759,enter_assert_predicate)*/
/*lint -esym(765,enter_assert_predicate)*/
/*lint -esym(755,PREC_PRIMARY)*/
/*lint -esym(769,ec_bad_multibyte_char_locale)*/
/*lint -esym(759,clear_type)*/
/*lint -esym(765,clear_type)*/
/*lint -esym(755,is_cli_generic_instance_type)*/
/*lint -esym(759,put_str_into_text_buffer)*/
/*lint -esym(765,put_str_into_text_buffer)*/
/*lint -esym(755,complete_template_instance_is_needed)*/
/*lint -esym(759,is_template_dependent_type_or_cli_generic_param)*/
/*lint -esym(765,is_template_dependent_type_or_cli_generic_param)*/
/*lint -esym(756,an_other_pragma_function_ptr)*/
/*lint -esym(759,constant_is_shareable)*/
/*lint -esym(765,constant_is_shareable)*/
/*lint -esym(759,routine_and_node_from_function_expr)*/
/*lint -esym(765,routine_and_node_from_function_expr)*/
/*lint -esym(759,set_template_decl_info_for_class_definition)*/
/*lint -esym(765,set_template_decl_info_for_class_definition)*/
/*lint -esym(714,make_prefixed_object_name)*/
/*lint -esym(759,make_prefixed_object_name)*/
/*lint -esym(765,make_prefixed_object_name)*/
/*lint -esym(759,add_cast_to_node)*/
/*lint -esym(765,add_cast_to_node)*/
/*lint -esym(759,source_corresp_for_template_param)*/
/*lint -esym(765,source_corresp_for_template_param)*/
/*lint -esym(755,ignore_variable_in_back_end)*/
/*lint -esym(755,__builtin_offsetof)*/
/*lint -esym(759,variable_name_mangling_needed)*/
/*lint -esym(765,variable_name_mangling_needed)*/
/*lint -esym(714,type_is_nonreal)*/
/*lint -esym(759,type_is_nonreal)*/
/*lint -esym(765,type_is_nonreal)*/
/*lint -esym(714,entity_is_nonreal)*/
/*lint -esym(759,entity_is_nonreal)*/
/*lint -esym(765,entity_is_nonreal)*/
/*lint -esym(714,is_decltype_auto_template_param_type)*/
/*lint -esym(759,is_decltype_auto_template_param_type)*/
/*lint -esym(765,is_decltype_auto_template_param_type)*/
/*lint -esym(755,copy_simple_position_to_full_position)*/
/*lint -esym(769,ec_cl_back_end_requires_il_file)*/
/*lint -esym(769,ec_cl_could_not_open_il_file)*/
/*lint -esym(769,ec_cl_il_display_requires_il_file_name)*/
/*lint -esym(769,ec_old_fashioned_assignment_operator)*/
/*lint -esym(769,ec_old_fashioned_initializer)*/
/*lint -esym(755,DSI_ASM_ALLOWED)*/
/*lint -esym(769,ec_asm_func_must_be_prototyped)*/
/*lint -esym(769,ec_bad_asm_func_ellipsis)*/
/*lint -esym(769,ec_asm_not_allowed)*/
/*lint -esym(769,ec_bad_asm_function_def)*/
/*lint -esym(769,ec_nonstd_asm_function)*/
/*lint -esym(769,ec_nonstd_asm_decl_within_template)*/
/*lint -esym(769,ec_cl_incorrect_host_id)*/
/*lint -esym(769,ec_cl_too_many_arguments)*/
/*lint -esym(769,ec_cl_output_file_incompatible_with_multiple_inputs)*/
/*lint -esym(769,ec_cl_pch_incompatible_with_multiple_inputs)*/
/*lint -esym(769,ec_cl_ii_file_name_incompatible_with_multiple_inputs)*/
/*lint -esym(769,
       ec_cl_one_instantiation_per_object_incompatible_with_multiple_inputs)*/
/*lint -esym(769,ec_cl_invalid_pch_size)*/
/*lint -esym(769,ec_cl_pch_must_be_first)*/
/*lint -esym(769,ec_out_of_memory_during_pch_allocation)*/
/*lint -esym(769,ec_not_enough_preallocated_memory)*/
/*lint -esym(769,ec_program_entity_too_large_for_pch)*/
/*lint -esym(759,get_page_size)*/
/*lint -esym(765,get_page_size)*/
/*lint -esym(769,ec_invalid_mmap_address)*/
/*lint -esym(769,ec_double_for_long_double)*/
/*lint -esym(769,ec_different_return_type_on_virtual_function_override)*/
/*lint -esym(769,ec_bad_multibyte_char)*/
/*lint -esym(755,mbc_length)*/
/*lint -esym(755,mbc_scan_init)*/
/*lint -esym(769,a_unicode_source_kind::usk_utf8)*/
/*lint -esym(769,a_unicode_source_kind::usk_utf16LE)*/
/*lint -esym(769,a_unicode_source_kind::usk_utf16BE)*/
/*lint -esym(769,ec_cl_unrecognized_unicode_source_kind)*/
/*lint -esym(769,ec_bad_unicode_char_in_pp_output)*/
/*lint -esym(769,ec_non_unicode_char_in_ident)*/
/*lint -esym(769,ec_non_unicode_char_in_header)*/
/*lint -esym(769,ec_invalid_locale)*/
/*lint -esym(769,ec_bad_unicode_char_in_string)*/
/*lint -esym(759,form_char)*/
/*lint -esym(765,form_char)*/
/*lint -esym(759,traverse_type_tree)*/
/*lint -esym(765,traverse_type_tree)*/
/*lint -esym(755,routine_is_builtin_function_kind)*/
/*lint -esym(750,RDF_INDIRECT,RDF_THIS_PARAM_OFFSET)*/
/*lint -esym(714,alloc_unshared_constant_in_region)*/
/*lint -esym(759,alloc_unshared_constant_in_region)*/
/*lint -esym(765,alloc_unshared_constant_in_region)*/
/*lint -esym(552,virtual_function_table_definition)*/
/*lint -esym(759,alloc_unshared_constant_full)*/
/*lint -esym(765,alloc_unshared_constant_full)*/
/*lint -esym(759,clear_expr_node)*/
/*lint -esym(765,clear_expr_node)*/
/*lint -esym(759,implicit_cast)*/
/*lint -esym(765,implicit_cast)*/
/*lint -esym(759,parent_is_lambda_closure)*/
/*lint -esym(765,parent_is_lambda_closure)*/
/*lint -esym(759,find_disambiguator)*/
/*lint -esym(765,find_disambiguator)*/
/*lint -esym(759,find_local_static_variable_init)*/
/*lint -esym(765,find_local_static_variable_init)*/
/*lint -esym(714,find_assoc_pragma)*/
/*lint -esym(759,find_assoc_pragma)*/
/*lint -esym(765,find_assoc_pragma)*/
/*lint -esym(714,add_to_end_of_destructions_list)*/
/*lint -esym(759,add_to_end_of_destructions_list)*/
/*lint -esym(765,add_to_end_of_destructions_list)*/
/*lint -esym(759,alloc_node_for_allocated_constant)*/
/*lint -esym(765,alloc_node_for_allocated_constant)*/
/*lint -esym(759,new_or_delete_type_requires_array_handling)*/
/*lint -esym(765,new_or_delete_type_requires_array_handling)*/
/*lint -esym(759,int_kind_for_size_and_alignment)*/
/*lint -esym(765,int_kind_for_size_and_alignment)*/
/*lint -esym(714,rout_is_inline_template_function)*/
/*lint -esym(759,rout_is_inline_template_function)*/
/*lint -esym(765,rout_is_inline_template_function)*/
/*lint -esym(759,copy_list_of_expr_trees)*/
/*lint -esym(765,copy_list_of_expr_trees)*/
/*lint -esym(759,copy_node)*/
/*lint -esym(765,copy_node)*/
/*lint -esym(714,copy_statement)*/
/*lint -esym(759,copy_statement)*/
/*lint -esym(765,copy_statement)*/
/*lint -esym(759,copy_constant_full)*/
/*lint -esym(765,copy_constant_full)*/
/*lint -esym(759,set_class_keep_definition_in_il)*/
/*lint -esym(765,set_class_keep_definition_in_il)*/
/*lint -esym(759,set_expr_node_kind)*/
/*lint -esym(765,set_expr_node_kind)*/
/*lint -esym(759,set_node_operator)*/
/*lint -esym(765,set_node_operator)*/
/*lint -esym(759,set_scope_kind)*/
/*lint -esym(765,set_scope_kind)*/
/*lint -esym(759,set_statement_kind)*/
/*lint -esym(765,set_statement_kind)*/
/*lint -esym(759,is_default_operator_delete)*/
/*lint -esym(765,is_default_operator_delete)*/
/*lint -esym(714,num_array_elements)*/
/*lint -esym(759,num_array_elements)*/
/*lint -esym(765,num_array_elements)*/
/*lint -esym(714,num_vector_elements)*/
/*lint -esym(759,num_vector_elements)*/
/*lint -esym(765,num_vector_elements)*/
/*lint -esym(759,strip_rvalue_base_class_casts)*/
/*lint -esym(765,strip_rvalue_base_class_casts)*/
/*lint -esym(714,is_or_was_nullptr_type)*/
/*lint -esym(759,is_or_was_nullptr_type)*/
/*lint -esym(765,is_or_was_nullptr_type)*/
/*lint -esym(765,do_type_name_mangling)*/
/*lint -esym(714,make_comma_node_if_necessary)*/
/*lint -esym(759,make_comma_node_if_necessary)*/
/*lint -esym(765,make_comma_node_if_necessary)*/
/*lint -esym(714,add_cast_to_glvalue_if_necessary)*/
/*lint -esym(759,add_cast_to_glvalue_if_necessary)*/
/*lint -esym(765,add_cast_to_glvalue_if_necessary)*/
/*lint -esym(759,glvalue_expr_reusable_copy)*/
/*lint -esym(765,glvalue_expr_reusable_copy)*/
/*lint -esym(759,find_mv_target_specific_routine)*/
/*lint -esym(765,find_mv_target_specific_routine)*/
/*lint -esym(769,ec_resolver_routine_required)*/
/*lint -esym(769,ec_invalid_target_attribute)*/
/*lint -esym(759,constant_fully_initializes_type)*/
/*lint -esym(714,constant_fully_initializes_type)*/
/*lint -esym(765,constant_fully_initializes_type)*/
/*lint -esym(759,copy_array_type_replacing_element_type)*/
/*lint -esym(765,copy_array_type_replacing_element_type)*/
/*lint -esym(759,mangle_function_name)*/
/*lint -esym(765,mangle_function_name)*/
/*lint -esym(759,add_to_destructions_list)*/
/*lint -esym(765,add_to_destructions_list)*/
/*lint -esym(769,ec_compound_lvalue_as_asm_operand)*/
/*lint -esym(552,inline_variables_in_comdat)*/
/*lint -esym(769,ec_invalid_std_comparison_type)*/
/*lint -esym(714,clang_target_version_number)*/
/*lint -esym(759,clang_target_version_number)*/
/*lint -esym(765,clang_target_version_number)*/
/*lint -esym(714,is_address_of_string_constant)*/
/*lint -esym(759,is_address_of_string_constant)*/
/*lint -esym(765,is_address_of_string_constant)*/
/*lint -esym(759,form_unknown_function_constant)*/
/*lint -esym(765,form_unknown_function_constant)*/
/*lint -esym(751,a_template_param_map_level)*/
/*lint -esym(759,form_uuidof_reference)*/
/*lint -esym(765,form_uuidof_reference)*/
/*lint -esym(759,form_typeid_reference)*/
/*lint -esym(765,form_typeid_reference)*/
/*lint -esym(759,decltype_arg)*/
/*lint -esym(765,decltype_arg)*/
/*lint -esym(769,ec_generated_c_plus_plus)*/
/*lint -esym(759,get_param_for_param_ref)*/
/*lint -esym(765,get_param_for_param_ref)*/
/*lint -esym(769,an_attribute_location::al_id_equivalent_as_postfix)*/
/*lint -esym(759,form_calling_convention)*/
/*lint -esym(765,form_calling_convention)*/
/*lint -esym(759,form_pointer_modifiers)*/
/*lint -esym(765,form_pointer_modifiers)*/
/*lint -esym(759,find_ms_attribute_for_entity)*/
/*lint -esym(765,find_ms_attribute_for_entity)*/
/*lint -esym(714,find_ms_attribute_for_entity)*/
/*lint -esym(759,form_property_or_event_name_as_qualifier_if_needed)*/
/*lint -esym(765,form_property_or_event_name_as_qualifier_if_needed)*/
/*lint -esym(755,next_non_empty_field)*/
/*lint -esym(755,next_non_empty_initializable_field)*/
/*lint -esym(759,conv_prvalue_expr_to_object_pointer)*/
/*lint -esym(765,conv_prvalue_expr_to_object_pointer)*/
/*lint -esym(714,conv_prvalue_expr_to_object_pointer)*/
/*lint -esym(749,pfs_last)*/
/*lint -esym(528,add_other_pragma_kind_description)*/
/*lint -esym(526,fileno)*/
/*lint -esym(526,isnan)*/
/*lint -esym(526,finite)*/
/*lint -esym(752,finite)*/
/*lint -esym(752,isnan)*/
/*lint -esym(769,ec_nonobject_pointer_arithmetic)*/
/*lint -esym(769,ec_noreturn_function_does_return)*/
/*lint -esym(769,ec_invalid_empty_initializer_list)*/
/*lint -esym(759,constant_prvalue_pointer_full)*/
/*lint -esym(765,constant_prvalue_pointer_full)*/
/*lint -esym(552,clang_version)*/
/*lint -esym(759,type_returned_by_cctor)*/
/*lint -esym(765,type_returned_by_cctor)*/
/*lint -esym(759,lower_c99_statement)*/
/*lint -esym(765,lower_c99_statement)*/
/*lint -esym(759,field_alignment_for)*/
/*lint -esym(765,field_alignment_for)*/
/*lint -esym(769,ec_bad_variable_for_init_priority)*/
/*lint -esym(769,ec_init_priority_reserved)*/
/*lint -esym(769,ec_ctor_dtor_priority_reserved)*/
/*lint -esym(769,ec_attribute_ignored_for_thread_local)*/
/*lint -esym(759,trace_entry)*/
/*lint -esym(765, trace_entry)*/
/*lint -esym(714, trace_entry)*/
/*lint -esym(769,ec_intermediate_language_7)*/
/*lint -esym(756,an_il_entry_number)*/
/*lint -esym(759,init_memory_region)*/
/*lint -esym(765,init_memory_region)*/
/*lint -esym(765, db_sym_list)*/
/*lint -esym(714, db_sym_list)*/
/*lint -esym(714, db_scheduled_routine_moves)*/
/*lint -esym(765, db_attribute_list)*/
/*lint -esym(714, db_attribute_list)*/
/*lint -esym(765, db_based_types)*/
/*lint -esym(714, db_based_types)*/
/*lint -esym(765, db_signed_integer_value)*/
/*lint -esym(714, db_signed_integer_value)*/
/*lint -esym(765, db_hash_ptr)*/
/*lint -esym(714, db_hash_ptr)*/
/*lint -esym(765, db_int_val)*/
/*lint -esym(714, db_complete_object)*/
/*lint -esym(765, db_complete_object)*/
/*lint -esym(714, db_int_val)*/
/*lint -esym(765, db_call_stack)*/
/*lint -esym(714, db_call_stack)*/
/*lint -esym(765, db_stack_storage)*/
/*lint -esym(714, db_stack_storage)*/
/*lint -esym(765, db_rescan_list)*/
/*lint -esym(714, db_rescan_list)*/
/*lint -esym(765, db_data_map)*/
/*lint -esym(714, db_data_map)*/
/*lint -esym(765, db_live_set)*/
/*lint -esym(714, db_live_set)*/
/*lint -esym(765, db_object_alloc_num)*/
/*lint -esym(714, db_object_alloc_num)*/
/*lint -esym(765, db_substitution_stack)*/
/*lint -esym(714, db_substitution_stack)*/
/*lint -esym(765, db_dip)*/
/*lint -esym(714, db_dip)*/
/*lint -esym(765, db_subobject_path)*/
/*lint -esym(714, db_subobject_path)*/
/*lint -esym(765, db_icp_list)*/
/*lint -esym(714, db_icp_list)*/
/*lint -esym(765, db_subst_pairs)*/
/*lint -esym(714, db_subst_pairs)*/
/*lint -esym(765, db_type_entries)*/
/*lint -esym(714, db_type_entries)*/
/*lint -esym(769,ec_unrecognized_upc_pragma)*/
/*lint -esym(769,ec_mismatched_shared_block_size)*/
/*lint -esym(769,ec_ambiguous_block_size_spec)*/
/*lint -esym(769,ec_shared_block_size_must_be_positive)*/
/*lint -esym(769,ec_multiple_block_sizes)*/
/*lint -esym(769,ec_nonshared_strict_relaxed)*/
/*lint -esym(769,ec_threads_constant_not_allowed)*/
/*lint -esym(769,ec_shared_block_size_too_large)*/
/*lint -esym(769,ec_function_returning_shared)*/
/*lint -esym(769,ec_shared_nonthreads_dim)*/
/*lint -esym(769,ec_shared_inside_struct)*/
/*lint -esym(769,ec_shared_parameter)*/
/*lint -esym(769,ec_threads_dimension_requires_definite_block_size)*/
/*lint -esym(769,ec_bad_shared_storage_class)*/
/*lint -esym(769,ec_nonshared_blocksizeof)*/
/*lint -esym(769,ec_nested_upc_forall)*/
/*lint -esym(769,ec_exit_forall)*/
/*lint -esym(769,ec_unexpected_upc_shared_specifier)*/
/*lint -esym(769,ec_bad_affinity)*/
/*lint -esym(769,ec_shared_affinity_type)*/
/*lint -esym(769,ec_upc_shared_void_comparison)*/
/*lint -esym(769,ec_cl_upc_requires_ansi_c_dialect)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_fsqrt)*/
/*lint -esym(759,find_progenitor_symbol)*/
/*lint -esym(765,find_progenitor_symbol)*/
/*lint -esym(769,ec_cfront_name_lookup_bug)*/
/*lint -esym(759,add_constructor_wrapper_code)*/
/*lint -esym(765,add_constructor_wrapper_code)*/
/*lint -esym(769,ec_assignment_to_this)*/
/*lint -esym(759,is_this_parameter_operand)*/
/*lint -esym(765,is_this_parameter_operand)*/
/*lint -esym(759,initial_processing_on_destructible_initialization)*/
/*lint -esym(765,initial_processing_on_destructible_initialization)*/
/*lint -esym(755,first_derivation_is_direct)*/
/*lint -esym(759,repr_for_ptr_to_data_member_constant)*/
/*lint -esym(765,repr_for_ptr_to_data_member_constant)*/
/*lint -esym(759,repr_for_ptr_to_member_function_constant)*/
/*lint -esym(765,repr_for_ptr_to_member_function_constant)*/
/*lint -esym(759,make_typeinfo_type)*/
/*lint -esym(765,make_typeinfo_type)*/
/*lint -esym(759,make_ctor_implied_arg_list)*/
/*lint -esym(765,make_ctor_implied_arg_list)*/
/*lint -esym(759,make_dtor_implied_arg_list)*/
/*lint -esym(765,make_dtor_implied_arg_list)*/
/*lint -esym(759,do_type_name_mangling)*/
/*lint -esym(765,do_type_name_mangling)*/
/*lint -esym(769,ec_mangled_name_too_long)*/
/*lint -esym(759,vtbl_addr_from_construction_vtbls_array)*/
/*lint -esym(765,vtbl_addr_from_construction_vtbls_array)*/
/*lint -esym(755,TARG_INT128_FIELD_ALIGNMENT_win64)*/
/*lint -esym(755,TARG_RUNTIME_ELEM_COUNT_INT_KIND_win64)*/
/*lint -esym(755,TARG_ETS_FLAG_TYPE_INT_KIND_win64)*/
/*lint -esym(755,TARG_SIZEOF_PTR_TO_VIRTUAL_BASE_CLASS_win64)*/
/*lint -esym(755,TARG_ALIGNOF_PTR_TO_VIRTUAL_BASE_CLASS_win64)*/
/*lint -esym(755,TARG_INT128_FIELD_ALIGNMENT_win32)*/
/*lint -esym(755,TARG_RUNTIME_ELEM_COUNT_INT_KIND_win32)*/
/*lint -esym(755,TARG_ETS_FLAG_TYPE_INT_KIND_win32)*/
/*lint -esym(755,TARG_SIZEOF_PTR_TO_VIRTUAL_BASE_CLASS_win32)*/
/*lint -esym(755,TARG_ALIGNOF_PTR_TO_VIRTUAL_BASE_CLASS_win32)*/
/*lint -esym(759,add_cast_to_char_star)*/
/*lint -esym(765,add_cast_to_char_star)*/
/*lint -esym(759,type_info_names)*/
/*lint -esym(765,type_info_names)*/
/*lint -esym(759,expr_list_has_side_effects)*/
/*lint -esym(765,expr_list_has_side_effects)*/
/*lint -esym(714,expr_list_has_side_effects)*/
/*lint -esym(769,ec_field_uses_tail_padding)*/
/*lint -esym(769,ec_base_uses_tail_padding)*/
/*lint -esym(769,ec_size_affected_by_tail_padding)*/
/*lint -esym(769,ec_gnu_may_use_bit_padding)*/
/*lint -esym(769,ec_no_gnu_virtual_base_gap)*/
/*lint -esym(769,ec_gnu_virtual_base_gap)*/
/*lint -esym(759,build_construction_vtbls_pointer)*/
/*lint -esym(765,build_construction_vtbls_pointer)*/
/*lint -esym(769,ec_no_default_delete_in_virtual_dtor)*/
/*lint -esym(759,should_drop_const_on_this_param_variable)*/
/*lint -esym(765,should_drop_const_on_this_param_variable)*/
/*lint -esym(759,make_vtbl_entry_type)*/
/*lint -esym(765,make_vtbl_entry_type)*/
/*lint -esym(756,uintptr_t)*/
/*lint -esym(755,TARG_IA64_ABI_USE_GUARD_ACQUIRE_RELEASE_win32)*/
/*lint -esym(755,TARG_IA64_ABI_USE_GUARD_ACQUIRE_RELEASE_win64)*/
/*lint -esym(755,TARG_IA64_ABI_USE_INT_STATIC_INIT_GUARD_win32)*/
/*lint -esym(755,TARG_IA64_ABI_USE_INT_STATIC_INIT_GUARD_win64)*/
/*lint -esym(755,TARG_IA64_ABI_USE_VARIANT_ARRAY_COOKIES_win32)*/
/*lint -esym(755,TARG_IA64_ABI_USE_VARIANT_ARRAY_COOKIES_win64)*/
/*lint -esym(755,TARG_IA64_ABI_USE_VARIANT_PTR_TO_MEMBER_FUNCTION_REPR_win32)*/
/*lint -esym(755,TARG_IA64_ABI_USE_VARIANT_PTR_TO_MEMBER_FUNCTION_REPR_win64)*/
/*lint -esym(755,TARG_IA64_ABI_VARIANT_CTORS_AND_DTORS_RETURN_THIS_win32)*/
/*lint -esym(755,TARG_IA64_ABI_VARIANT_CTORS_AND_DTORS_RETURN_THIS_win64)*/
/*lint -esym(755,TARG_IA64_ABI_VARIANT_KEY_FUNCTION_win32)*/
/*lint -esym(755,TARG_IA64_ABI_VARIANT_KEY_FUNCTION_win64)*/
/*lint -esym(755,TARG_IA64_VTABLE_ENTRY_INT_KIND_win64)*/
/*lint -esym(755,TARG_IA64_VTABLE_ENTRY_INT_KIND_win32)*/
/*lint -esym(755,TARG_REUSE_TAIL_PADDING_win64)*/
/*lint -esym(755,TARG_REUSE_TAIL_PADDING_win32)*/
/*lint -esym(759,get_mangled_function_name_full)*/
/*lint -esym(765,get_mangled_function_name_full)*/
/*lint -esym(769,ec_cfront_multiple_nested_types)*/
/*lint -esym(769,ec_cfront_global_defined_after_nested_type)*/
/*lint -esym(759,make_file_scope_temporary)*/
/*lint -esym(765,make_file_scope_temporary)*/
/*lint -esym(769,ec_bad_linkage_for_redefine_extname)*/
/*lint -esym(759,traverse_statement)*/
/*lint -esym(765,traverse_statement)*/
/*lint -esym(759,traverse_statement_list)*/
/*lint -esym(765,traverse_statement_list)*/
/*lint -esym(769,an_ms_attribute_kind::msak_last)*/
/*lint -esym(769,a_microsoft_pragma_comment_type::mpct_compiler)*/
/*lint -esym(769,a_microsoft_pragma_comment_type::mpct_exestr)*/
/*lint -esym(769,a_microsoft_pragma_comment_type::mpct_lib)*/
/*lint -esym(769,a_microsoft_pragma_comment_type::mpct_linker)*/
/*lint -esym(769,a_microsoft_pragma_comment_type::mpct_user)*/
/*lint -esym(769,a_microsoft_pragma_comment_type::mpct_last)*/
/*lint -esym(552,ms_permissive)*/
/*lint -esym(759,fixed_point_enabled)*/
/*lint -esym(765,fixed_point_enabled)*/
/*lint -esym(769,ec_nonstd_fixed_point_suffix)*/
/*lint -esym(769,ec_cl_fixed_point_option_only_in_C)*/
/*lint -esym(769,ec_integer_may_not_fit_in_fixed_point_result)*/
/*lint -esym(769,ec_bad_fixed_point_value)*/
/*lint -esym(769,ec_inexact_fxp_conversion)*/
/*lint -esym(769,ec_operation_may_not_fit_in_fixed_point_result)*/
/*lint -esym(769,ec_implicit_fixed_point_to_floating_point_conversion)*/
/*lint -esym(769,ec_no_classification_for_fixed_point_type)*/
/*lint -esym(769,ec_fixed_template_parameter)*/
/*lint -esym(769,ec_float_to_fixed_conversion)*/
/*lint -esym(769,ec_inexact_fixed_conversion)*/
/*lint -esym(769,ec_fixed_sign_change)*/
/*lint -esym(769,ec_integer_to_fixed_conversion)*/
/*lint -esym(769,ec_bad_fixed_operation_result)*/
/*lint -esym(769,ec_fixed_to_float_conversion)*/
/*lint -esym(769,ec_fixed_to_integer_conversion)*/
/*lint -esym(769,ec_fixed_to_fixed_conversion)*/
/*lint -esym(759,number_of_bits_in_mantissa)*/
/*lint -esym(765,number_of_bits_in_mantissa)*/
/*lint -esym(759,init_mantissa)*/
/*lint -esym(765,init_mantissa)*/
/*lint -esym(759,round_hex_fp_value)*/
/*lint -esym(765,round_hex_fp_value)*/
/*lint -esym(759,conv_hex_string_to_mantissa_and_exponent)*/
/*lint -esym(765,conv_hex_string_to_mantissa_and_exponent)*/
/*lint -esym(759,shift_left_mantissa)*/
/*lint -esym(765,shift_left_mantissa)*/
/*lint -esym(759,shift_right_mantissa)*/
/*lint -esym(765,shift_right_mantissa)*/
/*lint -esym(759,get_integer_attributes)*/
/*lint -esym(765,get_integer_attributes)*/
/*lint -esym(759,trunc_and_set_integer)*/
/*lint -esym(765,trunc_and_set_integer)*/
/*lint -esym(759,mantissa_is_zero)*/
/*lint -esym(765,mantissa_is_zero)*/
/*lint -esym(759,conv_mantissa_to_floating_point)*/
/*lint -esym(765,conv_mantissa_to_floating_point)*/
/*lint -esym(759,value_of_integer_value)*/
/*lint -esym(765,value_of_integer_value)*/
/*lint -esym(714,str_for_integer_value)*/
/*lint -esym(759,str_for_integer_value)*/
/*lint -esym(765,str_for_integer_value)*/
/*lint -esym(769,tok_fract)*/
/*lint -esym(769,tok_accum)*/
/*lint -esym(759,named_address_spaces_enabled)*/
/*lint -esym(765,named_address_spaces_enabled)*/
/*lint -esym(769,ec_cl_named_address_spaces_option_only_in_C)*/
/*lint -esym(769,ec_multiple_named_address_spaces)*/
/*lint -esym(769,ec_bad_storage_class_for_named_address_space_variable)*/
/*lint -esym(769,ec_type_with_named_address_space_not_allowed)*/
/*lint -esym(769,ec_named_address_space_on_function_type)*/
/*lint -esym(769,ec_field_type_cannot_be_qualified_with_named_address_space)*/
/*lint -esym(769,ec_named_address_space_not_allowed)*/
/*lint -esym(769,ec_cl_named_registers_option_only_in_C)*/
/*lint -esym(769,ec_named_register_not_allowed)*/
/*lint -esym(769,ec_register_storage_class_conflict)*/
/*lint -esym(769,ec_aliased_variable_cannot_have_register_storage_class)*/
/*lint -esym(769,ec_register_in_use)*/
/*lint -esym(769,ec_missing_named_register_storage_class)*/
/*lint -esym(769,ec_previous_decl_at)*/
/*lint -esym(769,ec_register_too_small)*/
/*lint -esym(769,ec_no_named_register_for_array)*/
/*lint -esym(769,
          ec_embedded_c_option_incompatible_with_individual_feature_options)*/
/*lint -esym(750,PFS_TRANSACTION_SAFE)*/
/*lint -esym(759,add_to_end_of_pending_stmk_init_statements_list)*/
/*lint -esym(765,add_to_end_of_pending_stmk_init_statements_list)*/
/*lint -esym(759,assign_expr_to_temp)*/
/*lint -esym(765,assign_expr_to_temp)*/
/*lint -esym(759, fixed_point_type_used_in_primary_IL)*/
/*lint -esym(765, fixed_point_type_used_in_primary_IL)*/
/*lint -esym(759, make_lvalue_reusable_copy_full)*/
/*lint -esym(765, make_lvalue_reusable_copy_full)*/
/*lint -esym(714,function_scope_for_local_type)*/
/*lint -esym(759,function_scope_for_local_type)*/
/*lint -esym(765,function_scope_for_local_type)*/
/*lint -esym(759,update_extended_decl_info_for_class)*/
/*lint -esym(765,update_extended_decl_info_for_class)*/
/*lint -esym(769,ec_cl_vla_option_only_in_C)*/
/*lint -esym(769,ec_sfinae_requires_newer_abi_version)*/
/*lint -esym(769,ec_cppcli_requires_newer_abi_version)*/
/*lint -esym(769,ec_delegating_constructor_requires_newer_abi_version)*/
/*lint -esym(769,ec_in_macro_expansion_at)*/
/*lint -esym(769,ec_name_of_unknown_macro)*/
/*lint -esym(769,ec_in_expansion_of_macro)*/
/*lint -esym(769,ec_macro_context_lines_skipped)*/
/*lint -esym(769,ec_in_expansion_of_macro_last)*/
/*lint -esym(769,ec_if_exists_not_allowed)*/
/*lint -esym(769,ec_if_exists_not_closed)*/
/*lint -esym(755,string_constants_are_the_same)*/
/*lint -esym(769,a_builtin_operation_kind::bok_types_compatible)*/
/*lint -esym(769,ec_gnu_attr_on_template_redecl)*/
/*lint -esym(769,ec_gnu_attr_on_template_redecl_but_original_kept)*/
/*lint -esym(769,ec_no_packing_of_non_POD_field)*/
/*lint -esym(769,ec_missing_gnu_inline_attr_on_redeclaration)*/
/*lint -esym(769,ec_pragma_gcc_system_header_in_primary_file)*/
/*lint -esym(769,ec_3rd_arg_of_assume_aligned_must_be_integral)*/
/*lint -esym(769,ec_only_gnu_attributes_here)*/
/*lint -esym(769,ec_bad_argument_for_bases)*/
/*lint -esym(769,ec_bad_prototype_argument_for_bases)*/
/*lint -esym(769,ec_bases_not_in_template)*/
/*lint -esym(769,ec_always_inline_requires_inline)*/
/*lint -esym(769,ec_exp_asm_label)*/
/*lint -esym(769,ec_missing_label_operand_number)*/
/*lint -esym(769,ec_label_operand_number_out_of_range)*/
/*lint -esym(769,ec_rvalue_references_is_cpp11)*/
/*lint -esym(769,ec_lambdas_is_cpp11)*/
/*lint -esym(769,ec_std_attributes_is_cpp11)*/
/*lint -esym(769,ec_delegating_constructor_is_cpp11)*/
/*lint -esym(769,ec_inheriting_constructor_is_cpp11)*/
/*lint -esym(769,ec_field_initializers_is_cpp11)*/
/*lint -esym(769,ec_deleted_functions_is_cpp11)*/
/*lint -esym(769,ec_defaulted_functions_is_cpp11)*/
/*lint -esym(769,ec_alias_declaration_is_cpp11)*/
/*lint -esym(769,ec_alias_template_is_cpp11)*/
/*lint -esym(769,ec_enum_qualifier_is_cpp11)*/
/*lint -esym(769,ec_cl_clang_mode_only_in_cplusplus)*/
/*lint -esym(769,ec_incompatible_ifunc_resolver_type)*/
/*lint -esym(769,ec_ifunc_cant_be_alias)*/
/*lint -esym(769,ec_ifunc_cant_be_weak)*/
/*lint -esym(769,ec_call_requires_string_literal)*/
/*lint -esym(769,ec_target_string_must_be_narrow)*/
/*lint -esym(769,ec_target_unmatched_parens)*/
/*lint -esym(769,ec_gcc_pragma_nothing_to_pop)*/
/*lint -esym(769,ec_pragma_inside_function)*/
/*lint -esym(769,ec_extended_friends_is_cpp11)*/
/*lint -esym(769,ec_bad_gnu_stmt_return)*/
/*lint -esym(769,ec_abi_tag_ignored_in_C_mode)*/
/*lint -esym(769,ec_abi_tag_redefinition)*/
/*lint -esym(769,ec_abi_tag_ignored)*/
/*lint -esym(769,ec_no_abi_tag_on_declaration)*/
/*lint -esym(769,ec_abi_tag_prev_declaration)*/
/*lint -esym(769,ec_abi_tag_ignored_on_specialization)*/
/*lint -esym(769,ec_ignoring_attribute_on_non_inline_namespace)*/
/*lint -esym(769,ec_ignoring_attribute_on_anonymous_namespace)*/
/*lint -esym(769,ec_constexpr_weak_address)*/
/*lint -esym(769,ec_no_float80)*/
/*lint -esym(769,ec_no_float128)*/
/*lint -esym(769,ec_if_constexpr_is_cpp17)*/
/*lint -esym(769,ec_cannot_be_common_internal_linkage)*/
/*lint -esym(769,ec_internal_linkage_not_on_prior_declaration)*/
/*lint -esym(759,same_string_ignoring_underscores)*/
/*lint -esym(765,same_string_ignoring_underscores)*/
/*lint -esym(714,same_string_ignoring_underscores)*/
/*lint -esym(759,put_str_to_f_debug)*/
/*lint -esym(765,put_str_to_f_debug)*/
/*lint -esym(759,is_wide_string_constant)*/
/*lint -esym(765,is_wide_string_constant)*/
/*lint -esym(714,is_wide_string_constant)*/
/*lint -esym(755,extract_wide_char_from_string)*/
/*lint -esym(755,wide_string_type)*/
/*lint -esym(769,ec_microsoft_version_doesnt_support_cpp14_mode)*/
/*lint -esym(769,ec_microsoft_version_doesnt_support_cpp17_mode)*/
/*lint -esym(769,ec_microsoft_version_doesnt_support_cpp20_mode)*/
/*lint -esym(769,ec_microsoft_version_doesnt_support_cpplatest_mode)*/
/*lint -esym(769,ec_too_many_template_arguments)*/
/*lint -esym(769,ec_invalid_event_handler_type)*/
/*lint -esym(769,ec_event_interface_must_be_previously_defined)*/
/*lint -esym(769,ec_event_interface_cannot_have_definition)*/
/*lint -esym(769,ec_cl_unrecognized_calling_convention)*/
/*lint -esym(769,ec_cl_calling_convention_list)*/
/*lint -esym(769,ec_microsoft_interface)*/
/*lint -esym(769,ec_default_member_init_for_value_class)*/
/*lint -esym(769,a_builtin_operation_kind::bok_has_finalizer)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_delegate)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_interface_class)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_ref_array)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_ref_class)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_sealed)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_simple_value_class)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_value_class)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_win_class)*/
/*lint -esym(769,a_builtin_operation_kind::bok_is_win_interface)*/
/*lint -esym(759,curr_token_is_identifier_string)*/
/*lint -esym(765,curr_token_is_identifier_string)*/
/*lint -esym(759,is_assignment_operator_for_copy)*/
/*lint -esym(765,is_assignment_operator_for_copy)*/
/*lint -esym(759,mark_init_component_list_as_permanently_allocated)*/
/*lint -esym(765,mark_init_component_list_as_permanently_allocated)*/
/*lint -esym(552,microsoft_build_number)*/
/*lint -esym(759,check_internal_template_instantiation)*/
/*lint -esym(765,check_internal_template_instantiation)*/
/*lint -esym(757,make_make_integer_seq_internal_template)*/
/*lint -esym(755,GID_IS_CPPCLI_CONSTRAINT)*/
/*lint -esym(769,ec_coclass_base_requirements_not_met)*/
/*lint -esym(759, lower_c99_constant_expr)*/
/*lint -esym(765, lower_c99_constant_expr)*/
/*lint -esym(759, walk_parents)*/
/*lint -esym(765, walk_parents)*/
/*lint -esym(714, walk_parents)*/
/*lint -esym(759, alloc_list_entry_for_constant)*/
/*lint -esym(765, alloc_list_entry_for_constant)*/
/*lint -esym(714, alloc_list_entry_for_constant)*/
/*lint -esym(759, free_list_of_constant_list_entries)*/
/*lint -esym(765, free_list_of_constant_list_entries)*/
/*lint -esym(714, free_list_of_constant_list_entries)*/
/*lint -esym(768, a_walk_parents_control_block::ptr)*/
/*lint -esym(759,set_complex_constant)*/
/*lint -esym(765,set_complex_constant)*/
/*lint -esym(714,set_complex_constant)*/
/*lint -esym(759,alignment_of_variable)*/
/*lint -esym(765,alignment_of_variable)*/
/*lint -esym(714,alignment_of_variable)*/
/*lint -esym(769,ec_bad_type_for_gnu_sync_function)*/
/*lint -esym(769,ec_invalid_gnu_sync_size)*/
/*lint -esym(769,ec_extra_arguments_ignored)*/
/*lint -esym(769,ec_first_arg_must_be_integer_constant)*/
/*lint -esym(769,ec_builtin_needs_128_bit_integers)*/
/*lint -esym(769,ec_builtin_needs_128_bit_floats)*/
/*lint -esym(769,ec_builtin_needs_vector_types)*/
/*lint -esym(769,ec_bad_asm_constraint_modifier)*/
/*lint -esym(769,ec_bad_asm_constraint_letter)*/
/*lint -esym(769,ec_missing_constraint_letter)*/
/*lint -esym(769,ec_asm_output_must_have_output_mod)*/
/*lint -esym(769,ec_asm_input_must_not_have_output_mod)*/
/*lint -esym(769,ec_register_used_twice)*/
/*lint -esym(769,ec_register_used_and_clobbered)*/
/*lint -esym(769,ec_fixed_register_used)*/
/*lint -esym(769,ec_match_limit_for_symbolic_asm_operand)*/
/*lint -esym(769,ec_constraint_number_mismatch)*/
/*lint -esym(769,ec_too_many_constraints)*/
/*lint -esym(759,conv_float_string_to_integer_value)*/
/*lint -esym(765,conv_float_string_to_integer_value)*/
/*lint -esym(714,conv_float_string_to_integer_value)*/
/*lint -esym(769,ec_unrecognized_gcc_pragma)*/
/*lint -esym(769,ec_unrecognized_gcc_visibility_pragma)*/
/*lint -esym(769,ec_gnu_visibility_conflict)*/
/*lint -esym(769,ec_unrecognized_visibility)*/
/*lint -esym(769,ec_attribute_does_not_apply_to_type)*/
/*lint -esym(769,ec_ELF_visibility_pop_mismatch)*/
/*lint -esym(769,ec_ELF_visibility_stack_empty)*/
/*lint -esym(769,
            ec_vector_size_attribute_requires_integral_floating_or_enum_type)*/
/*lint -esym(769,ec_vector_size_too_large)*/
/*lint -esym(769,ec_vector_size_must_be_power_of_two)*/
/*lint -esym(769,ec_vector_size_must_be_multiple_of_element_size)*/
/*lint -esym(769,ec_mixed_vector_scalar_operation)*/
/*lint -esym(769,ec_vectors_must_have_same_size)*/
/*lint -esym(769,ec_dependent_vector_size)*/
/*lint -esym(769,ec_vector_size_with_dependent_element_type)*/
/*lint -esym(769,ec_vector_size_attribute_not_allowed)*/
/*lint -esym(769,ec_vector_size_attribute_on_complex_type)*/
/*lint -esym(769,ec_vector_size_must_be_integer_constant)*/
/*lint -esym(769,ec_vector_element_type_mismatch)*/
/*lint -esym(769,ec_vector_operation_requires_integer_vector)*/
/*lint -esym(769,ec_vector_size_attribute_on_enum_type)*/
/*lint -esym(769,ec_incompatible_vectors_conversion)*/
/*lint -esym(769,ec_vector_template_parameter)*/
/*lint -esym(769,ec_operand_must_be_vector)*/
/*lint -esym(769,ec_incompatible_shuffle_source_operands)*/
/*lint -esym(769,ec_nonintegral_shuffle_mask)*/
/*lint -esym(769,ec_incompatible_shuffle_mask)*/
/*lint -esym(769,a_builtin_operation_kind::bok_builtin_shuffle)*/
/*lint -esym(769,a_builtin_operation_kind::bok_builtin_shufflevector)*/
/*lint -esym(769,ec_shufflevector_index_out_of_range)*/
/*lint -esym(769,ec_invalid_vector_element_type)*/
/*lint -esym(769,ec_vector_length_too_large)*/
/*lint -esym(769,a_builtin_operation_kind::bok_builtin_convertvector)*/
/*lint -esym(769,ec_vector_type_required)*/
/*lint -esym(769,ec_vector_types_differ_in_length)*/
/*lint -esym(769,ec_ext_vector_type_invalid_size)*/
/*lint -esym(769,ec_ext_vector_type_not_in_typedef)*/
/*lint -esym(769,ec_ext_vector_type_requires_integral_floating_type)*/
/*lint -esym(759,find_local_scope)*/
/*lint -esym(765,find_local_scope)*/
/*lint -esym(714,find_local_scope)*/
/*lint -esym(759,node_operands_have_correct_value_category)*/
/*lint -esym(765,node_operands_have_correct_value_category)*/
/*lint -esym(714,node_operands_have_correct_value_category)*/
/*lint -esym(759,tree_has_correct_lvalueness)*/
/*lint -esym(765,tree_has_correct_lvalueness)*/
/*lint -esym(714,tree_has_correct_lvalueness)*/
/*lint -esym(759,f_get_parent_scope_of)*/
/*lint -esym(765,f_get_parent_scope_of)*/
/*lint -esym(714,f_get_parent_scope_of)*/
/*lint -esym(755,get_parent_scope_of)*/
/*lint -esym(759,node_includes_glvalue_to_prvalue_conv)*/
/*lint -esym(765,node_includes_glvalue_to_prvalue_conv)*/
/*lint -efunc(670,macro_invocation)*/
/*lint -efunc(690,macro_invocation)*/
/*lint -esym(769,ec_call_requires_one_argument)*/
/*lint -esym(769,ec_call_requires_floating_point_argument)*/
/*lint -esym(759, node_is_pointer_with_restrict_semantics)*/
/*lint -esym(765, node_is_pointer_with_restrict_semantics)*/
/*lint -esym(714, node_is_pointer_with_restrict_semantics)*/
/*lint -esym(769,an_attribute_arg_kind::aak_last)*/
/*lint -esym(769,an_attribute_family::af_ms_declspec)*/
/*lint -esym(769,an_attribute_location::al_base_specifier)*/
/*lint -esym(769,an_attribute_location::al_trailing_return)*/
/*lint -esym(769,an_attribute_location::al_other)*/
/*lint -esym(769,an_attribute_location::al_last)*/
/*lint -esym(769,an_expr_node_kind::enk_runtime_sizeof)*/
/*lint -esym(552,using_framework_directory)*/
/*lint -esym(769,ec_win32_api_error)*/
/*lint -esym(769,a_cpp_cli_feature::*)*/
/*lint -esym(769,a_cpp_cli_import_flag::*)*/
/*lint -esym(759,clear_portable_assembly_header)*/
/*lint -esym(765,clear_portable_assembly_header)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_int16)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_uint16)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_int32)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_uint32)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_int32_is_long)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_uint32_is_long)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_int64)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_uint64)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_single)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_double)*/
/*lint -esym(769,a_cli_symbol_kind::csk_system_double_is_long)*/
/*lint -esym(769,a_cli_operator_kind::cok_addition)*/
/*lint -esym(769,a_cli_operator_kind::cok_addition_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_address_of)*/
/*lint -esym(769,a_cli_operator_kind::cok_assign)*/
/*lint -esym(769,a_cli_operator_kind::cok_bitwise_and)*/
/*lint -esym(769,a_cli_operator_kind::cok_bitwise_and_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_bitwise_or)*/
/*lint -esym(769,a_cli_operator_kind::cok_bitwise_or_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_comma)*/
/*lint -esym(769,a_cli_operator_kind::cok_decrement)*/
/*lint -esym(769,a_cli_operator_kind::cok_division)*/
/*lint -esym(769,a_cli_operator_kind::cok_division_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_equality)*/
/*lint -esym(769,a_cli_operator_kind::cok_exclusive_or)*/
/*lint -esym(769,a_cli_operator_kind::cok_exclusive_or_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_false)*/
/*lint -esym(769,a_cli_operator_kind::cok_function_call)*/
/*lint -esym(769,a_cli_operator_kind::cok_greater_than)*/
/*lint -esym(769,a_cli_operator_kind::cok_greater_than_or_equal)*/
/*lint -esym(769,a_cli_operator_kind::cok_increment)*/
/*lint -esym(769,a_cli_operator_kind::cok_inequality)*/
/*lint -esym(769,a_cli_operator_kind::cok_left_shift)*/
/*lint -esym(769,a_cli_operator_kind::cok_left_shift_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_less_than)*/
/*lint -esym(769,a_cli_operator_kind::cok_less_than_or_equal)*/
/*lint -esym(769,a_cli_operator_kind::cok_logical_and)*/
/*lint -esym(769,a_cli_operator_kind::cok_logical_not)*/
/*lint -esym(769,a_cli_operator_kind::cok_logical_or)*/
/*lint -esym(769,a_cli_operator_kind::cok_member_selection)*/
/*lint -esym(769,a_cli_operator_kind::cok_modulus)*/
/*lint -esym(769,a_cli_operator_kind::cok_modulus_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_multiply)*/
/*lint -esym(769,a_cli_operator_kind::cok_multiplication_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_ones_complement)*/
/*lint -esym(769,a_cli_operator_kind::cok_pointer_dereference)*/
/*lint -esym(769,a_cli_operator_kind::cok_pointer_to_member_selection)*/
/*lint -esym(769,a_cli_operator_kind::cok_right_shift)*/
/*lint -esym(769,a_cli_operator_kind::cok_right_shift_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_signed_right_shift)*/
/*lint -esym(769,a_cli_operator_kind::cok_subscript)*/
/*lint -esym(769,a_cli_operator_kind::cok_subtraction)*/
/*lint -esym(769,a_cli_operator_kind::cok_subtraction_assignment)*/
/*lint -esym(769,a_cli_operator_kind::cok_true)*/
/*lint -esym(769,a_cli_operator_kind::cok_unary_negation)*/
/*lint -esym(769,a_cli_operator_kind::cok_unary_plus)*/
/*lint -esym(769,a_cli_operator_kind::cok_unsigned_right_shift)*/
/*lint -esym(769,a_cli_operator_kind::cok_unsigned_right_shift_assignment)*/
/*lint -esym(759,cli_managed_class_tag_keyword)*/
/*lint -esym(765,cli_managed_class_tag_keyword)*/
/*lint -esym(714,cli_managed_class_tag_keyword)*/
/*lint -esym(759,is_class_struct_type)*/
/*lint -esym(765,is_class_struct_type)*/
/*lint -esym(714,is_class_struct_type)*/
/*lint -esym(769,ec_cli_get_accessor_missing)*/
/*lint -esym(769,ec_cli_set_accessor_missing)*/
/*lint -esym(769,ec_conflicting_properties)*/
/*lint -esym(769,ec_property_set)*/
/*lint -esym(769,ec_property)*/
/*lint -esym(769,ec_cli_entity_not_loaded)*/
/*lint -esym(769,ec_for_each_missing_function)*/
/*lint -esym(769,ec_for_each_function_takes_args)*/
/*lint -esym(769,ec_for_each_function_const_violation)*/
/*lint -esym(769,ec_for_each_function_access_violation)*/
/*lint -esym(769,ec_for_each_static_function)*/
/*lint -esym(769,ec_for_each_no_matching_overload)*/
/*lint -esym(769,ec_for_each_invalid_return_type_for_move_next)*/
/*lint -esym(769,ec_for_each_incompatible_type)*/
/*lint -esym(769,ec_for_each_incompatible_iterator)*/
/*lint -esym(769,ec_for_each_missing_field)*/
/*lint -esym(769,ec_for_each_getenumerator_return_type_invalid)*/
/*lint -esym(769,ec_exp_in)*/
/*lint -esym(757,insert_temporary_initialization)*/
/*lint -esym(759,process_simple_assignment)*/
/*lint -esym(765,process_simple_assignment)*/
/*lint -esym(769,ec_no_suitable_synthesis_assignment_operator)*/
/*lint -esym(769,ec_not_a_generic_param)*/
/*lint -esym(769,ec_not_generic_param_of_curr_decl)*/
/*lint -esym(769,ec_invalid_constraint)*/
/*lint -esym(769,ec_invalid_event_use)*/
/*lint -esym(769,ec_event_without_raise_invoked)*/
/*lint -esym(769,ec_bad_event_compound_assignment)*/
/*lint -esym(769,ec_managed_nullptr_not_allowed)*/
/*lint -esym(769,ec_typeid_of_managed_type)*/
/*lint -esym(769,ec_cli_typeid_of_managed_pointer)*/
/*lint -esym(769,ec_name_before_typeid_not_type)*/
/*lint -esym(769,ec_reserved_dispose)*/
/*lint -esym(769,ec_reserved_finalize)*/
/*lint -esym(769,ec_invalid_idisposable_dispose)*/
/*lint -esym(769,ec_invalid_object_finalize)*/
/*lint -esym(769,ec_finalize_does_not_override_object_finalize)*/
/*lint -esym(769,ec_cast_interior_ptr_to_ptr)*/
/*lint -esym(769,ec_cppcli_explicit_conversion_only_in_ref_and_value_classes)*/
/*lint -esym(769,ec_cppcli_explicit_conversion_is_virtual)*/
/*lint -esym(769,ec_invalid_gcnew_type)*/
/*lint -esym(769,ec_gcnew_used_with_placement_syntax)*/
/*lint -esym(769,ec_new_used_on_unsuitable_value_type)*/
/*lint -esym(769,ec_new_used_on_managed_class_type)*/
/*lint -esym(769,ec_new_used_on_handle_or_tracking_reference_type)*/
/*lint -esym(769,ec_cli_array_must_have_new_or_array_init)*/
/*lint -esym(769,ec_gcnew_bad_type_used_with_array_init)*/
/*lint -esym(769,ec_gcnew_used_with_auto_syntax)*/
/*lint -esym(769,ec_too_many_array_bounds)*/
/*lint -esym(769,ec_too_few_array_bounds)*/
/*lint -esym(769,ec_too_few_generic_args)*/
/*lint -esym(769,ec_too_many_generic_args)*/
/*lint -esym(769,ec_generic_class)*/
/*lint -esym(769,ec_no_matching_arity)*/
/*lint -esym(759,convert_arg_operand_list_to_expr_list)*/
/*lint -esym(765,convert_arg_operand_list_to_expr_list)*/
/*lint -esym(769,ec_bad_function_for_delegate)*/
/*lint -esym(769,ec_ambiguous_function_for_delegate)*/
/*lint -esym(769,ec_mismatched_function_for_delegate)*/
/*lint -esym(769,ec_missing_delegate_object)*/
/*lint -esym(769,ec_nonmanaged_function_for_delegate)*/
/*lint -esym(769,ec_superfluous_delegate_object)*/
/*lint -esym(769,ec_incompatible_delegate_object)*/
/*lint -esym(769,ec_address_of_managed_member_function)*/
/*lint -esym(769,ec_bad_delegate_init_list)*/
/*lint -esym(769,ec_interface_not_implemented)*/
/*lint -esym(769,ec_gcnew_of_native_array)*/
/*lint -esym(769,ec_cli_interface_cannot_have_assignment)*/
/*lint -esym(769,ec_sealed_cli_interface)*/
/*lint -esym(769,ec_destructor_or_finalizer_with_named_override)*/
/*lint -esym(769,ec_override_name_is_destructor_or_finalizer)*/
/*lint -esym(769,ec_named_override_requires_managed_type)*/
/*lint -esym(769,ec_named_override_type_mismatch)*/
/*lint -esym(769,ec_static_constructor_with_named_override)*/
/*lint -esym(769,ec_static_conversion_function_must_have_one_parameter)*/
/*lint -esym(769,ec_branch_into_finally)*/
/*lint -esym(769,ec_return_from_finally)*/
/*lint -esym(769,ec_missing_finally)*/
/*lint -esym(769,ec_managed_object_not_thrown_by_handle)*/
/*lint -esym(769,ec_managed_object_not_caught_by_handle)*/
/*lint -esym(769,ec_break_cannot_be_in_finally_block)*/
/*lint -esym(769,ec_continue_cannot_be_in_finally_block)*/
/*lint -esym(769,ec_duplicate_constraint)*/
/*lint -esym(769,ec_multiple_class_constraints)*/
/*lint -esym(769,ec_multiple_constraint_clauses)*/
/*lint -esym(769,ec_initonly_static_data_member_not_initialized)*/
/*lint -esym(769,ec_cli_param_array_must_be_last_parameter)*/
/*lint -esym(769,ec_default_arg_used_in_param_array_function)*/
/*lint -esym(769,ec_ellipsis_after_param_array)*/
/*lint -esym(769,ec_parameter_array_on_operator_function)*/
/*lint -esym(769,ec_microsoft_inline_not_allowed_here)*/
/*lint -esym(769,ec_data_member_with_interface_type)*/
/*lint -esym(769,ec_variable_with_interface_type)*/
/*lint -esym(769,ec_parameter_with_interface_type)*/
/*lint -esym(769,ec_return_type_is_interface)*/
/*lint -esym(769,ec_array_of_generic_param)*/
/*lint -esym(769,ec_ptr_handle_or_ref_to_generic_param)*/
/*lint -esym(759,update_base_class_derivation)*/
/*lint -esym(765,update_base_class_derivation)*/
/*lint -esym(759,adjust_deletion_counts)*/
/*lint -esym(765,adjust_deletion_counts)*/
/*lint -esym(755,is_field_node)*/
/*lint -esym(769,ec_ref_class_initonly_field)*/
/*lint -esym(769,ec_ref_bound_to_initonly_field)*/
/*lint -esym(769,ec_address_of_initonly_field)*/
/*lint -esym(769,ec_modification_of_initonly_field)*/
/*lint -esym(769,ec_modification_of_static_initonly_field)*/
/*lint -esym(769,ec_member_function_call_on_initonly_field)*/
/*lint -esym(769,ec_expr_not_pointer_nor_handle)*/
/*lint -esym(769,ec_generic_selection_with_points_to)*/
/*lint -esym(769,ec_invalid_specific_ref_class_base)*/
/*lint -esym(769,ec_generic_class_must_be_managed)*/
/*lint -esym(769,ec_sealed_constraint)*/
/*lint -esym(769,ec_dynamic_cast_to_value_generic)*/
/*lint -esym(769,ec_override_with_constraint_mismatch)*/
/*lint -esym(769,ec_deprecated_access_specifier)*/
/*lint -esym(769,ec_static_accessor_in_nonstatic_property_or_event)*/
/*lint -esym(769,ec_invalid_type_constraint)*/
/*lint -esym(769,ec_both_ref_and_value_constraints)*/
/*lint -esym(769,ec_circular_constraints)*/
/*lint -esym(769,ec_invalid_generic_arg)*/
/*lint -esym(769,ec_bad_assembly_info_attribute)*/
/*lint -esym(769,ec_ref_class_not_satisfied)*/
/*lint -esym(769,ec_value_class_not_satisfied)*/
/*lint -esym(769,ec_gcnew_and_abstract)*/
/*lint -esym(769,ec_gcnew_and_no_ctor)*/
/*lint -esym(769,ec_gcnew_and_no_gcnew)*/
/*lint -esym(769,ec_type_not_satisfied)*/
/*lint -esym(769,ec_constraint_mismatch)*/
/*lint -esym(769,ec_standard_array_member_in_managed_class)*/
/*lint -esym(769,ec_handle_member_in_standard_class)*/
/*lint -esym(769,ec_tracking_reference_member_in_standard_class)*/
/*lint -esym(769,ec_reinterpret_cast_of_handle)*/
/*lint -esym(769,ec_generic_type_in_template_arg)*/
/*lint -esym(769,ec_expr_not_pointer_or_array_handle)*/
/*lint -esym(769,ec_unrecognized_ms_attr)*/
/*lint -esym(769,ec_standard_class_member_in_managed_class)*/
/*lint -esym(769,ec_ref_or_interface_class_member_in_standard_class)*/
/*lint -esym(769,ec_template_delegate)*/
/*lint -esym(769,ec_invalid_generic_specialization)*/
/*lint -esym(769,ec_generic_in_template)*/
/*lint -esym(769,ec_template_in_generic)*/
/*lint -esym(769,ec_static_literal_field)*/
/*lint -esym(769,ec_standard_class_nested_in_managed_class)*/
/*lint -esym(769,ec_clrcall_requires_cppcli)*/
/*lint -esym(769,ec_vararg_clrcall)*/
/*lint -esym(769,ec_bad_use_of_function_modifier)*/
/*lint -esym(769,ec_override_with_trivial_property_or_event)*/
/*lint -esym(552,scanning_macro_name)*/
/*lint -esym(769,ec_exp_id_in_for_each_decl)*/
/*lint -esym(769,ec_missing_notequal_on_for_each_type)*/
/*lint -esym(769,ec_missing_incr_on_for_each_type)*/
/*lint -esym(769,ec_missing_indirect_on_for_each_type)*/
/*lint -esym(769,ec_nonpublic_implicit_interface_match)*/
/*lint -esym(769,ec_managed_member_function_cannot_have_ellipsis_parameter)*/
/*lint -esym(769,ec_invalid_prev_decl_iterator)*/
/*lint -esym(769,ec_generic_parameter_requires_clrcall)*/
/*lint -esym(769,ec_generic_parameter_does_not_permit_varargs)*/
/*lint -esym(759,set_up_overload_set_traversal)*/
/*lint -esym(765,set_up_overload_set_traversal)*/
/*lint -esym(759,next_symbol_in_overload_set)*/
/*lint -esym(765,next_symbol_in_overload_set)*/
/*lint -esym(769,ec_virtual_required_for_base_override)*/
/*lint -esym(769,ec_virtual_required_for_interface_implementation)*/
/*lint -esym(769,ec_initonly_volatile_not_allowed)*/
/*lint -esym(769,ec_member_name_reserved_by_cli_operator)*/
/*lint -esym(769,ec_tracking_ref_to_constant)*/
/*lint -esym(769,ec_tracking_reference_to_system_string)*/
/*lint -esym(769,ec_use_of_generic_class_with_pending_constraint)*/
/*lint -esym(769,ec_invalid_entity_for_pending_constraint)*/
/*lint -esym(769,ec_template_in_managed_class)*/
/*lint -esym(769,ec_interface_cannot_have_member_generics)*/
/*lint -esym(769,ec_class_metadata_not_representable)*/
/*lint -esym(769,ec_exp_ellipsis)*/
/*lint -esym(769,ec_implements_requires_interface)*/
/*lint -esym(769,ec_implements_must_precede_virtual_functions)*/
/*lint -esym(769,ec_missing_implements_list)*/
/*lint -esym(769,ec_unused_dereference_of_ref_class)*/
/*lint -esym(769,ec_using_or_access_declaration_in_managed_class)*/
/*lint -esym(769,ec_cli_abstract_member_function_definition)*/
/*lint -esym(769,ec_nonstatic_addressof_operator_in_managed_class)*/
/*lint -esym(769,ec_interface_nonstatic_data_member)*/
/*lint -esym(769,ec_pure_specifier_on_sealed_member)*/
/*lint -esym(769,ec_final_managed_class)*/
/*lint -esym(769,ec_cast_to_cli_interface_class)*/
/*lint -esym(769,ec_new_of_cli_interface_class)*/
/*lint -esym(769,ec_enum_type_replacement)*/
/*lint -esym(769,ec_ptr_to_member_of_handle_type)*/
/*lint -esym(769,ec_arrow_star_operator_in_managed_class)*/
/*lint -esym(769,ec_bad_assembly_index)*/
/*lint -esym(769,ec_attribute_conflict)*/
/*lint -esym(769,ec_cl_unrestricted_unions_in_microsoft_mode)*/
/*lint -esym(769,ec_bad_cli_dynamic_cast_type)*/
/*lint -esym(769,ec_generic_class_cannot_be_custom_attribute)*/
/*lint -esym(769,ec_invalid_ms_attribute_target)*/
/*lint -esym(769,ec_ambiguous_ms_attribute)*/
/*lint -esym(769,ec_cli_attribute_inaccessible_field)*/
/*lint -esym(769,ec_cli_attribute_invalid_field)*/
/*lint -esym(769,ec_cli_attribute_invalid_argument)*/
/*lint -esym(769,ec_cli_typeid_of_generic_param_in_attribute)*/
/*lint -esym(769,ec_invalid_use_of_standalone_custom_ms_attr)*/
/*lint -esym(769,ec_field_target_on_nontrivial_property_or_event)*/
/*lint -esym(769,ec_invalid_attribute_target_for_standalone_ms_attr)*/
/*lint -esym(769,ec_invalid_attribute_target_for_ms_attr)*/
/*lint -esym(769,ec_invalid_use_of_custom_ms_attr)*/
/*lint -esym(769,ec_cli_param_array_attribute_deprecated)*/
/*lint -esym(769,ec_namespace_default_cannot_be_extended)*/
/*lint -esym(769,ec_cppcx_box_invalid_type)*/
/*lint -esym(769,ec_tracking_reference_to_value_class)*/
/*lint -esym(769,ec_handle_to_value_class)*/
/*lint -esym(769,ec_tracking_reference_to_enum)*/
/*lint -esym(769,ec_handle_to_enum)*/
/*lint -esym(769,ec_cppcx_public_native_type)*/
/*lint -esym(769,ec_public_nested_type_in_cppcx_type)*/
/*lint -esym(769,ec_cppcx_generic_type_not_allowed)*/
/*lint -esym(769,ec_cppcx_generic_constraints_not_allowed)*/
/*lint -esym(769,ec_nonpublic_data_member_in_public_cppcx_value_type)*/
/*lint -esym(769,ec_public_nondata_member_in_public_cppcx_value_type)*/
/*lint -esym(769,ec_cppcx_public_value_class_constructor)*/
/*lint -esym(769,ec_bad_cppcx_event_add_return)*/
/*lint -esym(769,ec_bad_cppcx_event_remove_return)*/
/*lint -esym(769,ec_bad_cppcx_event_remove_parameter)*/
/*lint -esym(769,ec_cppcx_handle_or_ref_to_generic_param)*/
/*lint -esym(769,ec_public_data_member_in_public_non_value_type)*/
/*lint -esym(769,ec_cl_cppcx_only_in_microsoft_cplusplus)*/
/*lint -esym(769,ec_cl_cppcx_and_cppcli)*/
/*lint -esym(769,ec_cppcx_not_enabled)*/
/*lint -esym(769,ec_cl_microsoft_version_insufficient_for_cppcx)*/
/*lint -esym(769,ec_literal_fields_disallowed_in_cppcx_mode)*/
/*lint -esym(769,ec_normal_ref_bound_to_cppcx_lvalue)*/
/*lint -esym(769,ec_cppcx_enum_base_has_no_platform_counterpart)*/
/*lint -esym(769,ec_event_in_cppcx_value_type)*/
/*lint -esym(769,ec_bad_cppcx_dynamic_cast_type)*/
/*lint -esym(769,ec_cppcx_array_only_one_dimension_allowed)*/
/*lint -esym(769,ec_cppcx_tracking_reference_on_standard_class_type)*/
/*lint -esym(769,ec_cppcx_value_type_deriving_from_interface)*/
/*lint -esym(769,ec_cppcx_value_type_contains_virtual_function)*/
/*lint -esym(769,ec_partial_class_incorrect_type_or_location)*/
/*lint -esym(769,ec_cppcx_invalid_array_property_set_value_parameter)*/
/*lint -esym(769,ec_cppcx_public_global_type)*/
/*lint -esym(769,ec_cppcx_public_indexed_property)*/
/*lint -esym(769,ec_cppcx_public_nested_delegate)*/
/*lint -esym(769,ec_cppcx_bad_delegate_init_list)*/
/*lint -esym(769,ec_cppcx_invalid_delegate_object)*/
/*lint -esym(769,ec_cppcx_non_const_array_parameter)*/
/*lint -esym(769,ec_invalid_base_for_ms_attributes)*/
/*lint -esym(769,ec_enum_in_managed_class_missing_definition)*/
/*lint -esym(759,free_attachments_to_operand)*/
/*lint -esym(765,free_attachments_to_operand)*/
/*lint -esym(769,ec_function_modifier_requires_virtual_function)*/
/*lint -esym(769,ec_constexpr_ignored_on_microsoft_nonstatic_member)*/
/*lint -esym(769,ec_constant_must_be_positive)*/
/*lint -esym(769,ec_type_must_be_integral)*/
/*lint -esym(552,internal_templates_enabled)*/
/*lint -esym(552,scanning_generated_code)*/
/*lint -esym(769,ec_too_large_to_inline)*/
/*lint -esym(759,is_transparent_union_type)*/
/*lint -esym(765,is_transparent_union_type)*/
/*lint -esym(714,is_effective_diagnostic)*/
/*lint -esym(759,is_effective_diagnostic)*/
/*lint -esym(765,is_effective_diagnostic)*/
/*lint -esym(769,ec_unsequenced_use_of_variable)*/
/*lint -esym(757,fp_to_hex_constant_string)*/
/*lint -esym(759,add_to_def_undef_list)*/
/*lint -esym(765,add_to_def_undef_list)*/
/*lint -esym(714,find_literal_operator)*/
/*lint -esym(759,find_literal_operator)*/
/*lint -esym(765,find_literal_operator)*/
/*lint -esym(714,ud_lit_op_sym_for_curr_token)*/
/*lint -esym(759,ud_lit_op_sym_for_curr_token)*/
/*lint -esym(765,ud_lit_op_sym_for_curr_token)*/
/*lint -esym(552,ud_lit_op_sym_for_curr_token)*/
/*lint -esym(552,encoding_prefix_for_curr_token)*/
/*lint -esym(552,user_defined_literals_enabled)*/
/*lint -esym(552,macro_preempts_udl_suffix)*/
/*lint -esym(552,raw_string_literals_enabled)*/
/*line -esym(552,digit_separators_enabled)*/
/*lint -esym(755,ud_suffix_from_literal_operator_id)*/
/*lint -esym(755,var_has_static_storage_duration)*/
/*lint -esym(769,ec_unrecognized_target_attribute)*/
/*lint -esym(769,ec_gnu_mv_default_missing)*/
/*lint -esym(769,ec_gnu_mv_only_one_arch)*/
/*lint -esym(769,ec_missing_target_attribute)*/
/*lint -esym(769,ec_no_matching_target_attribute)*/
/*lint -esym(769,ec_resolver_routine_required)*/
/*lint -esym(769,ec_target_on_special_function)*/
/*lint -esym(769,ec_resolver_routine_required)*/
/*lint -esym(769,ec_invalid_target_attribute)*/
/*lint -esym(769,a_pragma_kind::pk_ident)*/
/*lint -esym(755,il_entry_prefix_of_no_check)*/
/*lint -esym(769,ec_attribute_not_supported_in_x86_64)*/
/*lint -esym(755,TARG_ALIGNOF_INT128_linux_i686)*/
/*lint -esym(755,TARG_ALIGNOF_INT128_linux_x86_64)*/
/*lint -esym(755,TARG_ALIGNOF_INT128_win64)*/
/*lint -esym(755,TARG_ALIGNOF_INT128_win32)*/
/*lint -esym(755,TARG_INT128_FIELD_ALIGNMENT_linux_i686)*/
/*lint -esym(755,TARG_INT128_FIELD_ALIGNMENT_linux_x86_64)*/
/*lint -esym(755,TARG_INT128_FIELD_ALIGNMENT_win64)*/
/*lint -esym(755,TARG_INT128_FIELD_ALIGNMENT_win32)*/
/*lint -esym(755,TARG_SIZEOF_INT128_linux_i686)*/
/*lint -esym(755,TARG_SIZEOF_INT128_linux_x86_64)*/
/*lint -esym(755,TARG_SIZEOF_INT128_win64)*/
/*lint -esym(755,TARG_SIZEOF_INT128_win32)*/
/*lint -esym(759,temp_for_local_constant)*/
/*lint -esym(765,temp_for_local_constant)*/
/*lint -esym(714,temp_for_local_constant)*/
/*lint -esym(755,EDG_CONCAT)*/
/*lint -esym(769,ec_ms_metadata_init_failed)*/
/*lint -esym(769,a_named_register::anr_fpsr)*/
/*lint -esym(769,a_named_register::anr_dirflag)*/
/*lint -esym(769,a_named_register::anr_16)*/
/*lint -esym(769,a_named_register::anr_17)*/
/*lint -esym(769,a_named_register::anr_18)*/
/*lint -esym(769,a_named_register::anr_19)*/
/*lint -esym(769,a_named_register::anr_20)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugepd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugeps)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugesd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugess)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugtpd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugtps)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugtsd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comugtss)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comulepd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comuleps)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comulesd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comuless)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comultpd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comultps)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comultsd)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_comultss)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_protb_imm)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_protd_imm)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_protq_imm)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_protw_imm)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_rolsi)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_roldi)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_rorsi)*/
/*lint -esym(769,a_builtin_function_kind_tag::bfk_ia32_rordi)*/
/*lint -esym(769,ec_constexpr_string_not_null_terminated)*/
/*lint -esym(769,ec_attempt_to_read_past_end_of_object)*/
/*lint -esym(769,ec_must_be_atomic_qualified_type)*/
/*lint -esym(755,gnu_routine_supp)*/
/*lint -esym(714,write_float_n)*/
/*lint -esym(759,write_float_n)*/
/*lint -esym(765,write_float_n)*/
/*lint -esym(714,write_double_n)*/
/*lint -esym(759,write_double_n)*/
/*lint -esym(765,write_double_n)*/
/*lint -esym(714,write_long_double_n)*/
/*lint -esym(759,write_long_double_n)*/
/*lint -esym(765,write_long_double_n)*/
/*lint -esym(714,db_dump_float)*/
/*lint -esym(714,db_dump_double)*/
/*lint -esym(714,db_dump_long_double)*/
/*lint -esym(755,MAKE_FP_MIN_SUBNORMAL)*/
/*lint -esym(755,MAKE_FP_MIN)*/
/*lint -esym(757,write_long_double)*/
/*lint -esym(757,write_long_double_n)*/
/*lint -esym(757,read_long_double)*/
/*lint -esym(757,db_binary_long_double)*/
/*lint -esym(714,load_matching_builtin_function_by_name)*/
/*lint -esym(759,load_matching_builtin_function_by_name)*/
/*lint -esym(765,load_matching_builtin_function_by_name)*/
/*lint -esym(714,push_new_top_level_declaration)*/
/*lint -esym(759,push_new_top_level_declaration)*/
/*lint -esym(765,push_new_top_level_declaration)*/
/*lint -esym(759,put_variable_into_comdat_group)*/
/*lint -esym(765,put_variable_into_comdat_group)*/
/*lint -esym(759,is_sized_delete)*/
/*lint -esym(765,is_sized_delete)*/
/*lint -esym(769,a_builtin_user_function_kind::bufk_first)*/
/*lint -esym(769,a_builtin_user_function_kind::bufk_last)*/
/*lint -esym(552,targ_ssize_t_int_kind)*/
/*lint -esym(769,ec_always_inline_suppressed)*/
/*lint -esym(755,is_effective_thread_local)*/
/*lint -esym(755,TARG_MINIMUM_PACK_ALIGNMENT_linux_x86_64)*/
/*lint -esym(755,TARG_MAXIMUM_PACK_ALIGNMENT_linux_x86_64)*/
/*lint -esym(755,TARG_MINIMUM_PACK_ALIGNMENT_linux_i686)*/
/*lint -esym(755,TARG_MAXIMUM_PACK_ALIGNMENT_linux_i686)*/
/*lint -esym(755,TARG_MINIMUM_PACK_ALIGNMENT_win64)*/
/*lint -esym(755,TARG_MAXIMUM_PACK_ALIGNMENT_win64)*/
/*lint -esym(755,TARG_MINIMUM_PACK_ALIGNMENT_win32)*/
/*lint -esym(755,TARG_MAXIMUM_PACK_ALIGNMENT_win32)*/
/*lint -esym(759,rvalue_pointer_for_class_expression)*/
/*lint -esym(765,rvalue_pointer_for_class_expression)*/
/*lint -esym(552,vcmeta_directory_name)*/
/*lint -esym(552,put_variable_into_comdat_group)*/
/*lint -esym(757,put_variable_into_comdat_group)*/
/*lint -esym(757,expr1_could_affect_expr2)*/
/*lint -esym(769,ec_ext_vector_type_invalid_size)*/
/*lint -esym(769,ec_ext_vector_type_not_in_typedef)*/
/*lint -esym(769,ec_ext_vector_type_requires_integral_floating_type)*/
/*lint -esym(552,gnu_target_version_number)*/
/*lint -esym(750,is_finite)*/
/*lint -esym(750,is_NaN)*/
/*lint -esym(750,comment_numeric_valued_macro)*/
/*lint -esym(755,DO_LAST)*/
/*lint -esym(755,DI_LAST)*/
/*lint -esym(755,DI_NO_INPUT_FLAGS)*/
/*lint -esym(755,DSO_LAST)*/
/*lint -esym(755,DSI_LAST)*/
/*lint -esym(755,HOST_FP_TYPE_SELECTED)*/
/*lint -esym(755,TCF_LAST)*/
/*lint -esym(755,ITF_LAST)*/
/*lint -esym(755,SPECIFIC_TARGET_DIALECT_SET)*/
/*lint -esym(755,SUPPRESS_DEFINITION_OF_STDINT_TYPES)*/
/*lint -esym(755,TARG_DBL_MAX)*/
/*lint -esym(755,TARG_FLT_MAX)*/
/*lint -esym(755,TARG_LDBL_MAX)*/
/*lint -esym(758,a_builtin_function_condition_index)*/
/*lint -esym(758,a_builtin_function_kind_tag)*/
/*lint -esym(758,a_builtin_function_type_index)*/
/*lint -esym(769,a_ctor_or_dtor_kind::cdk_last)*/
/*lint -esym(769,a_dynamic_init_kind::dik_call_returning_class_via_cctor)*/
/*lint -esym(769,an_expr_node_kind::enk_last)*/
/*lint -esym(769,an_element_position_kind::epk_last)*/
/*lint -esym(769,a_gcc_pragma_kind::gcc_pk_last)*/
/*lint -esym(769,a_pragma_binding_kind::pbk_last)*/
/*lint -esym(769,a_pointer_modifier::pmt_last)*/
/*lint -esym(769,a_stdc_pragma_kind::stdc_pk_last)*/
/*lint -esym(769,a_type_qualifier::tqt_msb_named_address_space)*/
/*lint -esym(769,an_expression_kind::enk_last)*/
/*lint -esym(769,a_statement_kind::stmk_last)*/
/*lint -esym(769,a_type_class_kind::tck_char)*/
/*lint -esym(769,a_type_class_kind::tck_method)*/
/*lint -esym(769,a_type_class_kind::tck_string)*/
/*lint -esym(755,__STDC_LIMIT_MACROS)*/
/*lint -esym(769,a_constexpr_intrinsic::cit_error)*/
/*lint -esym(755,tptk_is)*/
/*lint -esym(714,db_entity_list)*/

#endif /* ifndef LINT_H */

/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-2025 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
