/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-1994 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
/*

symbol_ref.c - Routines to manage references to symbols.

*/

/* Header files common to all files. */
#include "fe_common.h"

#ifdef PCH_PRAGMA_GUARD
/* Mark the end of the sequence of headers subject to precompiled header
   processing. */
#pragma hdrstop
#endif /* ifdef PCH_PRAGMA_GUARD */

/* Additional header files. */
#include "symbol_ref.h"
#if MICROSOFT_EXTENSIONS_ALLOWED
#include "statements.h"
#endif /* MICROSOFT_EXTENSIONS_ALLOWED */


static an_il_to_str_output_control_block
		octl;
			/* Output control block used to interface to the
			   il_to_str routines. */

static a_boolean
		output_control_block_has_been_set_up = FALSE;
			/* Flag that indicates whether initialization has
			   already been done on the output control block. */

static void write_string_to_xref_file(char *str)
/*
Write str to the xref file.  The address of this routine is passed to
the il_to_str routines for generating formatted names.
*/
{
  (void)fputs(str, f_xref_info);
}  /* write_string_to_xref_file */


static void write_xref_entry(a_symbol_reference_kind srk_flags,
                             a_symbol_ptr            sym_ptr,
                             a_source_position       *source_position)
/*
Write information to f_xref_info describing a reference of kind "kind"
to symbol "sym_ptr" at source position "source_position".  This routine
should only be called if cross-reference information is being generated
(i.e., f_xref_info != NULL).
*/
{
  char              code;
  char              *file_name, *full_name;
  a_line_number     line_number;
  a_boolean         at_end_of_source;

  if (!output_control_block_has_been_set_up) {
    /* Set octl so that it can be passed into the il_to_str routines to tell
       them how to write a string to the xref file. */
    clear_il_to_str_output_control_block(&octl);
    octl.output_str = write_string_to_xref_file;
    output_control_block_has_been_set_up = TRUE;
  }  /* if */
  if (sym_ptr->kind == (a_symbol_kind)sk_extern_variable ||
             sym_ptr->kind == (a_symbol_kind)sk_extern_routine) {
    /* Ignore extern variable and routine symbols.  They are really just
       shadow symbols for the real ones. */
  } else if (is_unnamed_tag_symbol(sym_ptr)) {
    /* Ignore symbols for unnamed classes and enums. */
  } else if (source_position->seq == 0) {
    /* This symbol is not associated with any particular source position. */
  } else {
    /* The record written to the file is a text line that looks like

       symbol-id name X file-name line-number column-number

       The separator character between the fields is a horizontal tab.
       where X is "d" for declaration,
                  "D" for definition,
                  "M" for modification,
                  "A" for address taken,
                  "U" for use,
                  "C" for changed (i.e., used and modified in one
                      operation, such as an increment operation),
                  "R" for generic reference, or
                  "E" for error.
       The symbol-id is a unique number for the symbol, generated by 
       casting the symbol pointer to unsigned long.
    */
    if (srk_flags & SRK_DECLARATION) {
      if (srk_flags & SRK_DEFINITION) {
        code = 'D';
      } else {
        code = 'd';
      }  /* if */
    } else if (srk_flags & SRK_REFERENCE) {
      if (srk_flags & SRK_USE) {
        if (srk_flags & SRK_MODIFICATION) {
          code = 'C';
        } else {
          code = 'U';
        }  /* if */
      } else if (srk_flags & SRK_MODIFICATION) {
        code = 'M';
      } else if (srk_flags & SRK_ADDRESS_TAKEN) {
        code = 'A';
      } else if (srk_flags & SRK_ERROR) {
        code = 'E';
      } else {
        code = 'R';
      }  /* if */
#if CHECKING
    } else {
      internal_error("write_xref_entry: bad reference kind");
#endif /* CHECKING */
    }  /* if */
    /* Convert the source position to file name/line number. */
    conv_seq_to_file_and_line(source_position->seq, &file_name, &full_name,
                              &line_number, &at_end_of_source);
    fprintf(f_xref_info, "%lu\t", (unsigned long)sym_ptr);
    /* Write the symbol name, complete with class qualifier, etc., to the
       xref file. */
    form_symbol_name(sym_ptr, &octl);
    fprintf(f_xref_info, "\t%c\t%s\t%lu\t%d\n",
                         code,
                         file_name,
                         line_number,
                         source_position->column);
  }  /* if */
}  /* write_xref_entry */


void mark_variable_value_set(a_symbol_ptr  sym)
/*
Set the "value_has_been_set" flag of the variable symbol pointed to by sym.
*/
{
  check_assertion(sym->kind == (a_symbol_kind)sk_variable);
  if (sym->variant.variable.value_has_been_set) {
    /* Variable has already been set. */
    a_variable_ptr  vp = sym->variant.variable.ptr;
    if (vp->is_parameter || vp->is_handler_param) {
      /* Since parameters are by definition initialized (by the actual
         argument), any subsequent modification is a change to the initial
         value.  Knowing this can be useful for inlining. */
      vp->param_value_has_been_changed = TRUE;
    }  /* if */
  } else {
    sym->variant.variable.value_has_been_set = TRUE;
  }  /* if */
}  /* mark_variable_value_set */

#if RECORD_HIDDEN_NAMES_IN_IL

static a_boolean symbols_are_equivalent(a_symbol_ptr  sym1,
                                        a_symbol_ptr  sym2)
/*
Return TRUE if sym1 and sym2 point to the same IL entries.
*/
{
  an_il_entry_kind  kind;
  a_boolean         equiv = (sym1 == sym2);

  if (!equiv) {
    sym1 = fundamental_symbol_of(sym1);
    sym2 = fundamental_symbol_of(sym2);
    equiv = sym1 == sym2;
    if (!equiv) {
      if (sym1->kind == sym2->kind) {
        char *entry1 = il_entry_for_symbol_null_okay(sym1, &kind);
        char *entry2 = il_entry_for_symbol_null_okay(sym2, &kind);
        if (entry1 == entry2 && entry1 != NULL) equiv = TRUE;
      }  /* if */
    }  /* if */
  }  /* if */
  return equiv;
}  /* symbols_are_equivalent */


static a_hidden_name_ptr make_new_hidden_name(a_scope_ptr  sp)
/*
Allocate a new hidden name entry and link it in the list for the given scope.
*/
{
  a_hidden_name_ptr       hnp;
  a_scope_depth           scope_depth;
  a_memory_region_number  region_to_switch_back_to;
   /* Get the scope depth from which to determine the appropriate
     memory region in which to allocate the hidden-name entry. */
  if (in_file_scope(sp)) {
    scope_depth = DEPTH_OF_FILE_SCOPE;
  } else {
    scope_depth = sp->depth_in_scope_stack;
    check_assertion(scope_depth != NO_SCOPE_DEPTH);
  }  /* if */
  switch_to_scope_region(scope_depth, &region_to_switch_back_to);
  hnp = alloc_hidden_name();
  switch_back_to_original_region(region_to_switch_back_to);
  /* Add it to the start of the hidden_names list for the current
     scope. */
  hnp->next = sp->hidden_names;
  sp->hidden_names = hnp;
  return hnp;
}  /* make_new_hidden_name */


static void record_defeatable_name_hiding(
                              a_symbol_ptr  hidden_sym,
                              a_boolean     tag_hidden_by_nontag,
                              a_boolean     hidden_class_or_namespace_member,
                              a_scope_ptr   sp,
                              a_symbol_ptr  hidden_by)
/*
hidden_sym is a symbol for an entity that is hidden by another declaration
of the same name -- but the hiding can be "defeated" by using an
elaborated type specifier or global qualification (preceding "::") when
referring to the hidden name.  Create the hidden-name entity to represent
this case and add it to the list for the current scope.  If hidden_by is
non-NULL, it points to the symbol that does the hiding; when hidden_sym
and hidden_by refer to the same IL entry, no hidden-name entry is produced.
*/
{
  a_hidden_name_ptr        hnp;
  char                     *entity;
  an_il_entry_kind         kind;
  a_symbol_ptr             sym;
  a_template_instance_ptr  tip;

  check_assertion(sp != NULL);
  if (hidden_by != NULL && symbols_are_equivalent(hidden_sym, hidden_by)) {
    /* A symbol does not hide itself. */
  } else {
    switch (hidden_sym->kind) {
      case sk_label:
      case sk_keyword:
      case sk_macro:
      case sk_undefined:
      case sk_extern_variable:
      case sk_extern_routine:
        /* Not in the same name space. */
        break;
      case sk_overloaded_function:
        /* Enter members of an overload set separately. */
        for (sym = hidden_sym->variant.overloaded_function.symbols;
             sym != NULL;
             sym = sym->next) {
          record_defeatable_name_hiding(sym, tag_hidden_by_nontag,
                                        hidden_class_or_namespace_member, sp,
                                        hidden_by);
        }  /* for */
        break;
      case sk_projection:
        if (!hidden_sym->synthesized_namespace_projection) {
          /* Ignore most projection symbols. */
          break;
        }  /* if */
        /* FALLTHROUGH */
      case sk_namespace_projection:
        /* Enter the fundamental symbol of a namespace projection. */
        sym = fundamental_symbol_of(hidden_sym);
        /* If the fundamental symbol belongs to the same namespace as the
           symbol it's hidden by (something that can happen with synthesized
           namespace projections), then the hiding cannot be defeated by a
           qualifier.  Check for that case. */
        if (hidden_class_or_namespace_member &&
            depth_innermost_function_scope == NO_SCOPE_DEPTH &&
            hidden_by != NULL && !hidden_by->is_class_member &&
            !sym->is_class_member &&
            sym->parent.namespace_ptr == hidden_by->parent.namespace_ptr) {
          /* Set hidden_class_or_namespace_member to FALSE. */
          hidden_class_or_namespace_member = FALSE;
          /* If they're both FALSE don't create a hidden name table entry. */
          if (!tag_hidden_by_nontag) break;
        }  /* if */
        record_defeatable_name_hiding(sym, tag_hidden_by_nontag,
                                      hidden_class_or_namespace_member,
                                      sp, hidden_by);
        break;
      case sk_class_template:
        /* Enter each instance of a class template. */
        for (sym = hidden_sym->variant.template_info->
                                  variant.class_template.instantiations;
             sym != NULL;
             sym = next_instance_sym(sym)) {
          /* Don't enter prototype instantiations if they are not recorded in
             the IL. */
          if (!is_nonreal_instance_class_symbol(sym) ||
              prototype_instantiations_in_il) {
            record_defeatable_name_hiding(sym, tag_hidden_by_nontag,
                                          hidden_class_or_namespace_member, sp,
                                          hidden_by);
          }  /* if */
        }  /* for */
        break;
      case sk_function_template:
        /* Enter each instance of a function template. */
        for (tip = hidden_sym->variant.template_info->
                                  variant.function.instantiations;
             tip != NULL;
             tip = tip->next) {
          if (tip->is_guiding_decl) {
            /* Ignore guiding declarations -- they will have been picked up
               elsewhere. */
          } else {
            record_defeatable_name_hiding(tip->instance_sym,
                                          tag_hidden_by_nontag,
                                          hidden_class_or_namespace_member, sp,
                                          hidden_by);
          }  /* if */
        }  /* for */
        break;
      default:
        /* The normal case.  First find the entity associated with the
           symbol. */
        entity = il_entry_for_symbol(hidden_sym, &kind);
        /* If there is already a hidden name entry for this entity in this
           scope, reuse it. */
        for (hnp = sp->hidden_names; hnp != NULL; hnp = hnp->next) {
          if (hnp->entity.ptr == entity) break;
        }  /* for */
#if DEBUG
        if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
          if (hnp == NULL ||
              ((tag_hidden_by_nontag &&
                !hnp->elaborated_type_specifier_needed) ||
               (hidden_class_or_namespace_member &&
                !hnp->qualification_needed))) {
            a_source_correspondence  *scp =
                                   source_corresp_for_il_entry(entity, kind);
            fputs("    in ", f_debug);
            db_scope(sp);
            fputs(": use", f_debug);
            if (hidden_class_or_namespace_member) {
              fputs(" qualifier", f_debug);
              if (tag_hidden_by_nontag) fputs(" and", f_debug);
            }  /* if */
            if (tag_hidden_by_nontag) fputs(" class-key", f_debug);
            fprintf(f_debug, " for %s\"",
                    hidden_sym->decl_scope == file_scope_number ?
                                                     "global " : "");
            if (kind == (an_il_entry_kind)iek_type) {
              db_abbreviated_type((a_type_ptr)entity);
            } else {
              if (scp != NULL) {
                db_name_full(scp, kind);
              } else {
                fprintf(f_debug, "\?\?\?");
              }  /* if */
            }  /* if */
            fprintf(f_debug, "\"%s", hnp == NULL ? "" : " [modif]");
            fprintf(f_debug, "\n");
          }  /* if */
        }  /* if */
#endif /* DEBUG */
        if (hnp == NULL) {
          /* No existing entry.  Allocate a new one. */
          hnp = make_new_hidden_name(sp);
          hnp->entity.ptr = entity;
          hnp->entity.kind = (a_byte_il_entry_kind)kind;
        }  /* if */
        /* Set the appropriate flag. */
        if (tag_hidden_by_nontag) {
          check_assertion(kind == (an_il_entry_kind)iek_type);
          hnp->elaborated_type_specifier_needed = TRUE;
        }  /* if */
        if (hidden_class_or_namespace_member) {
          a_symbol_ptr  fund_hiding_sym = (hidden_by == NULL) ?
                                             NULL :
                                             fundamental_symbol_of(hidden_by),
                        fund_hidden_sym = fundamental_symbol_of(hidden_sym);
          if (microsoft_mode &&
              fund_hiding_sym != NULL &&
              fund_hiding_sym->kind == (a_symbol_kind)sk_type &&
              fund_hiding_sym->variant.type.is_injected_class_name) {
            /* In Microsoft compilers an injected class name is only visible
               through qualified lookup.  Furthermore, Microsoft does not
               accept (redundant) qualification with a class whose closing
               brace has not yet been seen.  Setting the following flag
               notifies consumers of this special "partial hiding" case. */
            hnp->partially_hidden_by_microsoft_injected_class_name = TRUE;
          }  /* if */
          check_assertion(in_file_scope(entity));
          if (fund_hiding_sym == NULL ||
              !(is_type_symbol(fund_hidden_sym) &&
                fund_hiding_sym->kind == (a_symbol_kind)sk_type &&
                fund_hiding_sym->variant.type.is_injected_class_name) ||
              !f_identical_types(type_symbol_type(fund_hidden_sym),
                                 type_symbol_type(fund_hiding_sym),
                                 ITF_NO_FLAGS)) {
            /* It is possible that an injected class name hides another type
               symbol that refers to the same IL entity.  In that case, no
               qualification is needed. */
            hnp->qualification_needed = TRUE;
          }  /* if */
        }  /* if */
        break;
    }  /* switch */
  }  /* if */
}  /* record_defeatable_name_hiding */


static void check_name_unhiding(a_symbol_ptr sym_ptr,
                                a_scope_ptr sp)
/*
Injected class names and block extern declarations enable unqualified access
to entities that might have been previously hidden.  If sym_ptr is a symbol
for such an entity, we create a new hidden name entry for scope sp with all
flags cleared.  Note that this happens even if no hiding had occurred.
*/
{
  a_hidden_name_ptr  hnp = NULL;
  an_il_entry_kind   entity_kind;

  if (is_injected_class_symbol(sym_ptr)) {
    if (microsoft_mode) {
      /* In Microsoft mode, injected class names are only accessible as
         qualified names. */
    } else {
      /* An injected class name is accessible without qualification (except in
         Microsoft mode).  Creating a hidden name entry will ensure that any
         qualification forced by prior entries is canceled.  Make sure that the
         injected class name is not hidden by another member. */
      a_symbol_locator  locator;
      clear_locator(&locator, &sym_ptr->decl_position);
      locator.symbol_header = sym_ptr->header;
      check_assertion(sp->kind == (a_scope_kind)sck_class_struct_union);
      (void)class_qualified_id_lookup(&locator, sp->variant.assoc_type,
                                      IDL_HIDDEN_NAME_LOOKUP);
      /* If the lookup produced the injected symbol, it is not hidden by
         another member. */
      if (locator.specific_symbol != NULL &&
          fundamental_symbol_of(locator.specific_symbol) == sym_ptr) {
        hnp = make_new_hidden_name(sp);
        hnp->entity.ptr = il_entry_for_symbol(sym_ptr, &entity_kind);
        hnp->entity.kind = (a_byte_il_entry_kind)entity_kind;
      }  /* if */
    }  /* if */
  } else if (sp->kind == (a_scope_kind)sck_function ||
             sp->kind == (a_scope_kind)sck_block) {
    /* A block extern declaration makes the associated entity accessible
       without qualification.  A new hidden name entry will override any
       previous entry that might have imposed qualification. */
    if (sym_ptr->kind == (a_symbol_kind)sk_variable) {
      a_variable_ptr  var = sym_ptr->variant.variable.ptr;
      if (var->storage_class == (a_storage_class)sc_extern ||
          var->storage_class == (a_storage_class)sc_unspecified) {
        hnp = make_new_hidden_name(sp);
        hnp->entity.ptr = il_entry_for_symbol(sym_ptr, &entity_kind);
        hnp->entity.kind = (a_byte_il_entry_kind)entity_kind;
      }  /* if */
    } else if (sym_ptr->kind == (a_symbol_kind)sk_routine) {
      a_routine_ptr  routine = sym_ptr->variant.routine.ptr;
      if (routine->storage_class == (a_storage_class)sc_extern ||
          routine->storage_class == (a_storage_class)sc_unspecified) {
        hnp = make_new_hidden_name(sp);
        hnp->entity.ptr = il_entry_for_symbol(sym_ptr, &entity_kind);
        hnp->entity.kind = (a_byte_il_entry_kind)entity_kind;
      }  /* if */
    } else if (sym_ptr->kind == (a_symbol_kind)sk_overloaded_function) {
      /* Each member of the overload set must be separately "unhidden". */
      a_symbol_ptr  overload_item =
                                 sym_ptr->variant.overloaded_function.symbols;
      for (; overload_item != NULL; overload_item = overload_item->next) {
        check_name_unhiding(overload_item, sp);
      }  /* for */
    }  /* if */
  }  /* if */
#if DEBUG
  if ((debug_level >= 4 || db_flag_is_set("dump_hidden")) && hnp != NULL) {
    a_source_correspondence  *scp =
               source_corresp_for_il_entry(hnp->entity.ptr, entity_kind);
    fputs("    in ", f_debug);
    db_scope(sp);
    fprintf(f_debug, ": \"");
    if (entity_kind == (an_il_entry_kind)iek_type) {
      db_abbreviated_type((a_type_ptr)hnp->entity.ptr);
    } else {
      if (scp != NULL) {
        db_name_full(scp, entity_kind);
      } else {
        fprintf(f_debug, "\?\?\?");
      }  /* if */
    }  /* if */
    fprintf(f_debug, "\" can be used as an unqualified name\n");
  }  /* if */
#endif /* DEBUG */
}  /* check_name_unhiding */


static void check_defeatable_base_inaccessibility(
                                              a_type_ptr        class_type,
                                              a_base_class_ptr  bcp)
/*
If a base class bcp is inaccessible (privately but not directly inherited),
the C++ generating back-end cannot access it using an unqualified name in the
class scope of class_type.  Therefore, we treat the base type as hidden in the
scope of the class class_type and mark it as needing qualified access.
This allows the following example to work:
   struct A { static int i; };
   struct B: private A {};
   struct C: B { void f(); };
   void C::f() { ::A::i = 42; }; <-- Needs to remain "::A::i": just "i" or
                                     "A::i" fails.
*/
{
  /* First check if we have access to public members of this base class.
     If so, there is no problem and no need for extra work. */
  if (!is_accessible_base_class(bcp)) {
    /* This base is inaccessible because of private inheritance. */
    a_symbol_ptr            hidden_sym;
    a_scope_ptr             scope;
    a_scope_depth           scope_depth;
    a_hidden_name_ptr       hnp;
    a_memory_region_number  region_to_switch_back_to;
    an_il_entry_kind        kind;

    scope =  class_type->variant.class_struct_union.extra_info->assoc_scope;
    if (in_file_scope(scope)) {
      scope_depth = DEPTH_OF_FILE_SCOPE;
    } else {
      scope_depth = scope->depth_in_scope_stack;
      check_assertion(scope_depth != NO_SCOPE_DEPTH);
    }  /* if */
    switch_to_scope_region(scope_depth, &region_to_switch_back_to);
    hnp = alloc_hidden_name();
    switch_back_to_original_region(region_to_switch_back_to);
    hidden_sym = (a_symbol_ptr)bcp->type->source_corresp.assoc_info;
    hnp->entity.ptr = il_entry_for_symbol(hidden_sym, &kind);
    hnp->entity.kind = (a_byte_il_entry_kind)kind;
    hnp->qualification_needed = TRUE;
    /* Add it to the start of the hidden_names list for the current scope. */
    hnp->next = scope->hidden_names;
    scope->hidden_names = hnp;
  }  /* if */
}  /* check_defeatable_base_inaccessibility */


static void check_hiding_by_inherited_names(a_type_ptr  class_type,
                                            a_scope_ptr sp,
                                            a_boolean   top_level)
/*
Perform hidden name checking on the members of each of the base classes of
class_type.  This routine is called recursively, in which case top_level
is FALSE.  When top_level is FALSE, i.e., if class_type is not the most
derived type (i.e., if its IL scope is not the indicated IL scope), do
hidden name checking on its own members, too.
*/
{
  a_base_class_ptr  bcp = base_classes_of(class_type);
  a_symbol_ptr      sym_ptr, old_sym_ptr;
  a_symbol_locator  locator;

#if DEBUG
  if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
    /* If this is the top-level call, identify class_type. */
    if (bcp != NULL && top_level) {
      fputs("Hidden name check for inherited names of ", f_debug);
      db_type_name(class_type);
      fputc('\n', f_debug);
    }  /* if */
  }  /* if */
#endif /* DEBUG */
  /* Loop through each of the base classes of class type and perform hidden
     name checking on the inherited members of direct (and, if top-level,
     virtual) base classes. */
  for (; bcp != NULL; bcp = bcp->next) {
    if (bcp->direct || (top_level && bcp->is_virtual)) {
      check_hiding_by_inherited_names(bcp->type, sp, /*top_level=*/FALSE);
    }  /* if */
    if (!bcp->direct && !bcp->type->source_corresp.is_local_to_function) {
      /* The base class may be inaccessible or ambiguous by inheritance, but
         it may be possible to refer to it through qualified access (if it is
         not a local class). */
      check_defeatable_base_inaccessibility(class_type, bcp);
    }  /* if */
  }  /* for */
  if (!top_level) {
    sym_ptr = symbol_supplement_for_class(class_type)->symbols;
    for (; sym_ptr != NULL; sym_ptr = sym_ptr->next_in_scope) {
      /* Skip constructors. */
      if (is_constructor_symbol(sym_ptr)) continue;
#if DEBUG
      if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
        if (sym_ptr->decl_position.seq) {
          fputs("  Hidden name check: ", f_debug);
          fprintf(f_debug, "<%s> ", symbol_kind_names[(int)sym_ptr->kind]);
          db_symbol_name(sym_ptr);
          fputc('\n', f_debug);
        }  /* if */
      }  /* if */
#endif /* DEBUG */
      /* Unhide the injected class names since they can now be accessed
         using an unqualified name even if that was not so in the base. */
      check_name_unhiding(sym_ptr, sp);
      /* Perform a lookup. */
      clear_locator(&locator, &sym_ptr->decl_position);
      locator.symbol_header = sym_ptr->header;
#if DEBUG
      if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
        fputs("    ...doing lookup (inherited names)\n", f_debug);
      }  /* if */
#endif /* DEBUG */
      (void)normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
      old_sym_ptr = locator.specific_symbol;
      /* If something was found, see if it is hidden by sym_ptr. */
      if (old_sym_ptr != NULL) {
        a_symbol_ptr  tag_sym = NULL;
        if (is_injected_class_symbol(sym_ptr) &&
            (is_tag_symbol(old_sym_ptr) ||
             is_class_template_symbol(old_sym_ptr))) {
          tag_sym =
               (a_symbol_ptr)(skip_typerefs(type_symbol_type(sym_ptr))->
                                                  source_corresp.assoc_info);
        }  /* if */
        if (tag_sym != NULL &&
            (symbols_are_equivalent(old_sym_ptr, tag_sym) ||
             (is_class_template_symbol(old_sym_ptr) &&
              is_template_class_symbol(tag_sym)))) {
          /* sym_ptr does not hide old_sym_ptr -- they represent the same
             declaration. */
        } else if (old_sym_ptr->decl_scope == file_scope_number ||
                   old_sym_ptr->is_class_member ||
                   old_sym_ptr->parent.namespace_ptr != NULL) {
          /* The name hiding can be defeated by using a qualifier. */
          record_defeatable_name_hiding(
                                  old_sym_ptr,
                                  /*tag_hidden_by_nontag=*/FALSE,
                                  /*hidden_class_or_namespace_member=*/TRUE,
                                  sp, sym_ptr);
        }  /* if */
      }  /* if */
    }  /* for */
  }  /* if */
}  /* check_hiding_by_inherited_names */


static void check_name_hiding_of_tag_by_nontag(a_symbol_ptr  sym_ptr,
                                               a_scope_ptr   sp)
/*
sym_ptr is a non-tag name declared in scope sp.  Determine whether there
are any tag declarations in an enclosing scope that are hidden by sym_ptr
and that can be rendered unhidden by being referred to with an elaborated
type specifier when put out by the C++-generating back end.
*/
{
  a_symbol_locator         locator;
  a_symbol_ptr             old_sym_ptr;
  a_boolean                tag_hidden_by_nontag;
  a_boolean                hidden_class_or_namespace_member;

  clear_locator(&locator, &sym_ptr->decl_position);
  locator.symbol_header = sym_ptr->header;
  /* Determine what declarations are hidden by the current declaration. */

  /* First check for hiding that can be resolved with an elaborated type
     specifier -- e.g., when the current declaration is a non-tag name that
     hides a tag name in the same or an enclosing scope and when the current
     declaration is a tag name that is hidden by a non-tag name in the
     current scope. */

  /* The current declaration is of something other than a tag name.
     If it hides a tag in the same scope or an enclosing scope, an
     elaborated type specifier can render the tag visible.  For example:
       class x;
       int x = 1;                   // class x is hidden at file scope
       class y;
       void f() {
         int y = 1;                 // class y is hidden in function f
       }
     An elaborated type specifier can be used to "defeat" the hiding. */
  /* Find the innermost tag declaration with the same name. */
#if DEBUG
  if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
    fputs("    ...doing tag lookup (tag-nontag)\n", f_debug);
  }  /* if */
#endif /* DEBUG */
  old_sym_ptr = normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP |
                                           IDL_MUST_BE_TAG);
  if (old_sym_ptr != NULL) {
    /* old_sym_ptr is a tag with the same name as sym_ptr and in the
       same or a containing scope. */
    a_type_ptr  sym_type;
    if (sym_ptr->kind == (a_symbol_kind)sk_type &&
        typeref_is_typedef(sym_ptr->variant.type.ptr) &&
        (sym_type = skip_typerefs(sym_ptr->variant.type.ptr),
         same_entities(sym_type,
                       old_sym_ptr->variant.class_struct_union.type))) {
      /* sym_ptr is a typedef that refers the type represented by
         old_sym_ptr -- something like "typedef struct S { ... } S;"
         There's no need to generate hidden-name info for this common
         construct. */
    } else if (old_sym_ptr->decl_scope != sym_ptr->decl_scope &&
               (old_sym_ptr->is_class_member ||
                old_sym_ptr->parent.namespace_ptr != NULL ||
                old_sym_ptr->decl_scope == file_scope_number)) {
      /* No need to defeat the name hiding with an elaborated type
         specifier -- the tag name will be qualified, either by its
         parent class or namespace or by a leading "::".  That's
         handled later. */
    } else {
      /* Either the two declarations are in the same scope or else
         old_sym_ptr cannot be qualified -- e.g., its containing scope is
         local to a function:
           void f() {
             struct S { ... };
             { int S; ... }     // S is hidden in the block scope
           }
      */
      tag_hidden_by_nontag = TRUE;
      hidden_class_or_namespace_member = FALSE;
      record_defeatable_name_hiding(old_sym_ptr, tag_hidden_by_nontag,
                                    hidden_class_or_namespace_member,
                                    sp, sym_ptr);
    }  /* if */
  }  /* if */
}  /* check_name_hiding_of_tag_by_nontag */


static void check_name_hiding_of_qualifiable_name(a_symbol_ptr  sym_ptr,
                                                  a_scope_ptr   sp)
/*
sym_ptr is a name declared in scope sp.  Determine whether there are any
declarations in an enclosing scope that are hidden by sym_ptr and that
can be rendered unhidden by being qualified when put out by the
C++-generating back end.
*/
{
  a_symbol_locator         locator;
  a_symbol_ptr             old_sym_ptr, tag_sym;
  a_boolean                tag_hidden_by_nontag;
  a_boolean                hidden_class_or_namespace_member;

  clear_locator(&locator, &sym_ptr->decl_position);
  locator.symbol_header = sym_ptr->header;
#if DEBUG
  if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
    fputs("    ...doing skip-curr-scope lookup (qualifiable)\n", f_debug);
  }  /* if */
#endif /* DEBUG */
  old_sym_ptr = normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP |
                                           IDL_SKIP_CURR_SCOPE);
  if (old_sym_ptr == NULL) {
    /* There is no symbol that may potentially be hidden. */
  } else if (old_sym_ptr->is_nonreal_member) {
    /* Ignore members of proxy and nonreal classes: they don't correspond to
       actual declarations and therefore cannot be hidden. */
  } else {
    tag_sym = NULL;
    if (is_injected_class_symbol(sym_ptr) &&
        (is_tag_symbol(old_sym_ptr) ||
         is_class_template_symbol(old_sym_ptr))) {
      tag_sym =
         (a_symbol_ptr)(skip_typerefs(type_symbol_type(sym_ptr))->
                                            source_corresp.assoc_info);
    }  /* if */
    if (tag_sym != NULL &&
        (symbols_are_equivalent(old_sym_ptr, tag_sym) ||
         (is_class_template_symbol(old_sym_ptr) &&
          is_template_class_symbol(tag_sym)))) {
      /* sym_ptr does not hide old_sym_ptr -- they represent the same
         declaration. */
    } else if (old_sym_ptr->decl_scope == sym_ptr->decl_scope &&
               !old_sym_ptr->synthesized_namespace_projection) {
      /* Despite the skip-curr-scope lookup, the two symbols were declared in
         the same scope; this can happen as a result of using-declarations.
         Qualification will not help.  Synthesized namespace projection
         symbols are excluded from this test because their decl_scope is not
         meaningful in this context. */
    } else if (old_sym_ptr->decl_scope == file_scope_number ||
               old_sym_ptr->is_class_member ||
               old_sym_ptr->parent.namespace_ptr != NULL ||
               old_sym_ptr->synthesized_namespace_projection) {
      /* A qualifiable name. */
      tag_hidden_by_nontag = FALSE;
      hidden_class_or_namespace_member = TRUE;
      record_defeatable_name_hiding(old_sym_ptr, tag_hidden_by_nontag,
                                    hidden_class_or_namespace_member,
                                    sp, sym_ptr);
    }  /* if */
    /* Do a similar check for tag names in containing scopes. */
    if (sym_ptr->header->any_tag_decl &&
        !is_tag_symbol(old_sym_ptr) &&
        !is_class_template_symbol(old_sym_ptr)) {
      clear_specific_symbol(locator);
#if DEBUG
      if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
        fputs("    ...doing skip-curr-scope tag lookup (qualifiable)\n",
              f_debug);
      }  /* if */
#endif /* DEBUG */
      old_sym_ptr = normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP |
                                               IDL_MUST_BE_TAG |
                                               IDL_SKIP_CURR_SCOPE);
      if (old_sym_ptr != NULL) {
        if ((old_sym_ptr == sym_ptr) ||
            (old_sym_ptr->decl_scope == sym_ptr->decl_scope)) {
          /* This can happen when the scope to which sym_ptr belongs is
             an unnamed namespace. */
        } else {
          tag_hidden_by_nontag = TRUE;
          if (old_sym_ptr->decl_scope == file_scope_number ||
              old_sym_ptr->is_class_member ||
              old_sym_ptr->parent.namespace_ptr != NULL) {
            hidden_class_or_namespace_member = TRUE;
            record_defeatable_name_hiding(
                                        old_sym_ptr,
                                        tag_hidden_by_nontag,
                                        hidden_class_or_namespace_member,
                                        sp, sym_ptr);
          }  /* if */
        }  /* if */
      }  /* if */
    }  /* if */
  }  /* if */
}  /* check_name_hiding_of_qualifiable_name */


static void resolve_using_directive_ambiguity(a_symbol_ptr  sym_ptr,
                                              a_scope_ptr   sp)
/*
Determine whether references to the declaration indicated by sym_ptr should
be displayed by the C++-generating back end with a qualifier in order to
resolve ambiguities caused by a using-directive.  For example:
  namespace N { void f(); }
  using namespace N;
  void f();
  void g() { ::f(); }    // don't put out unqualified "f" -- qualifier is
                         // needed to resolve the ambiguity.
*/
{
  a_symbol_locator         locator;
  a_symbol_ptr             old_sym_ptr;
  a_boolean                tag_hidden_by_nontag;
  a_boolean                hidden_class_or_namespace_member;
                                              
  /* Do a lookup and see if a synthesized namespace projection is
     found.  If it is, we can assume that sym_ptr is part of the mix
     (though it may not actually be returned unless a function overload
     set is produced), and if so qualifying sym_ptr will disambiguate
     the reference. */
  clear_locator(&locator, &sym_ptr->decl_position);
  locator.symbol_header = sym_ptr->header;
#if DEBUG
  if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
    fputs("    ...doing lookup (using-directive)\n", f_debug);
  }  /* if */
#endif /* DEBUG */
  (void)normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
  old_sym_ptr = locator.specific_symbol;
  if (old_sym_ptr != NULL &&
      old_sym_ptr->synthesized_namespace_projection) {
    if (old_sym_ptr->ambiguous ||
        old_sym_ptr->kind == (a_symbol_kind)sk_overloaded_function) {
      hidden_class_or_namespace_member = TRUE;
      tag_hidden_by_nontag = FALSE;
      record_defeatable_name_hiding(sym_ptr, tag_hidden_by_nontag,
                                    hidden_class_or_namespace_member,
                                    sp, (a_symbol_ptr)NULL);
    }  /* if */
  }  /* if */
}  /* resolve_using_directive_ambiguity */


static void check_for_defeatable_name_hiding(a_symbol_ptr  sym_ptr,
                                        a_scope_ptr   sp)
/*
Check whether any declarations are hidden by the declaration associated
with sym_ptr, and if appropriate enter hidden_name_table entries in the
indicated scope.
*/
{
#if DEBUG
  if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
    if (sym_ptr->decl_position.seq) {
      fputs("Hidden name check: ", f_debug);
      fprintf(f_debug, "<%s> ", symbol_kind_names[(int)sym_ptr->kind]);
      db_symbol_name(sym_ptr);
      fputc('\n', f_debug);
    }  /* if */
  }  /* if */
#endif /* DEBUG */
  if (!is_tag_symbol(sym_ptr) && !is_injected_class_symbol(sym_ptr)) {
    /* See if the current symbol hides a tag symbol. */
    if (sym_ptr->header->any_tag_decl) {
      check_name_hiding_of_tag_by_nontag(sym_ptr, sp);
    }  /* if */
  }  /* if */
  if (sym_ptr->header->any_decl_in_file_or_namespace_scope ||
      sym_ptr->header->inactive_symbols != NULL) {
    /* There are qualifiable symbols that share this name. */
    if (sp->kind != (a_scope_kind)sck_file &&
        (sp->kind != (a_scope_kind)sck_namespace ||
         sp->variant.assoc_namespace->source_corresp.name != NULL ||
         sp->variant.assoc_namespace->
                             source_corresp.parent.namespace_ptr != NULL)) {
      /* A declaration in the current scope may hide a declaration from the
         file scope or a namespace scope.  If so, the hidden name may be
         rendered visible by qualification.  Conversely, a few situations may
         "unhide" such a name. */
      check_name_unhiding(sym_ptr, sp);
      check_name_hiding_of_qualifiable_name(sym_ptr, sp);
    }  /* if */
  }  /* if */
  if (sp->kind == (a_scope_kind)sck_file ||
      sp->kind == (a_scope_kind)sck_namespace) {
    a_scope_stack_entry_ptr  ssep =
                                &scope_stack[depth_innermost_namespace_scope];
    check_assertion(ssep->il_scope == sp);
    if (ssep->using_directives_apply) {
      /* If a using-directive appeared in the current scope, it may render
         sym_ptr ambiguous unless sym_ptr is displayed with a qualifier. */
      resolve_using_directive_ambiguity(sym_ptr, sp);
    }  /* if */
  }  /* if */
}  /* check_for_defeatable_name_hiding */

                       
void check_name_hiding_for_scope(a_scope_ptr  sp)
/*
Check for symbols declared in the specified scope that hide names declared
in the same scope or an enclosing scope and, when appropriate, create hidden
name table entries to describe the hiding when it can be defeated in the
C++-generating back end by using a qualifier or elaborated type specifier.
In C++ mode this routine is called recursively for namespace scopes and
class scopes.  It is called directly from pop_scope for function and block
scopes and for the file scope.
*/
{
  a_scope_stack_entry_ptr     ssep;
  a_namespace_ptr             nsp;
  a_type_ptr                  tp;
  a_symbol_ptr                sym, sym_list;

  db_enter(3, "check_name_hiding_for_scope");
  if (sp != NULL) {
    /* Check certain nested scopes first. */
    if (!C_mode()) {
      /* If this is the file scope or a namespace scope, there may be nested
         namespaces.  Do checking for the nested scope before proceeding to
         the symbols that were declared in the current scope. */
      for (nsp = sp->namespaces; nsp != NULL; nsp = nsp->next) {
        if (!nsp->is_namespace_alias) {
          push_namespace_extension_scope(nsp);
          check_name_hiding_for_scope(nsp->variant.assoc_scope);
          pop_namespace_extension_scope();
        }  /* if */
      }  /* for */
      /* Similarly, do checking for class scopes defined within the current
         scope before proceeding to the symbols that were declared in the
         current scope. */
      for (tp = sp->types; tp != NULL; tp = tp->next) {
        if (is_immediate_class_type(tp)) {
          a_scope_ptr  scope_ptr = tp->variant.class_struct_union.
                                                extra_info->assoc_scope;
          if (scope_ptr != NULL) {
            push_class_reactivation_scope(tp, /*extend_namespace=*/FALSE);
            check_name_hiding_for_scope(scope_ptr);
            pop_class_reactivation_scope();
            check_hiding_by_inherited_names(tp, scope_ptr,
                                            /*top_level=*/TRUE);
          }  /* if */
        }  /* if */
      }  /* for */
    }  /* if */
    /* Find the list of symbols declared in the current scope. */
    switch (sp->kind) {
      case sck_file:
      case sck_function:
      case sck_block:
        ssep = &scope_stack[depth_scope_stack];
        sym_list = assoc_pointers_block_of(ssep)->symbols;
        break;
      case sck_namespace:
        nsp = sp->variant.assoc_namespace;
        sym_list = symbol_supplement_for_namespace(nsp)->
                                             pointers_block.symbols;
        break;
      case sck_class_struct_union:
        tp = sp->variant.assoc_type;
        sym_list = symbol_supplement_for_class(tp)->symbols;
        break;
      default:
#if CHECKING
        unexpected_condition();
#else /* !CHECKING */
        sym_list = NULL;
#endif /* CHECKING */
    }  /* if */
#if DEBUG
    if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
      if (sym_list != NULL) {
        fputs("Checking hidden names declared in ", f_debug);
        db_scope(sp);
        fputs("\n", f_debug);
      }  /* if */
    }  /* if */
#endif /* DEBUG */
    /* Traverse the symbols declared in the current scope. */
    for (sym = sym_list; sym != NULL; sym = sym->next_in_scope) {
      if (sym->kind == (a_symbol_kind)sk_extern_routine ||
          sym->kind == (a_symbol_kind)sk_extern_variable) {
        /* Ignore extern symbols. */
      } else if (sym->is_error) {
        /* Ignore error symbols. */
      } else if (sym->kind == (a_symbol_kind)sk_macro) {
        /* Ignore macros. */
      } else if (!sym->decl_position.seq) {
        /* Ignore compiler-generated symbols for predeclared entities. */
      } else if (is_unnamed_tag_symbol(sym)) {
        /* No name hiding by unnamed symbols. */
      } else if (sym->is_invisible) {
        /* A friend declaration doesn't affect lookup until it's actually
           declared in the scope to which it belongs -- so if it's invisible,
           it can't hide other declarations. */
      } else if (is_template_class_symbol(sym)) {
        /* The template itself belongs to the same scope -- one check for a
           given name is sufficient. */
      } else if (is_injected_class_symbol(sym)) {
        /* Ignore symbols representing injected class names. */
      } else if (sym->kind == (a_symbol_kind)sk_projection) {
        /* Ignore inherited names -- they are handled separately. */
      } else {
        /* Only the overload symbol should be on the scope list. */
        check_assertion(!sym->overload_set_member);
        /* Falling through to here means the symbol should be checked to see
           if this declaration hides another declaration. */
        check_for_defeatable_name_hiding(sym, sp);
      }  /* if */
    }  /* for */
  }  /* if */
  db_exit();
}  /* check_name_hiding_for_scope */
  
#endif /* RECORD_HIDDEN_NAMES_IN_IL */
#if GENERATE_SOURCE_SEQUENCE_LISTS

static void sym_update_source_sequence_list(
                                  a_symbol_ptr                 sym,
                                  a_source_position            *pos,
                                  a_boolean                    is_primary_decl,
                                  a_source_sequence_entry_ptr  old_ssep)
/*
Allocate a source sequence entry for the IL entry to which sym refers and
add it to the list for the appropriate scope.  If is_primary_decl is TRUE
this is the primary declaration of the IL entity, and any existing source
sequence entry already bound to the IL entity should be demoted to
secondary status.
*/
{
  char                          *il_entry_ptr;
  an_il_entry_kind              kind;
  a_src_seq_secondary_decl_ptr  sssdp;
  a_boolean                     force_alloc_in_filescope;
  a_memory_region_number        region_to_switch_back_to;

  if (!source_sequence_entries_disallowed) {
    /* We are in a context in which source sequence entries are being
       generated. */
    if ((il_entry_ptr = il_entry_for_symbol_null_okay(sym, &kind)) != NULL) {
      if (pos->seq == 0 ||
          (kind == iek_routine &&
           ((a_routine_ptr)il_entry_ptr)->compiler_generated)) {
        /* Don't put out source sequence information on compiler generated
           functions. */
      } else {
        if (!is_primary_decl) {
          /* This is not a primary declaration, so put out an entry for a
             secondary declaration. */
          /* Switch to the file scope memory region to allocate the new entry
             if necessary. */
          if (curr_il_region_number != file_scope_region_number &&
              in_file_scope(il_entry_ptr)) {
            force_alloc_in_filescope = TRUE;
            switch_to_file_scope_region(&region_to_switch_back_to);
          } else {
            force_alloc_in_filescope = FALSE;
          }  /* if */
          sssdp = alloc_src_seq_secondary_decl();
          if (force_alloc_in_filescope) {
            switch_back_to_original_region(region_to_switch_back_to);
          }  /* if */
          /* Set the fields. */
          sssdp->decl_position = *pos;
          sssdp->entity.kind = (a_byte_il_entry_kind)kind;
          sssdp->entity.ptr = il_entry_ptr;
          /* Change the parameter values accordingly. */
          kind = iek_src_seq_secondary_decl;
          il_entry_ptr = (char *)sssdp;
          if (scope_stack[depth_scope_stack].kind ==
                                       (a_scope_kind)sck_func_prototype) {
            sssdp->declared_in_func_prototype = TRUE;
          }  /* if */
        }  /* if */
        f_update_source_sequence_list(il_entry_ptr, kind, old_ssep);
      }  /* if */
    }  /* if */
  }  /* if */
}  /* sym_update_source_sequence_list */

#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */

#if !GENERATE_SOURCE_SEQUENCE_LISTS
/* ARGSUSED */ /* <-- ssep is only used with source sequence lists. */
#endif /* !GENERATE_SOURCE_SEQUENCE_LISTS */
void record_symbol_declaration(a_symbol_reference_kind      srk_flags,
                               a_symbol_ptr                 sym_ptr,
                               a_source_position            *source_position,
                               a_source_sequence_entry_ptr  ssep)
/*
Record information about how the given symbol is declared.  The srk_flags
parameter describes the specificity of the declaration (e.g., that it is a
definition, a friend declaration, etc.).  The source position will be recorded
in the symbol as its "decl_position" (overwriting what's there already, if
this is a definition); the same will be done for the decl_position field of
the IL entry.  A cross-reference entry will be put out.  If source-sequence
entries are being generated, ssep may point to an "empty" entry already
created for this entity; otherwise, it is NULL.
*/
{
  a_boolean                is_definition = srk_flags & SRK_DEFINITION;
  a_boolean                is_tentative_def = srk_flags & SRK_TENTATIVE_DEF;
#if GENERATE_SOURCE_SEQUENCE_LISTS
  a_boolean                is_primary_decl = FALSE;
  a_boolean                set_first_decl_flag = FALSE;
  a_boolean                update_src_seq_list = TRUE;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
  a_source_correspondence  *scptr = NULL;

  if (is_definition) {
    if (sym_ptr->defined) {
      /* This is a redefinition -- allowed for C variables at file scope, for
         macros, and for C++ typedefs. */
      if (C_mode() && sym_ptr->kind == (a_symbol_kind)sk_variable &&
          !is_tentative_def) {
        /* This must be an initializing definition following a tentative
           definition. */
#if GENERATE_SOURCE_SEQUENCE_LISTS
        is_primary_decl = TRUE;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
      } else {
        /* A definition is ordinarily the primary declaration, but if it was
           previously defined and this is just a redefinition, this should be
           recorded as a secondary declaration. */
        is_definition = FALSE;
      }  /* if */
    } else {
#if GENERATE_SOURCE_SEQUENCE_LISTS
      is_primary_decl = !is_tentative_def;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
      sym_ptr->defined = TRUE;
      sym_ptr->decl_position = *source_position;
    }  /* if */
    if (is_definition) {
      sym_ptr->decl_position = *source_position;
      scptr = source_corresp_entry_for_symbol(sym_ptr);
      if (scptr != NULL) {
        if (is_template_symbol(sym_ptr)) {
          /* The decl_position field in the IL template entry is not
             updated. */
        } else {
          scptr->decl_position = *source_position;
        }  /* if */
#if EXTRA_SOURCE_POSITIONS_IN_IL
        if (scptr->decl_pos_info == NULL) {
          scptr->decl_pos_info =
                       alloc_decl_position_supplement(in_file_scope(scptr));
        } else if (is_template_symbol(sym_ptr)) {
          /* The decl-position-supplement in the IL template entry should not
             be modified. */
        } else {
          clear_decl_position_supplement(scptr->decl_pos_info);
        }  /* if */
#endif /* EXTRA_SOURCE_POSITIONS_IN_IL */
      }  /* if */
    }  /* if */
  }  /* if */
  /* Set declaration sequence numbers based on the first declaration of the
     name, regardless of whether it is the primary declaration or not. */
  if (sym_ptr->decl_seq == 0) set_decl_sequence_number(sym_ptr);
  /* Update the cross reference file if it exists. */
  if (f_xref_info != NULL) {
    /* If writing cross-reference information, write an entry for this
       declaration. */
    write_xref_entry(srk_flags, sym_ptr, source_position);
  }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  /* Issue a source sequence entry -- unless this is a label definition.  (A
     label is always defined by an stmk_label statement, for which a source
     sequence entry will be put out; putting out both would be redundant.)
     Also, sk_parameter symbols are not yet bound to a variable, so there's
     no way to put out a source sequence entry yet. */
  if ((sym_ptr->kind != (a_symbol_kind)sk_label || !is_definition) &&
      sym_ptr->kind != (a_symbol_kind)sk_parameter) {
    /* Determine whether the field definition_is_first_decl should be set
       for a class symbol.  Note that it may be changed later, if a source
       sequence entry is generated to represent a forward declaration of
       the class. */
    if (is_definition && is_class_struct_union_symbol(sym_ptr) &&
        scptr != NULL && scptr->source_sequence_entry == NULL) {
      set_first_decl_flag = TRUE;
    }  /* if */
#if TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS
    if (sym_ptr->kind == (a_symbol_kind)sk_member_function ||
        sym_ptr->kind == (a_symbol_kind)sk_routine) {
#if FRIEND_AND_MEMBER_DEFINITIONS_MAY_BE_MOVED_OUT_OF_CLASS
      if (is_definition && !C_mode() &&
          scope_stack[depth_scope_stack].kind ==
                                    (a_scope_kind)sck_class_struct_union &&
          !scope_stack[depth_scope_stack].inside_local_class &&
          has_name(scope_stack[depth_scope_stack].assoc_type)) {
        /* This is a member or friend function definition inside the
           definition of a nonlocal class.  When template instantiations are
           put out in the source sequence list, it is necessary to move the
           member or friend definition outside the class definition (i.e.,
           just after it).  That means a secondary-source-sequence entry
           should be put out here. */
        is_primary_decl = FALSE;
      }  /* if */
#endif /* FRIEND_AND_MEMBER_DEFINITIONS_MAY_BE_MOVED_OUT_OF_CLASS */
#if CLASS_TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS
    } else if (is_class_struct_union_symbol(sym_ptr) && !C_mode()) {
      if (is_definition) {
        if (scptr != NULL && scptr->source_sequence_entry == NULL) {
          /* This is the initial declaration of this class.  If appropriate,
             put out a secondary declaration entry immediately before the
             definition entry to deal with forward reference problems of
             instantiations that are inserted in front of the class; if
             there is no insertion, the entry will be removed eventually. */
          a_boolean                     add_secondary_decl;
          a_type_ptr                    class_type = type_symbol_type(sym_ptr);
          an_il_entry_kind              kind;
          a_class_type_supplement_ptr   parent_ctsp;
          a_src_seq_secondary_decl_ptr  sssdp;

          if (scptr->is_local_to_function ||
              class_type->variant.class_struct_union.originally_unnamed) {
            /* Can't be done for local functions.  It cannot be done for
               classes that got their name through a typedef either because
               the following is not legal: struct X; typedef struct {} X; */
            add_secondary_decl = FALSE;
          } else if (!scptr->is_class_member) {
            /* Okay for all classes that aren't nested. */
            add_secondary_decl = TRUE;
          } else {
            /* It's okay for nested classes only if it's a deferred
               definition (i.e., the definition appears at file or
               namespace scope). */
            parent_ctsp = scptr->parent.class_type->
                                  variant.class_struct_union.extra_info;
            add_secondary_decl = (parent_ctsp->assoc_scope->
                                     depth_in_scope_stack == NO_SCOPE_DEPTH);
          }  /* if */
          if (add_secondary_decl) {
            kind = (an_il_entry_kind)iek_type;
            sssdp = make_source_sequence_secondary_decl((char *)class_type,
                                                        kind, class_type);
            sssdp->autonomous_tag_decl = TRUE;
            sssdp->decl_position = *source_position;
            sssdp->compiler_generated_forward_decl = TRUE;
            sssdp->first_declaration = TRUE;
            set_first_decl_flag = FALSE;
            if (class_type->variant.class_struct_union.is_template_class) {
#if BACK_END_IS_CP_GEN_BE
              sssdp->specialized_with_new_syntax =
                            !old_specializations_for_generated_instances;
#else /* !BACK_END_IS_CP_GEN_BE */
              sssdp->specialized_with_new_syntax = TRUE;
#endif /* BACK_END_IS_CP_GEN_BE */
            }  /* if */
            kind = (an_il_entry_kind)iek_src_seq_secondary_decl;
            add_to_source_sequence_list((char *)sssdp, kind);
            /* Reset the insertion point for instantiations to NULL. */
            reset_ss_list_instantiation_insert_point();
          }  /* if */
        }  /* if */
      } else if (depth_innermost_instantiation_scope != NO_SCOPE_DEPTH) {
        /* Not a definition.  If this is a nested class declaration inside
           a class template instantiation, only put out the declaration if
           it's the first.  This is to deal with the following case:
             template <class T> class A {
               class N;
               class N { ... };
             };
             A<int> x;
           where the instantiation of A<int> would be represented in the
           generated C++ as a specialization:
             template<> class A<int> {
               class N;
               class N;                // declaration substitutes for
             };                        //    inline definition
             class A<int>::N { ... }   // if needed
           The problem is that a second declaration of class N is disallowed
           (9.2 paragraph 1 of the C++ standard).  The solution is to suppress
           any declaration of a nested class other than the first. */
        a_scope_stack_entry_ptr scope_stack_ptr =
                                         &scope_stack[depth_scope_stack];
        if (!scope_stack_ptr->in_prototype_instantiation &&
            scope_stack_ptr->kind == (a_scope_kind)sck_class_struct_union &&
            sym_ptr->is_class_member &&
            sym_ptr->parent.class_type == scope_stack_ptr->assoc_type) {
          scptr = source_corresp_entry_for_symbol(sym_ptr);
          if (scptr != NULL && scptr->source_sequence_entry != NULL) {
            update_src_seq_list = FALSE;
          }  /* if */
        }  /* if */
      }  /* if */
#endif /* CLASS_TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS */
    }  /* if */
#endif /* TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS */
    if (update_src_seq_list) {      /*lint !e774*/
      if (is_definition) {
        /* If this is a primary declaration (or a tentative definition that
           is the first definition of the variable), erase the previous
           source sequence entry bound to this entity (if any). */
        if (scptr != NULL) scptr->source_sequence_entry = NULL;
        if (set_first_decl_flag) {
          sym_ptr->variant.class_struct_union.extra_info->
                                         definition_is_first_decl = TRUE;
        }  /* if */
      }  /* if */
      sym_update_source_sequence_list(sym_ptr, source_position,
                                      is_primary_decl, ssep);
    }  /* if */
  }  /* if */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
#if RECORD_HIDDEN_NAMES_IN_IL
  /* If appropriate, set a flag in the symbol header to indicate that at
     least one declaration with this name was a tag name and/or appeared in
     the file scope or a namespace scope.  The information is used in
     building the hidden name table.  Command-line macro definitions should
     not be considered as appearing in file scope. */
  if (!sym_ptr->is_error &&
      sym_ptr->kind != (a_symbol_kind)sk_undefined &&
      sym_ptr->kind != (a_symbol_kind)sk_macro) {
    a_symbol_header_ptr  hdr = sym_ptr->header;

    if (is_tag_symbol(sym_ptr)) hdr->any_tag_decl = TRUE;
    if (!sym_ptr->is_class_member) {
      if (sym_ptr->decl_scope == file_scope_number ||
          sym_ptr->parent.namespace_ptr != NULL) {
        hdr->any_decl_in_file_or_namespace_scope = TRUE;
      } else if (is_template_symbol(sym_ptr)) {
        hdr->any_decl_in_file_or_namespace_scope = TRUE;
      } else if (depth_innermost_function_scope != NO_SCOPE_DEPTH ||
                 scope_stack[depth_scope_stack].kind ==
                                      (a_scope_kind)sck_class_struct_union) {
        /* We're in the context of a function definition or a friend function
           in a local class.  Does sym_ptr represent a block extern
           declaration?  Check the IL entry. */
        if (scptr == NULL) scptr = source_corresp_entry_for_symbol(sym_ptr);
        if (scptr != NULL && !scptr->is_local_to_function) {
          hdr->any_decl_in_file_or_namespace_scope = TRUE;
        }  /* if */
      }  /* if */
    }  /* if */        
  }  /* if */
#endif /* RECORD_HIDDEN_NAMES_IN_IL */
}  /* record_symbol_declaration */


void record_symbol_reference(a_symbol_reference_kind kind,
                             a_symbol_ptr            sym_ptr,
                             a_source_position       *source_position,
                             a_boolean               update_il_entry)
/*
Record a reference of the indicated kind to the indicated symbol.  Set the
referenced flag in the symbol entry.  If update_il_entry is TRUE, also
set the referenced flag in the associated IL entry, if any.  Mark the
symbol "used" or "set", if appropriate.  sym_ptr should not point to a
projection symbol.
*/
{
  a_source_correspondence *scptr;
  a_symbol_kind           sym_kind = sym_ptr->kind;
 
  check_assertion_str(sym_ptr->kind != (a_symbol_kind)sk_projection &&
                      sym_ptr->kind != (a_symbol_kind)sk_namespace_projection,
                      "record_symbol_reference: projection symbol");
  /* If writing cross-reference information, write an entry for this
     declaration. */
  if (f_xref_info != NULL) {
    a_symbol_ptr             sym_for_xref = sym_ptr;
    a_symbol_reference_kind  kind_for_xref = kind;
    a_type_ptr               tp;

    if (sym_kind == (a_symbol_kind)sk_type) {
      if (sym_ptr->is_template_param) {
        /* A reference to a template parameter during template instantiation is
           actually a reference to the template argument that it represents. */
        tp = sym_ptr->variant.type.ptr;
        if (tp->kind == (a_type_kind)tk_template_param) {
          /* We are in the midst of a template definition. */
        } else {
          /* We are in the midst of a template instantiation. */
          for(;;) {
            if (tp->kind == (a_type_kind)tk_typeref) {
              if (typeref_is_qualified(tp)) {
                tp = tp->variant.typeref.type;
              } else {
                sym_for_xref = (a_symbol_ptr)tp->source_corresp.assoc_info;
                check_assertion(sym_for_xref != NULL);
                kind_for_xref |= SRK_IMPLICIT_TEMPLATE_ARG;
                break;
              }  /* if */
            } else if (is_array_type(tp)) {
              tp = array_element_type(tp);
            } else if (is_ptr_or_ref_type(tp)) {
              tp = type_pointed_to(tp);
            } else {
              break;
            }  /* if */
          }  /* for */
        }  /* if */
      }  /* if */
    } else if (is_class_symbol(sym_ptr)) {
      tp = type_symbol_type(sym_ptr);
      if (is_immediate_class_type(tp) && !sym_ptr->is_class_member) {
        a_class_symbol_supplement_ptr  cssp;
        cssp = sym_ptr->variant.class_struct_union.extra_info;
        if (tp->variant.class_struct_union.is_prototype_instantiation) {
          /* A reference to a top-level prototype instantiation (i.e., not a
             nested class) is put out as a reference to the template itself. */
          sym_for_xref = cssp->class_template;
          check_assertion(sym_for_xref != NULL);
        }  /* if */
      }  /* if */
    }  /* if */
    write_xref_entry(kind_for_xref, sym_for_xref, source_position);
  }  /* if */
  /* Set the referenced flag in the symbol. */
  sym_ptr->referenced = TRUE;
  scptr = source_corresp_entry_for_symbol(sym_ptr);
  if (update_il_entry && scptr != NULL) {
    /* Set the referenced flag in the associated intermediate language entry,
       if there is one.  Note that more than one symbol can point to the same
       IL entry.  Use the fact that all the IL tables begin with
       a_source_correspondence. */
    /* If the symbol is for a virtual function, do not set the IL referenced
       flag; a reference to the symbol is not necessarily a reference to the
       corresponding IL entry.  When it is, the flag is set explicitly
       elsewhere. */
    if (sym_kind == (a_symbol_kind)sk_member_function &&
        sym_ptr->variant.routine.ptr->is_virtual) {
      /* Do not set IL referenced flag. */
    } else {
      if (sym_kind == (a_symbol_kind)sk_static_data_member &&
          /* Don't instantiate things in default arguments.  They get
             instantiated if the default argument is actually used. */
          !(kind & SRK_DEFAULT_ARG_EXPR)) {
        /* If we are marking a template static data member as referenced, also
           set its instantiation required flag. */
        set_instance_required(sym_ptr, TRUE, /*defer_inline=*/FALSE);
      }  /* if */
      scptr->referenced = TRUE;
    }  /* if */
  }  /* if */
  if (update_il_entry && (kind & SRK_ADDRESS_TAKEN)) {
    /* Set the address_taken flag in variables and routines. */
    if (sym_kind == (a_symbol_kind)sk_variable) {
      set_variable_address_taken(sym_ptr->variant.variable.ptr);
    } else if (sym_kind == (a_symbol_kind)sk_static_data_member) {
      set_variable_address_taken(sym_ptr->variant.static_data_member.variable);
    } else if (sym_kind == (a_symbol_kind)sk_routine ||
               sym_kind == (a_symbol_kind)sk_member_function) {
      sym_ptr->variant.routine.ptr->address_taken = TRUE;
    }  /* if */
  }  /* if */
  if (sym_kind == (a_symbol_kind)sk_variable) {
    /* If this reference is a use or, by taking the variable's address, a
       potential use, mark the variable has having been used.  Note that for
       an error reference, the variable is marked as being both set
       and modified, to keep diagnostics from being issued down the road; nor
       are diagnostics issued here. */
    a_scope_stack_entry_ptr  ssep;
    a_variable_ptr           vp = sym_ptr->variant.variable.ptr;
    if (kind & (SRK_ALL_VARIABLE_USES | SRK_ERROR)) {
      if (sym_ptr->variant.variable.used) {
        /* This is not the first use. */
        if (vp->is_parameter || vp->is_handler_param) {
          /* Mark the parameter as multiply used (information that may be
             useful for inlining). */
          vp->param_used_more_than_once = TRUE;
        }  /* if */
      } else {
        /* This is the first use of the variable. */
        if (!(kind & SRK_USE) || suppress_used_before_set_warnings ||
            sym_ptr->variant.variable.value_has_been_set) {
          /* No diagnostic. */
        } else if (!vp->source_corresp.is_local_to_function) {
          /* A block-extern variable or a namespace-scope variable with
             internal linkage -- no diagnostic. */
        } else {
          /* Variable's value has not been set yet.  Issue a warning, if
             appropriate. */
          a_boolean suppress_warning = FALSE;

          if (!C_mode()) {
            /* In C++ don't put out a warning if the variable is of class
               type (or array of class type) and the class has no fields. */
            a_type_ptr  tp = vp->type;
            if (is_array_type(tp)) tp = underlying_array_element_type(tp);
            if (is_class_struct_union_type(tp) &&
                !symbol_supplement_for_class(tp)->any_nonstatic_data_members) {
              /* Variable is of empty-class type. */
              suppress_warning = TRUE;
            }  /* if */
          }  /* if */
          if (!suppress_warning) {
            /* To determine whether to suppress the warning, examine the scope
               stack for labels and uncompleted loops that might enable the
               program to set the variable in code that has not yet been seen
               and then to branch back to the current code.  In other words,
               only issue a warning if we're sure the variable cannot have
               been set. */
            for (ssep = &scope_stack[decl_scope_level]; ; --ssep) {
              check_assertion(ssep != &scope_stack[0]);
              if (ssep->kind == (a_scope_kind)sck_function) {
                /* A reference to a local variable from within quasi-nested
                   function definition should have been reported as an error
                   and recorded as an srk_error reference. */
                check_assertion(ssep->number == sym_ptr->decl_scope ||
                                !scptr->is_local_to_function);
                /* We are at the outermost scope of the function.  Check for
                   a label. */
                goto check_label_decl_seq;
              } else if (ssep->number == sym_ptr->decl_scope) {
                /* We are at the scope in which the variable was declared.
                   Jump out to the function scope and look for a label. */
                ssep = &scope_stack[depth_innermost_function_scope];
check_label_decl_seq:
                /* If the variable was declared before the label, suppress the
                   warning.  If it was declared after the label, the warning
                   is appropriate.  For example:
                     void f() {
                       int i;
                         :
                     L:
                       int j;
                       ++i;          // No warning -- i may be set later.
                       ++j;          // Warning -- j cannot have been set yet.
                           :
                     }
                */
                if (ssep->last_label_decl_seq > sym_ptr->decl_seq) {
                  /* Variable was declared before the label was defined. */
                  suppress_warning = TRUE;
                }  /* if */
                break;
              } else if (ssep->is_loop_scope) {
                /* The variable was declared in a scope outside the loop
                   scope, so suppress the warning.  If it were declared within
                   the loop, the warning would still be okay.  For example:
                     void f() {
                       int i;
                         :
                       for (;;) {
                         int j;
                         ++i;        // No warning -- i may be set later.
                         ++j;        // Warning -- j cannot have been set yet.
                           :
                       }
                     }
                */
                suppress_warning = TRUE;
                break;
              }  /* if */
            }  /* for */
          }  /* if */
          if (!suppress_warning) {
            pos_sy_warning(ec_used_before_set, source_position, sym_ptr);
          }  /* if */
        }  /* if */
        sym_ptr->variant.variable.used = TRUE;
        if (scptr != NULL) {
          /* The variable may point to a different symbol in cases like
             this:
               static int i = 1;
               int f() { extern int i; return i; }
             and it is necessary for the file-scope symbol to be marked
             "used" too. */
          if ((a_symbol_ptr)scptr->assoc_info != sym_ptr) {
            ((a_symbol_ptr)scptr->assoc_info)->variant.variable.used = TRUE;
          }  /* if */
        }  /* if */
      }  /* if */
    }  /* if */
    /* If this reference involves a modification or, by taking the variable's
       address, a potential modification, mark the variable as having its
       value set. */
    if (kind & (SRK_ALL_VARIABLE_MODIFICATIONS | SRK_ERROR)) {
      mark_variable_value_set(sym_ptr);
      if (exceptions_enabled) {
        /* If the modification takes place inside a try block and the
           variable was declared in a (function-local) scope that contains
           the try block, then it may have to be treated as quasi-volatile
           -- it may need to be stored immediately in case an exception is
           thrown. */
        vp = sym_ptr->variant.variable.ptr;
        if (!vp->source_corresp.is_local_to_function) {
          /* Don't worry about file-scope variables. */
        } else if (vp->modified_within_try_block) {
          /* Flag is already set. */
        } else {
          ssep = &scope_stack[decl_scope_level];
          if (ssep->within_try_block) {
            /* This modification is inside a try block. */
            for (;;) {
              if (ssep->number == sym_ptr->decl_scope) {
                /* Symbol was declared inside the try block.  It's only those
                   declared outside the try block we're interested in. */
                break;
              } else if (ssep->is_try_block) {
                /* We've reached the try block's scope without finding the
                   scope in which the variable was declared.  Set the flag
                   and break out of the loop. */
                vp->modified_within_try_block = TRUE;
                break;
              }  /* if */
              /* Advance up the scope stack. */
              --ssep;
              check_assertion_str2(ssep->within_try_block,
                                   "record_symbol_reference:",
                                   "within_try_block not set properly");
            }  /* for */
          } /* if */
        }  /* if */
      }  /* if */
    }  /* if */
  }  /* if */
}  /* record_symbol_reference */


void reference_to_invalid_name(a_symbol_locator *locator)
/*
A name was referred to in a declaration but was invalid -- either it was
undefined or it was not being used correctly.  Put out cross reference
information on the reference, if required.
*/
{
  a_symbol_locator  loc;

  if (f_xref_info != NULL) {
    loc = *locator;
    if (loc.specific_symbol == NULL && !is_error_locator(loc)) {
      make_specific_symbol_error_locator(&loc);
    }  /* if */
    write_xref_entry(SRK_ERROR | SRK_REFERENCE, loc.specific_symbol,
                     &loc.source_position);
  }  /* if */
}  /* reference_to_invalid_name */


void record_param_id_list_declarations(a_func_info_block_ptr func_info)
/*
The function with which the param-id list headed by pid is associated has
been declared but not defined.  The symbols associated with the parameter
declarations should be recorded for cross referencing and any associated
source-sequence entries should be removed from the list.
*/
{
  a_param_id_ptr  pid = func_info->param_id_list;
#if GENERATE_SOURCE_SEQUENCE_LISTS
  a_source_sequence_entry_ptr  ss_list = func_info->prototype_scope_ss_list;
  a_source_sequence_entry_ptr  ssep, next_ssep, *avail_list;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */

  /* Update xref information on each symbol. */
  for (; pid != NULL; pid = pid->next) {
    if (pid->symbol != NULL) {
      mark_declared(pid->symbol, &pid->symbol->decl_position);
    }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
    if (pid->source_sequence_entry != NULL) {
      check_assertion(ss_entry_kind(pid->source_sequence_entry) ==
                                             (an_il_entry_kind)iek_none);
      if (ss_list != NULL) {
        ssep = ss_list;
        for (; ssep != pid->source_sequence_entry; ssep = ssep->next) {
          check_assertion(ssep != NULL);
        }  /* for */
        if (ssep == ss_list) {
          ss_list = ssep->next;
        } else {
          ssep->prev->next = ssep->next;
        }  /* if */
        if (ssep->next != NULL) ssep->next->prev = ssep->prev;
        if (in_file_scope(ssep)) {
          avail_list = &scope_stack[DEPTH_OF_FILE_SCOPE].
                                              source_sequence_avail_list;
        } else {
          check_assertion(depth_innermost_function_scope != NO_SCOPE_DEPTH);
          avail_list = &scope_stack[depth_innermost_function_scope].
                                              source_sequence_avail_list;
        }  /* if */
        ssep->next = *avail_list;
        *avail_list = ssep;
      }  /* if */
      pid->source_sequence_entry = NULL;
    }  /* if */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
  }  /* for */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  for (ssep = ss_list; ssep != NULL; ssep = next_ssep) {
    next_ssep = ssep->next;
    if (ssep->prev != NULL) ssep->prev->next = next_ssep;
    if (ssep->next != NULL) ssep->next->prev = ssep->prev;
    ssep->next = ssep->prev = NULL;
    add_source_sequence_entry_to_list(ssep);
  }  /* for */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
}  /* record_param_id_list_declarations */


#if !GENERATE_SOURCE_SEQUENCE_LISTS
/*ARGSUSED*/ /* udp and prev_udp are used only for source sequence entries. */
#endif /* !GENERATE_SOURCE_SEQUENCE_LISTS */
void record_using_decl(a_symbol_ptr       sym,
                       a_source_position  *pos,
                       a_using_decl_ptr   udp,
                       a_using_decl_ptr   prev_udp)
/*
udp points to a using-decl entry created to represent an using declaration
specifying fundamental symbol sym.  If appropriate, update the cross reference
and source sequence output.  prev_udp, if non-NULL, refers to the previously
created using-decl in a function overload set.  *pos is the source position of
the identifier in the using-declaration.
*/
{
  /* Update the cross reference file if it exists. */
  if (f_xref_info != NULL) {
    /* If writing cross-reference information, write an entry for this
       declaration. */
    write_xref_entry(SRK_DECLARATION, sym, pos);
  }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  if (!source_sequence_entries_disallowed) {
    if (prev_udp == NULL) {
      add_to_source_sequence_list((char *)udp,
                                  (an_il_entry_kind)iek_using_decl);
    } else {
      prev_udp->next_in_overload_set = udp;
    }  /* if */
  }  /* if */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
}  /* record_using_decl */


static a_boolean is_cfront_base_class_destructor_access_bug(
                                                a_symbol_ptr   sym,
                                                a_routine_ptr  rp,
                                                a_type_ptr     class_of_object)
/*
Cfront has a bug in which a private destructor in a base class can be
called when the derived class really should not have access to it.
This function, which should only be called in cfront mode, detects
the condition in which the access error should be suppressed.
*/
{
  a_boolean  result = FALSE;
  if (rp->special_kind == (a_special_function_kind)sfk_destructor &&
      !same_entities(sym->parent.class_type, class_of_object) &&
      class_of_object != NULL) {
    result = TRUE;
  }  /* if */
  return result;
}  /* is_cfront_base_class_destructor_access_bug */


void reference_to_implicitly_invoked_function
                                (a_symbol_ptr       sym,
                                 a_source_position  *pos,
                                 a_type_ptr         class_of_object,
                                 a_boolean          honor_virtual,
                                 a_boolean          evaluated,
                                 a_boolean          instantiate)
/*
sym is points to a symbol for a special member function that is invoked
implicitly -- e.g., a copy constructor that is called when a class
object is passed by value or an assignment operator that is called when
another assignment operator function is being created.  Check that the
special member function is accessible and mark the routine entry
referenced.  sym can be a projection symbol.  *pos gives the source
position of the reference.  class_of_object points to the type of the
object for which the function is being called, which is not always the
same as the class of which the function is a member.  This is used to
check protected member access which only applies to objects of a
derived class.  class_of_object may be NULL if protected member access
checking is not needed.  Also, if the routine is compiler generated, it
may still need to be defined, since the definition may have been put
off until an actual reference occurred (e.g., ARM 12.8).  This function
deals with implicitly called constructors, destructors, assignment
operators, and conversion functions.  If honor_virtual is TRUE, and the
function is virtual, the reference is considered to be a virtual call;
that means the access control checking is done, but the IL entry is not
marked as referenced.  If evaluated is FALSE, the reference is within
an unevaluated expression; again, access control checking is done, but
the IL entry is not marked as referenced.  If instantiate is TRUE and
the function is a template function, it should be instantiated.
*/
{
  a_symbol_ptr  base_sym = fundamental_symbol_of(sym);
  a_routine_ptr rp = base_sym->variant.routine.ptr;

  check_assertion(rp->special_kind ==
                               (a_special_function_kind)sfk_constructor ||
                  rp->special_kind ==
                               (a_special_function_kind)sfk_destructor ||
                  rp->special_kind ==
                               (a_special_function_kind)sfk_conversion ||
                  (rp->special_kind == (a_special_function_kind)sfk_operator &&
                   rp->opname_or_builtin.opname_kind == 
                               (an_opname_kind)onk_assign));
#if MICROSOFT_EXTENSIONS_ALLOWED
  if (microsoft_mode && depth_stmt_stack >= 0 &&
      struct_stmt_stack[depth_stmt_stack].in_handler_parameter_declaration &&
      is_constructor_symbol(base_sym)) {
    /* Don't check access on constructors while processing handler parameters
       in Microsoft mode. */
  } else
#endif /* MICROSOFT_EXTENSIONS_ALLOWED */
  {
    /* Check for accessibility. */
    if (!have_access_to_symbol(sym)) {
      an_error_severity  severity = es_discretionary_error;
      /* Normally an error, but in cfront mode there is a special case
         involving a private base class destructor where we issue a warning. */
      if (any_cfront_mode() &&
          is_cfront_base_class_destructor_access_bug(sym, rp,
                                                     class_of_object)) {
        severity = es_warning;
      }  /* if */
      pos_sy_diagnostic(severity, ec_inaccessible_special_function,
                        pos, sym);
    } else if (class_of_object != NULL) {
      /* Protected members of a base class can only be accessed through an
         object of a derived class. */
      check_protected_member_access(sym, pos, class_of_object);
    }  /* if */
  }  /* if */
  /* Update the symbol and the cross-reference listing. */
  record_symbol_reference((SRK_REFERENCE | SRK_IMPLICIT), base_sym, pos,
                          /*update_il_entry=*/FALSE);
  if (!evaluated) {
    /* Unevaluated expression.  Do not set the IL referenced flag. */
  } else if (rp->is_virtual && honor_virtual) {
    /* Virtual function call.  Do not set the IL referenced flag because the
       call might actually be of an overriding function. */
  } else {
    /* Non-virtual call. */
    mark_routine_referenced_full(rp, instantiate);
  }  /* if */
}  /* reference_to_implicitly_invoked_function */


a_boolean reference_to_trivial_default_constructor(
                                              a_type_ptr         class_type,
                                              a_source_position  *pos)
/*
If class_type has an associated trivial default constructor, record a
reference to it -- checking its accessibility, updating the cross-reference
listing if appropriate, and assuring that it is defined, which is done (even
though the function is not actually called) in case the definition has side
effects.  If class_type does have a trivial default constructor (which
should never be the case for PODs, for classes with any user-declared
constructors, or for classes with an implicitly declared nontrivial default
constructor), return TRUE.
*/
{
  a_symbol_ptr   ctor_sym;

  check_assertion(is_class_struct_union_type(class_type));
  ctor_sym = symbol_supplement_for_class(class_type)->
                                            trivial_default_constructor;
  if (ctor_sym != NULL) {
    reference_to_implicitly_invoked_function(ctor_sym, pos, class_type,
                                             /*honor_virtual=*/FALSE,
                                             /*evaluated=*/TRUE,
                                             /*instantiate=*/TRUE);
  }  /* if */
  return (ctor_sym != NULL);
}  /* reference_to_trivial_default_constructor */


/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-1994 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
