/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-1994 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
/*

symbol_ref.c - Routines to manage references to symbols.

*/

/* Header files common to all files. */
#include "fe_common.h"
#include "symbol_tbl.h"

#if HDRSTOP_RECOGNIZED
/* Insert a marker in case headers are saved and restored. */
#pragma hdrstop
#endif /* HDRSTOP_RECOGNIZED */

/* Additional header files. */
#include "symbol_ref.h"


static an_il_to_str_output_control_block
		octl;
			/* Output control block used to interface to the
			   il_to_str routines. */

static a_boolean
		output_control_block_has_been_set_up = FALSE;
			/* Flag that indicates whether initialization has
			   already been done on the output control block. */

static void write_string_to_xref_file(char *str)
/*
Write str to the xref file.  The address of this routine is passed to
the il_to_str routines for generating formatted names.
*/
{
  (void)fputs(str, f_xref_info);
}  /* write_string_to_xref_file */


static void write_xref_entry(a_symbol_reference_kind srk_flags,
                             a_symbol_ptr            sym_ptr,
                             a_source_position       *source_position)
/*
Write information to f_xref_info describing a reference of kind "kind"
to symbol "sym_ptr" at source position "source_position".  This routine
should only be called if cross-reference information is being generated
(i.e., f_xref_info != NULL).
*/
{
  char              code;
  char              *file_name, *full_name;
  a_line_number     line_number;
  a_boolean         at_end_of_source;

  if (!output_control_block_has_been_set_up) {
    /* Set octl so that it can be passed into the il_to_str routines to tell
       them how to output to write a string to the xref file. */
    clear_il_to_str_output_control_block(&octl);
    octl.output_str = write_string_to_xref_file;
    output_control_block_has_been_set_up = TRUE;
  }  /* if */
  if (sym_ptr->kind == (a_symbol_kind)sk_extern_variable ||
             sym_ptr->kind == (a_symbol_kind)sk_extern_routine) {
    /* Ignore extern variable and routine symbols.  They are really just
       shadow symbols for the the real ones. */
  } else if (is_unnamed_class_symbol(sym_ptr)) {
    /* Ignore symbols for unnamed classes */
  } else if (source_position->seq == 0) {
    /* This symbol is not associated with any particular source position. */
  } else if (depth_innermost_instantiation_scope != NO_SCOPE_DEPTH &&
             (sym_ptr->is_template_param ||
              scope_stack[depth_scope_stack].in_prototype_instantiation)) {
    /* Ignore template parameter symbols encountered during template
       instantiation and any symbols encountered during prototype
       instantiation. */
  } else {
    /* The record written to the file is a text line that looks like

       symbol-id name X file-name line-number column-number

       The separator character between the fields is a horizontal tab.
       where X is "d" for declaration,
                  "D" for definition,
                  "M" for modification,
                  "A" for address taken,
                  "U" for use,
                  "C" for changed (i.e., used and modified in one
                      operation, such as an increment operation),
                  "R" for generic reference, or
                  "E" for error.
       The symbol-id is a unique number for the symbol, generated by 
       casting the symbol pointer to unsigned long.
    */
    if (srk_flags & SRK_DECLARATION) {
      if (srk_flags & SRK_DEFINITION) {
        code = 'D';
      } else {
        code = 'd';
      }  /* if */
    } else if (srk_flags & SRK_REFERENCE) {
      if (srk_flags & SRK_USE) {
        if (srk_flags & SRK_MODIFICATION) {
          code = 'C';
        } else {
          code = 'U';
        }  /* if */
      } else if (srk_flags & SRK_MODIFICATION) {
        code = 'M';
      } else if (srk_flags & SRK_ADDRESS_TAKEN) {
        code = 'A';
      } else if (srk_flags & SRK_ERROR) {
        code = 'E';
      } else {
        code = 'R';
      }  /* if */
#if CHECKING
    } else {
      internal_error("write_xref_entry: bad reference kind");
#endif /* CHECKING */
    }  /* if */
    /* Convert the source position to file name/line number. */
    conv_seq_to_file_and_line(source_position->seq, &file_name, &full_name,
                              &line_number, &at_end_of_source);
    fprintf(f_xref_info, "%lu\t", (unsigned long)sym_ptr);
    /* Write the symbol name, complete with class qualifier, etc., to the
       xref file. */
    form_symbol_name(sym_ptr, &octl);
    fprintf(f_xref_info, "\t%c\t%s\t%lu\t%d\n",
                         code,
                         file_name,
                         line_number,
                         source_position->column);
  }  /* if */
}  /* write_xref_entry */


void mark_variable_value_set(a_symbol_ptr  sym)
/*
Set the "value_has_been_set" flag of the variable symbol pointed to by sym.
*/
{
  check_assertion(sym->kind == (a_symbol_kind)sk_variable);
  if (sym->variant.variable.value_has_been_set) {
    /* Variable has already been set. */
    a_variable_ptr  vp = sym->variant.variable.ptr;
    if (vp->is_parameter || vp->is_handler_param) {
      /* Since parameters are by definition initialized (by the actual
         argument), any subsequent modification is a change to the initial
         value.  Knowning this can be useful for inlining. */
      vp->param_value_has_been_changed = TRUE;
    }  /* if */
  } else {
    sym->variant.variable.value_has_been_set = TRUE;
  }  /* if */
}  /* mark_variable_value_set */

#if GENERATE_SOURCE_SEQUENCE_LISTS

static void sym_update_source_sequence_list(
                                  a_symbol_ptr                 sym,
                                  a_source_position            *pos,
                                  a_boolean                    is_primary_decl,
                                  a_source_sequence_entry_ptr  old_ssep)
/*
Allocate a source sequence entry for the IL entry to which sym refers and
add it to the list for the appropriate scope.  If is_primary_decl is TRUE
this is the primary declaration of the IL entity, and any existing source
sequence entry already bound to the IL entity should be demoted to
secondary status.
*/
{
  char                          *il_entry_ptr;
  an_il_entry_kind              kind;
  a_src_seq_secondary_decl_ptr  sssdp;
  a_boolean                     force_alloc_in_filescope;
  a_memory_region_number        region_to_switch_back_to;

  if (!source_sequence_entries_disallowed) {
    /* We are in a context in which source sequence entries are being
       generated. */
    if ((il_entry_ptr = il_entry_for_symbol(sym, &kind)) != NULL) {
      if (pos->seq == 0 ||
          (kind == iek_routine &&
           ((a_routine_ptr)il_entry_ptr)->compiler_generated)) {
        /* Don't put out source sequence information on compiler generated
           functions. */
      } else {
        if (!is_primary_decl) {
          /* This is not a primary declaration, so put out an entry for a
             secondary declaration. */
          /* Switch to the file scope memory region to allocate the new entry
             if necessary. */
          if (curr_il_region_number != FILE_SCOPE_REGION_NUMBER &&
              in_file_scope(il_entry_ptr)) {
            force_alloc_in_filescope = TRUE;
            switch_to_file_scope_region(&region_to_switch_back_to);
          } else {
            force_alloc_in_filescope = FALSE;
          }  /* if */
          sssdp = alloc_src_seq_secondary_decl();
          if (force_alloc_in_filescope) {
            switch_back_to_original_region(region_to_switch_back_to);
          }  /* if */
          /* Set the fields. */
          sssdp->decl_position = *pos;
          sssdp->entity.kind = (a_byte_il_entry_kind)kind;
          sssdp->entity.ptr = il_entry_ptr;
          /* Change the parameter values accordingly. */
          kind = iek_src_seq_secondary_decl;
          il_entry_ptr = (char *)sssdp;
        }  /* if */
        f_update_source_sequence_list(il_entry_ptr, kind, old_ssep);
      }  /* if */
    }  /* if */
  }  /* if */
}  /* sym_update_source_sequence_list */

#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */

#if !GENERATE_SOURCE_SEQUENCE_LISTS
/* ARGSUSED */ /* <-- ssep is only used with source sequence lists. */
#endif /* !GENERATE_SOURCE_SEQUENCE_LISTS */
void record_symbol_declaration(a_symbol_reference_kind      srk_flags,
                               a_symbol_ptr                 sym_ptr,
                               a_source_position            *source_position,
                               a_source_sequence_entry_ptr  ssep)
/*
Record information about how the given symbol is declared.  The srk_flags
parameter describes the specificity of the declaration (e.g., that it is a
definition, a friend declaration, etc.).  The source position will be recorded
in the symbol as its "decl_position" (overwriting what's there already, if
this is a definition); the same will be done for the decl_position field of
the IL entry.  A cross-reference entry will be put out.  If source-sequence
entries are being generated, ssep may point to an "empty" entry already
created for this entity; otherwise, it is NULL.
*/
{
  a_boolean                is_definition = srk_flags & SRK_DEFINITION;
  a_boolean                is_tentative_def = srk_flags & SRK_TENTATIVE_DEF;
  a_boolean                is_primary_decl = FALSE;
  a_source_correspondence  *scptr = NULL;

  if (is_definition) {
    if (sym_ptr->defined) {
      /* This is a redefinition -- allowed for C variables at file scope, for
         macros, and for C++ typedefs. */
      if (C_mode() && sym_ptr->kind == (a_symbol_kind)sk_variable &&
          !(srk_flags & SRK_TENTATIVE_DEF)) {
        /* This must be an initializing definition following a tentative
           definition. */
        is_primary_decl = TRUE;
      } else {
        /* A definition is ordinarily the primary declaration, but if it was
           previously defined and this is just a redefinition, this should be
           recorded as a secondary declaration. */
        is_definition = FALSE;
      }  /* if */
    } else {
      is_primary_decl = !is_tentative_def;
      sym_ptr->defined = TRUE;
      sym_ptr->decl_position = *source_position;
    }  /* if */
    if (is_definition) {
      sym_ptr->decl_position = *source_position;
      scptr = source_corresp_entry_for_symbol(sym_ptr);
      if (scptr != NULL) scptr->decl_position = *source_position;
    }  /* if */
  }  /* if */
  /* Set declaration sequence numbers based on the first declaration of the
     name, regardless of whether it is the primary declaration or not. */
  if (sym_ptr->decl_seq == 0) set_decl_sequence_number(sym_ptr);
  /* Update the cross reference file if it exists. */
  if (f_xref_info != NULL) {
    /* If writing cross-reference information, write an entry for this
       declaration. */
    write_xref_entry(srk_flags, sym_ptr, source_position);
  }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  /* Issue a source sequence entry -- unless this is a label definition.  (A
     label is always defined by an stmk_label statement, for which a source
     sequence entry will be put out.  Putting out both would be redundant. */
  if (sym_ptr->kind != (a_symbol_kind)sk_label) {
    if (is_definition) {
      /* If this is a primary declaration (or a tentative definition that
         is the first definition of the variable), erase the previous
         source sequence entry bound to this entity (if any). */
      if (scptr != NULL) scptr->source_sequence_entry = NULL;
    }  /* if */
    sym_update_source_sequence_list(sym_ptr, source_position,
                                    is_primary_decl, ssep);
  }  /* if */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
#if RECORD_HIDDEN_NAMES_IN_IL
#if 0
/* The following can be improved (but made more fragile, with only a little
   gain) by minimizing the number of hidden-name entries put out.  For
   instance, we can skip to the file scope when the instantiation scope is
   encountered.  Also, we should only mark the innermost non-file-scope tag
   symbol as unhidable by an elaborated type specifier.  Other cases?  But
   is it worth the trouble? */
#endif /* if 0 */
  if (!C_mode()) {
    a_scope_depth   scope_depth;
    a_boolean       check_for_tag_sym;
    a_type_ptr      class_type;
    a_scope_ptr     sp;
    a_boolean       is_local_to_function = FALSE;
    a_symbol_ptr    old_sym_ptr;

    if (depth_scope_stack == DEPTH_OF_FILE_SCOPE &&
        sym_ptr->class_of_which_a_member != NULL) {
      /* Ignore member definitions outside the class definition. */
    } else if (sym_ptr->kind == (a_symbol_kind)sk_parameter) {
      /* Ignore parameter symbols.  The only parameters that are interesting
         are the ones that have been turned into variables. */
    } else if (depth_innermost_instantiation_scope != NO_SCOPE_DEPTH ||
               depth_template_declaration_scope != NO_SCOPE_DEPTH ||
               (sym_ptr->class_of_which_a_member != NULL &&
                is_template_class_type(sym_ptr->class_of_which_a_member))) {
      /* We don't deal with templates yet. */
    } else {
      scope_depth = scope_depth_of(sym_ptr, &is_local_to_function);
      if (scope_depth > DEPTH_OF_FILE_SCOPE) {
        /* If the current declaration hides a declaration at a containing
           scope, record that information in the IL. */
        sp = NULL;
        check_for_tag_sym = !is_tag_symbol(sym_ptr);
        for (old_sym_ptr = sym_ptr->next;
             old_sym_ptr != NULL;
             old_sym_ptr = old_sym_ptr->next) {
          if (check_for_tag_sym && is_tag_symbol(old_sym_ptr)) {
            /* The current symbol is a nontag symbol, and the hidden symbol is
               a tag symbol.  The latter can be unhidden by an elaborated type
               specifier. */
            record_defeatable_name_hiding(old_sym_ptr,
                                          /*tag_hidden_by_nontag=*/TRUE, sp);
          }  /* if */
          if (old_sym_ptr->decl_scope == FILE_SCOPE_NUMBER) {
            /* The hidden symbol is file-scope entity.  It can be unhidden by
               global qualification ("::"). */
            record_defeatable_name_hiding(old_sym_ptr,
                                          /*tag_hidden_by_nontag=*/FALSE, sp);
          }  /* if */
        }  /* for */
      } else if (scope_depth == DEPTH_OF_FILE_SCOPE) {
        /* If the current declaration is hidden by a previous declaration of a
           class member, record that, too. */
        check_for_tag_sym = is_tag_symbol(sym_ptr);
        for (old_sym_ptr = sym_ptr->header->inactive_symbols;
             old_sym_ptr != NULL;
             old_sym_ptr = old_sym_ptr->next) {
          class_type = old_sym_ptr->class_of_which_a_member;
          if (class_type != NULL) {
            sp = class_type->
                    variant.class_struct_union.extra_info->assoc_scope;
            if (sp == NULL) {
              /* This can happen if a name is a member of class that is
                 a template parameter -- e.g.,
                   template <class T> void f(T t, T::S s) { ... }
                 In such a case, a class type for T is created to serve as the
                 parent for S but it is undefined.  A similar case occurs with
                 friend declarations withing a class template:
                   template <class T> class A {
                     friend void T::f();
                   };
              */
            } else {
              if (check_for_tag_sym && !is_tag_symbol(old_sym_ptr)) {
                record_defeatable_name_hiding(sym_ptr,
                                              /*tag_hidden_by_nontag=*/TRUE,
                                              sp);
              }  /* if */
              record_defeatable_name_hiding(sym_ptr,
                                            /*tag_hidden_by_nontag=*/FALSE,
                                            sp);
            }  /* if */
          }  /* if */
        }  /* for */
      }  /* if */
    }  /* if */
  }  /* if */
#endif /* RECORD_HIDDEN_NAMES_IN_IL */
}  /* record_symbol_declaration */


void record_symbol_reference(a_symbol_reference_kind kind,
                             a_symbol_ptr            sym_ptr,
                             a_source_position       *source_position,
                             a_boolean               update_il_entry)
/*
Record a reference of the indicated kind to the indicated symbol.  Set the
referenced flag in the symbol entry.  If update_il_entry is TRUE, also
set the referenced flag in the associated IL entry, if any.  Mark the
symbol "used" or "set", if appropriate.
*/
{
  a_source_correspondence *scptr;
  a_symbol_kind           sym_kind = sym_ptr->kind;
 
  /* If writing cross-reference information, write an entry for this
     declaration. */
  if (f_xref_info != NULL) {
    a_symbol_ptr             sym_for_xref = sym_ptr;
    a_symbol_reference_kind  kind_for_xref = kind;
    a_type_ptr               tp;

    if (sym_kind == (a_symbol_kind)sk_type) {
      if (sym_ptr->is_template_param) {
        /* A reference to a template parameter during template instantiation is
           actually a reference to the template argument that it represents. */
        tp = sym_ptr->variant.type;
        if (tp->kind == (a_type_kind)tk_template_param) {
          /* We are in the midst of a template definition. */
        } else {
          /* We are in the midst of a template instantiation. */
          for(;;) {
            if (tp->kind == (a_type_kind)tk_typeref) {
              if (tp->variant.typeref.is_const ||
                  tp->variant.typeref.is_volatile) {
                tp = tp->variant.typeref.type;
              } else {
                sym_for_xref = (a_symbol_ptr)tp->source_corresp.assoc_info;
                check_assertion(sym_for_xref != NULL);
                kind_for_xref |= SRK_IMPLICIT_TEMPLATE_ARG;
                break;
              }  /* if */
            } else if (is_array_type(tp)) {
              tp = array_element_type(tp);
            } else if (is_ptr_or_ref_type(tp)) {
              tp = type_pointed_to(tp);
            } else {
              break;
            }  /* if */
          }  /* for */
        }  /* if */
      }  /* if */
    } else if (is_class_symbol(sym_ptr)) {
      tp = type_symbol_type(sym_ptr);
      if (is_immediate_class_type(tp) &&
          sym_ptr->class_of_which_a_member == NULL) {
        a_class_symbol_supplement_ptr  cssp;
        cssp = sym_ptr->variant.class_struct_union.extra_info;
        if (cssp->is_prototype_instantiation) {
          /* A reference to a top-level prototype instantiation (i.e., not a
             nested class) is put out as a reference to the template itself. */
          sym_for_xref = cssp->class_template;
          check_assertion(sym_for_xref != NULL);
        }  /* if */
      }  /* if */
    }  /* if */
    write_xref_entry(kind_for_xref, sym_for_xref, source_position);
  }  /* if */
  /* Set the referenced flag in the symbol. */
  sym_ptr->referenced = TRUE;
  scptr = source_corresp_entry_for_symbol(sym_ptr);
  if (update_il_entry && scptr != NULL) {
    /* Set the referenced flag in the associated intermediate language entry,
       if there is one.  Note that more than one symbol can point to the same
       IL entry.  Use the fact that all the IL tables begin with
       a_source_correspondence. */
    /* If the symbol is for a virtual function, do not set the IL referenced
       flag; a reference to the symbol is not necessarily a reference to the
       corresponding IL entry.  When it is, the flag is set explicitly
       elsewhere. */
    if (sym_kind == (a_symbol_kind)sk_member_function &&
        sym_ptr->variant.routine.ptr->is_virtual) {
      /* Do not set IL referenced flag. */
    } else {
      scptr->referenced = TRUE;
    }  /* if */
  }  /* if */
  if (update_il_entry && (kind & SRK_ADDRESS_TAKEN)) {
    /* Set the address_taken flag in variables and routines. */
    if (sym_kind == (a_symbol_kind)sk_variable) {
      sym_ptr->variant.variable.ptr->address_taken = TRUE;
    } else if (sym_kind == (a_symbol_kind)sk_static_data_member) {
      sym_ptr->variant.static_data_member.variable->address_taken = TRUE;
    } else if (sym_kind == (a_symbol_kind)sk_routine ||
               sym_kind == (a_symbol_kind)sk_member_function) {
      sym_ptr->variant.routine.ptr->address_taken = TRUE;
    }  /* if */
  }  /* if */
  if (sym_kind == (a_symbol_kind)sk_variable) {
    /* If this reference is a use or, by taking the variable's address, a
       potential use, mark the variable has having been used.  Note that for
       an error reference, the variable is marked as being both set
       and modified, to keep diagnostics from being issued down the road; nor
       are diagnostics issued here. */
    if ((kind & SRK_USE) || (kind & SRK_ADDRESS_TAKEN) || (kind & SRK_ERROR)) {
      if (sym_ptr->variant.variable.used) {
        /* This is not the first use. */
        a_variable_ptr  vp = sym_ptr->variant.variable.ptr;
        if (vp->is_parameter || vp->is_handler_param) {
          /* Mark the parameter as multiply used (information that may be
             useful for inlining). */
          vp->param_used_more_than_once = TRUE;
        }  /* if */
      } else {
        /* This is the first use of the variable. */
        if (!sym_ptr->variant.variable.value_has_been_set &&
            !suppress_used_before_set_warnings && (kind & SRK_USE)) {
          /* But its value has not been set yet.  Issue a warning, if
             appropriate. */
          a_boolean                suppress_warning = FALSE;
          a_scope_stack_entry_ptr  ssep;

          /* To determine whether to suppress the warning, examine the scope
             stack for labels and uncompleted loops that might enable the
             program to set the variable in code that has not yet been seen
             and then to branch back to the current code.  In other words,
             only issue a warning if we're sure the variable cannot have
             been set. */
          for (ssep = &scope_stack[decl_scope_level]; ; --ssep) {
            check_assertion(ssep != &scope_stack[0]);
            if (ssep->kind == (a_scope_kind)sck_function) {
              /* A reference to a local variable from within quasi-nested
                 function definition should have been reported as an error and
                 recorded as an srk_error reference. */
              check_assertion(ssep->number == sym_ptr->decl_scope ||
                              !scptr->is_local_to_function);
              /* We are at the outermost scope of the function.  Check for
                 a label. */
              goto check_label_decl_seq;
            } else if (ssep->number == sym_ptr->decl_scope) {
              /* We are at the scope in which the variable was declared.
                 Jump out to the function scope and look for a label. */
              ssep = &scope_stack[depth_innermost_function_scope];
check_label_decl_seq:
              /* If the variable was declared before the label, suppress the
                 warning.  If it was declared after the label, the warning
                 is appropriate.  For example:
                   void f() {
                     int i;
                       :
                   L:
                     int j;
                     ++i;          // No warning -- i may be set later.
                     ++j;          // Warning -- j cannot have been set yet.
                         :
                   }
              */
              if (ssep->last_label_decl_seq > sym_ptr->decl_seq) {
                /* Variable was declared before the label was defined. */
                suppress_warning = TRUE;
              }  /* if */
              break;
            } else if (ssep->is_loop_scope) {
              /* The variable was declared in a scope outside the loop
                 scope, so suppress the warning.  If it were declared within
                 the loop, the warning would still be okay.  For example:
                   void f() {
                     int i;
                       :
                     for (;;) {
                       int j;
                       ++i;        // No warning -- i may be set later.
                       ++j;        // Warning -- j cannot have been set yet.
                         :
                     }
                   }
              */
              suppress_warning = TRUE;
              break;
            }
          }  /* for */
          if (!suppress_warning) {
            pos_sy_warning(ec_used_before_set, source_position, sym_ptr);
          }  /* if */
        }  /* if */
        sym_ptr->variant.variable.used = TRUE;
        if (scptr != NULL) {
          /* The variable may point to a different symbol in cases like
             this:
               static int i = 1;
               int f() { extern int i; return i; }
             and it is necessary for the file-scope symbol to be marked
             "used" too. */
          if ((a_symbol_ptr)scptr->assoc_info != sym_ptr) {
            ((a_symbol_ptr)scptr->assoc_info)->variant.variable.used = TRUE;
          }  /* if */
        }  /* if */
      }  /* if */
    }  /* if */
    /* If this reference involves a modification or, by taking the variable's
       address, a potential modification, mark the variable as having its
       value set. */
    if ((kind & SRK_MODIFICATION) || (kind & SRK_ADDRESS_TAKEN) ||
        (kind & SRK_ERROR)) {
      mark_variable_value_set(sym_ptr);
    }  /* if */
  }  /* if */
}  /* record_symbol_reference */


void reference_to_invalid_name(a_symbol_locator *locator)
/*
A name was referred to in a declaration but was invalid -- either it was
undefined or it was not being used correctly.  Put out cross reference
information on the reference, if required.
*/
{
  a_symbol_locator  loc;

  if (f_xref_info != NULL) {
    loc = *locator;
    if (loc.specific_symbol == NULL && !is_error_locator(loc)) {
      make_specific_symbol_error_locator(&loc);
    }  /* if */
    write_xref_entry(SRK_ERROR | SRK_REFERENCE, loc.specific_symbol,
                     &loc.source_position);
  }  /* if */
}  /* reference_to_invalid_name */


#if !GENERATE_SOURCE_SEQUENCE_LISTS
/*ARGSUSED*/ /* aap is used only when a source sequence entry is created. */
#endif /* !GENERATE_SOURCE_SEQUENCE_LISTS */
void record_access_adjustment(an_access_adjustment_ptr  aap,
                              a_symbol_ptr              sym,
                              a_source_position         *pos)
/*
aap points to an access-adjustment entry created to represent the an
access adjustment declaration of the inherited member sym.  If appropriate,
update the cross reference and source sequence output.
*/
{
  /* Update the cross reference file if it exists. */
  if (f_xref_info != NULL) {
    /* If writing cross-reference information, write an entry for this
       declaration. */
    write_xref_entry(SRK_DECLARATION, sym, pos);
  }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  update_source_sequence_list((char *)aap,
                              (an_il_entry_kind)iek_access_adjustment,
                              (a_source_sequence_entry_ptr)NULL);
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
}  /* record_access_adjustment */

static a_boolean is_cfront_base_class_destructor_access_bug(
                                                a_symbol_ptr   sym,
                                                a_routine_ptr  rp,
                                                a_type_ptr     class_of_object)
/*
Cfront has a bug in which a private destructor in a base class can be
called when the derived class really should not have access to it.
This function, which should only be called in cfront mode, detects
the condition in which the access error should be suppressed.
*/
{
  a_boolean  result = FALSE;
  if (rp->special_kind == (a_special_function_kind)sfk_destructor &&
      sym->class_of_which_a_member != class_of_object &&
      class_of_object != NULL) {
    result = TRUE;
  }  /* if */
  return result;
}  /* is_cfront_base_class_destructor_access_bug */


void reference_to_implicitly_invoked_function
                                (a_symbol_ptr       sym,
                                 a_source_position  *pos,
                                 a_type_ptr         class_of_object,
                                 a_boolean          honor_virtual,
                                 a_boolean          evaluated,
                                 a_boolean          suppress_access_check)
/*
sym is points to a symbol for a special member function that is invoked
implicitly -- e.g., a copy constructor that is called when a class
object is passed by value or an assignment operator that is called when
another assignment operator function is being created.  Check that the
special member function is accessible and mark the routine entry
referenced.  *pos gives the source position of the reference.
class_of_object points to the type of the object for which the function
is being called, which is not always the same as the class of which the
function is a member.  This is used to check protected member access
which only applies to objects of a derived class.  class_of_object may
be NULL if protected member access checking is not needed.  Also, if the
routine is compiler generated, it may still need to be defined, since
the definition may have been put off until an actual reference occurred
(e.g., ARM 12.8).  This function deals with implicitly called
constructors, destructors, assignment operators, and conversion
functions.  If honor_virtual is TRUE, and the function is virtual, the
reference is considered to be a virtual call; that means the access
control checking is done, but the IL entry is not marked as referenced.
If evaluated is FALSE, the reference is within an unevaluated
expression; again, access control checking is done, but the IL entry is
not marked as referenced.  If suppress_access_check is TRUE, no access
control checking is done.
*/
{
  a_routine_ptr rp = sym->variant.routine.ptr;

  check_assertion(rp->special_kind ==
                               (a_special_function_kind)sfk_constructor ||
                  rp->special_kind ==
                               (a_special_function_kind)sfk_destructor ||
                  rp->special_kind ==
                               (a_special_function_kind)sfk_conversion ||
                  (rp->special_kind == (a_special_function_kind)sfk_operator &&
                   rp->opname_kind == (an_opname_kind)onk_assign));
  if (!suppress_access_check) {
    /* Check for accessibility. */
    if (!have_access_to_symbol(sym)) {
      an_error_severity  severity = es_error;
      /* Normally an error, but in cfront mode there is a special case
         involving a private base class destructor where we issue a warning. */
      if (any_cfront_mode() &&
          is_cfront_base_class_destructor_access_bug(sym, rp,
                                                     class_of_object)) {
        severity = es_warning;
      }  /* if */
      pos_sy_diagnostic(severity, ec_inaccessible_special_function,
                        pos, sym);
    } else if (class_of_object != NULL) {
      /* Protected members of a base class can only be accessed through an
         object of a derived class. */
      check_protected_member_access(sym, pos, class_of_object);
    }  /* if */
  }  /* if */
  /* Update the symbol and the cross-reference listing. */
  record_symbol_reference((SRK_REFERENCE | SRK_IMPLICIT), sym, pos,
                          /*update_il_entry=*/FALSE);
  if (!evaluated) {
    /* Unevaluated expression.  Do not set the IL referenced flag. */
  } else if (rp->is_virtual && honor_virtual) {
    /* Virtual function call.  Do not set the IL referenced flag because the
       call might actually be of an overriding function. */
  } else {
    /* Non-virtual call. */
    mark_routine_referenced(rp);
  }  /* if */
}  /* reference_to_implicitly_invoked_function */


/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-1994 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
