/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-1994 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
/*

symbol_ref.c - Routines to manage references to symbols.

*/

/* Header files common to all files. */
#include "fe_common.h"

#ifdef PCH_PRAGMA_GUARD
/* Mark the end of the sequence of headers subject to precompiled header
   processing. */
#pragma hdrstop
#endif /* ifdef PCH_PRAGMA_GUARD */

/* Additional header files. */
#include "symbol_ref.h"


static an_il_to_str_output_control_block
		octl;
			/* Output control block used to interface to the
			   il_to_str routines. */

static a_boolean
		output_control_block_has_been_set_up = FALSE;
			/* Flag that indicates whether initialization has
			   already been done on the output control block. */

static void write_string_to_xref_file(char *str)
/*
Write str to the xref file.  The address of this routine is passed to
the il_to_str routines for generating formatted names.
*/
{
  (void)fputs(str, f_xref_info);
}  /* write_string_to_xref_file */


static void write_xref_entry(a_symbol_reference_kind srk_flags,
                             a_symbol_ptr            sym_ptr,
                             a_source_position       *source_position)
/*
Write information to f_xref_info describing a reference of kind "kind"
to symbol "sym_ptr" at source position "source_position".  This routine
should only be called if cross-reference information is being generated
(i.e., f_xref_info != NULL).
*/
{
  char              code;
  char              *file_name, *full_name;
  a_line_number     line_number;
  a_boolean         at_end_of_source;

  if (!output_control_block_has_been_set_up) {
    /* Set octl so that it can be passed into the il_to_str routines to tell
       them how to write a string to the xref file. */
    clear_il_to_str_output_control_block(&octl);
    octl.output_str = write_string_to_xref_file;
    output_control_block_has_been_set_up = TRUE;
  }  /* if */
  if (sym_ptr->kind == (a_symbol_kind)sk_extern_variable ||
             sym_ptr->kind == (a_symbol_kind)sk_extern_routine) {
    /* Ignore extern variable and routine symbols.  They are really just
       shadow symbols for the real ones. */
  } else if (is_unnamed_tag_symbol(sym_ptr)) {
    /* Ignore symbols for unnamed classes and enums. */
  } else if (source_position->seq == 0) {
    /* This symbol is not associated with any particular source position. */
  } else if (depth_innermost_instantiation_scope != NO_SCOPE_DEPTH &&
             (sym_ptr->is_template_param ||
              scope_stack[depth_scope_stack].in_prototype_instantiation)) {
    /* Ignore template parameter symbols encountered during template
       instantiation and any symbols encountered during prototype
       instantiation. */
  } else {
    /* The record written to the file is a text line that looks like

       symbol-id name X file-name line-number column-number

       The separator character between the fields is a horizontal tab.
       where X is "d" for declaration,
                  "D" for definition,
                  "M" for modification,
                  "A" for address taken,
                  "U" for use,
                  "C" for changed (i.e., used and modified in one
                      operation, such as an increment operation),
                  "R" for generic reference, or
                  "E" for error.
       The symbol-id is a unique number for the symbol, generated by 
       casting the symbol pointer to unsigned long.
    */
    if (srk_flags & SRK_DECLARATION) {
      if (srk_flags & SRK_DEFINITION) {
        code = 'D';
      } else {
        code = 'd';
      }  /* if */
    } else if (srk_flags & SRK_REFERENCE) {
      if (srk_flags & SRK_USE) {
        if (srk_flags & SRK_MODIFICATION) {
          code = 'C';
        } else {
          code = 'U';
        }  /* if */
      } else if (srk_flags & SRK_MODIFICATION) {
        code = 'M';
      } else if (srk_flags & SRK_ADDRESS_TAKEN) {
        code = 'A';
      } else if (srk_flags & SRK_ERROR) {
        code = 'E';
      } else {
        code = 'R';
      }  /* if */
#if CHECKING
    } else {
      internal_error("write_xref_entry: bad reference kind");
#endif /* CHECKING */
    }  /* if */
    /* Convert the source position to file name/line number. */
    conv_seq_to_file_and_line(source_position->seq, &file_name, &full_name,
                              &line_number, &at_end_of_source);
    fprintf(f_xref_info, "%lu\t", (unsigned long)sym_ptr);
    /* Write the symbol name, complete with class qualifier, etc., to the
       xref file. */
    form_symbol_name(sym_ptr, &octl);
    fprintf(f_xref_info, "\t%c\t%s\t%lu\t%d\n",
                         code,
                         file_name,
                         line_number,
                         source_position->column);
  }  /* if */
}  /* write_xref_entry */


void mark_variable_value_set(a_symbol_ptr  sym)
/*
Set the "value_has_been_set" flag of the variable symbol pointed to by sym.
*/
{
  check_assertion(sym->kind == (a_symbol_kind)sk_variable);
  if (sym->variant.variable.value_has_been_set) {
    /* Variable has already been set. */
    a_variable_ptr  vp = sym->variant.variable.ptr;
    if (vp->is_parameter || vp->is_handler_param) {
      /* Since parameters are by definition initialized (by the actual
         argument), any subsequent modification is a change to the initial
         value.  Knowing this can be useful for inlining. */
      vp->param_value_has_been_changed = TRUE;
    }  /* if */
  } else {
    sym->variant.variable.value_has_been_set = TRUE;
  }  /* if */
}  /* mark_variable_value_set */

#if RECORD_HIDDEN_NAMES_IN_IL

static a_boolean symbols_are_equivalent(a_symbol_ptr  sym1,
                                        a_symbol_ptr  sym2)
/*
Return TRUE if sym1 and sym2 point to the same IL entries.
*/
{
  an_il_entry_kind  kind;
  a_boolean         equiv = (sym1 == sym2);

  if (!equiv) {
    if (sym1->kind == sym2->kind) {
      char *entry1 = il_entry_for_symbol_null_okay(sym1, &kind);
      char *entry2 = il_entry_for_symbol_null_okay(sym2, &kind);
      if (entry1 == entry2 && entry1 != NULL) equiv = TRUE;
    }  /* if */
  }  /* if */
  return equiv;
}  /* symbols_are_equivalent */


static a_scope_ptr hidden_name_scope(void)
/*
Return the IL scope with which a hidden-name table entry should be associated.
*/
{
  a_scope_stack_entry_ptr  ssep;
  a_scope_ptr              sp;

  /* Get pointer to current scope entry. */
  ssep = &scope_stack[decl_scope_level];
  if (ssep->kind == (a_scope_kind)sck_pragma) --ssep;
  while (ssep->kind == (a_scope_kind)sck_template_declaration) {
    --ssep;
  }  /* while */
  /* Create the IL scope if necessary (for block scopes). */
  sp = ensure_il_scope_exists(ssep);
  check_assertion_str(sp != NULL, "hidden_name_scope: NULL IL scope");
  return sp;
}  /* hidden_name_scope */


static void record_hidden_template(
                              a_symbol_ptr  hidden_sym,
                              a_boolean     tag_hidden_by_nontag,
                              a_boolean     hidden_class_or_namespace_member,
                              a_scope_ptr   sp)
/*
A template name (indicated by hidden_sym) is hidden in the specified scope
by another declaration.  Record the fact in a fixup list that can be
checked later whenever a new instance of the template is generated.
*/
{
  a_template_symbol_supplement_ptr  tssp;
  a_hidden_template_name_fixup_ptr  htnfp;
  a_symbol_list_entry_ptr           slep;
  a_scope_stack_entry_ptr           ssep;

  check_assertion(is_template_symbol(hidden_sym));
  /* Add a fixup entry to a list in the template symbol supplement. */
  tssp = hidden_sym->variant.template_info;
  htnfp = alloc_hidden_template_name_fixup();
  htnfp->scope = sp;
  htnfp->tag_hidden_by_nontag = tag_hidden_by_nontag;
  htnfp->hidden_class_or_namespace_member = hidden_class_or_namespace_member;
  htnfp->next = tssp->hidden_name_fixup_list;
  tssp->hidden_name_fixup_list = htnfp;
  /* If this hiding occurs within the context of function definition, record
     the template in a list in the scope stack entry for the function.  Then
     when the function scope is popped, fixup entries associated with the
     function scope can be removed.  (This is required because the memory
     region to which the current IL scope entry points may no longer be
     valid once the function scope is popped.) */
  if (depth_innermost_function_scope != NO_SCOPE_DEPTH) {
    slep = alloc_symbol_list_entry();
    slep->symbol = hidden_sym;
    ssep = &scope_stack[depth_innermost_function_scope];
    /* Record the function scope in the fixup entry. */
    htnfp->assoc_function_scope = ssep->il_scope;
    /* Add the list entry to the front of the list. */
    slep->next = ssep->hidden_template_name_symbols;
    ssep->hidden_template_name_symbols = slep;
  }  /* if */
}  /* record_hidden_template */


static void record_defeatable_name_hiding(
                              a_symbol_ptr  hidden_sym,
                              a_boolean     tag_hidden_by_nontag,
                              a_boolean     hidden_class_or_namespace_member,
                              a_scope_ptr   sp,
                              a_symbol_ptr  hidden_by)
/*
hidden_sym is a symbol for an entity that is hidden by another declaration
of the same name -- but the hiding can be "defeated" by using an
elaborated type specifier or global qualification (preceding "::") when
referring to the hidden name.  Create the hidden-name entity to represent
this case and add it to the list for the current scope.  If hidden_by is
non-NULL, it points to the symbol that does the hiding; when hidden_sym
and hidden_by refer to the same IL entry, no hidden-name entry is produced.
*/
{
  a_hidden_name_ptr        hnp;
  char                     *entity;
  an_il_entry_kind         kind;
  a_symbol_ptr             sym;
  a_template_instance_ptr  tip;

  if (hidden_by != NULL && symbols_are_equivalent(hidden_sym, hidden_by)) {
    /* A symbol does not hide itself. */
  } else {
    switch (hidden_sym->kind) {
      case sk_label:
      case sk_keyword:
      case sk_macro:
      case sk_undefined:
      case sk_extern_variable:
      case sk_extern_routine:
        /* Not in the same name space. */
        break;
      case sk_overloaded_function:
        /* Enter members of an overload set separately. */
        if (sp == NULL) sp = hidden_name_scope();
        for (sym = hidden_sym->variant.overloaded_function.symbols;
             sym != NULL;
             sym = sym->next) {
          record_defeatable_name_hiding(sym, tag_hidden_by_nontag,
                                        hidden_class_or_namespace_member, sp,
                                        hidden_by);
        }  /* for */
        break;
      case sk_projection:
        if (!hidden_sym->synthesized_namespace_projection) {
          /* Ignore most projection symbols. */
          break;
        }  /* if */
        /* FALLTHROUGH */
      case sk_namespace_projection:
        /* Enter the fundamental symbol of a namespace projection. */
        sym = fundamental_symbol_of(hidden_sym);
        /* If the fundamental symbol belongs to the same namespace as the
           symbol it's hidden by (something that can happen with synthesized
           namespace projections), then the hiding cannot be defeated by a
           qualifier.  Check for that case. */
        if (hidden_class_or_namespace_member &&
            depth_innermost_function_scope == NO_SCOPE_DEPTH &&
            hidden_by != NULL && !hidden_by->is_class_member &&
            !sym->is_class_member &&
            sym->parent.namespace_ptr == hidden_by->parent.namespace_ptr) {
          /* Set hidden_class_or_namespace_member to FALSE. */
          hidden_class_or_namespace_member = FALSE;
          /* If they're both FALSE don't create a hidden name table entry. */
          if (!tag_hidden_by_nontag) break;
        }  /* if */
        record_defeatable_name_hiding(sym, tag_hidden_by_nontag,
                                      hidden_class_or_namespace_member,
                                      sp, hidden_by);
        break;
      case sk_class_template:
        /* Enter each instance of a class template. */
        if (sp == NULL) sp = hidden_name_scope();
        for (sym = hidden_sym->variant.template_info->
                                  variant.class_template.instantiations;
             sym != NULL;
             sym = next_instance_sym(sym)) {
          if (!sym->variant.class_struct_union.extra_info->is_nonreal_class) {
            record_defeatable_name_hiding(sym, tag_hidden_by_nontag,
                                          hidden_class_or_namespace_member, sp,
                                          hidden_by);
          }  /* if */
        }  /* for */
        /* Add a fixup entry for the template, so that hidden name table
           entries can be added for instances that are created later. */
        record_hidden_template(hidden_sym, tag_hidden_by_nontag,
                               hidden_class_or_namespace_member, sp);
        break;
      case sk_function_template:
        /* Enter each instance of a function template. */
        if (sp == NULL) sp = hidden_name_scope();
        for (tip = hidden_sym->variant.template_info->
                                  variant.function.instantiations;
             tip != NULL;
             tip = tip->next) {
          if (tip->is_guiding_decl) {
            /* Ignore guiding declarations -- they will have been picked up
               elsewhere. */
          } else {
            record_defeatable_name_hiding(tip->instance_sym,
                                          tag_hidden_by_nontag,
                                          hidden_class_or_namespace_member, sp,
                                          hidden_by);
          }  /* if */
        }  /* for */
        break;
      default:
        /* The normal case.  First find the entity associated with the
           symbol. */
        entity = il_entry_for_symbol(hidden_sym, &kind);
        if (sp == NULL) sp = hidden_name_scope();
        /* If there is already a hidden name entry for this entity in this
           scope, reuse it. */
        for (hnp = sp->hidden_names; hnp != NULL; hnp = hnp->next) {
          if (hnp->entity.ptr == entity) break;
        }  /* for */
#if DEBUG
        if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
          if (hnp == NULL ||
              ((tag_hidden_by_nontag &&
                !hnp->elaborated_type_specifier_needed) ||
               (hidden_class_or_namespace_member &&
                !hnp->qualification_needed))) {
            a_source_correspondence  *scp =
                                   source_corresp_for_il_entry(entity, kind);
            fputs("    in ", f_debug);
            db_scope(sp);
            fputs(": use", f_debug);
            if (hidden_class_or_namespace_member) {
              fputs(" qualifier", f_debug);
              if (tag_hidden_by_nontag) fputs(" and", f_debug);
            }  /* if */
            if (tag_hidden_by_nontag) fputs(" class-key", f_debug);
            fputs(" for \"", f_debug);
            if (kind == (an_il_entry_kind)iek_type) {
              db_abbreviated_type((a_type_ptr)entity);
            } else {
              if (scp != NULL) {
                db_name(scp);
                if (kind == (an_il_entry_kind)iek_routine) {
                  db_function_param_list(((a_routine_ptr)entity)->type);
                }  /* if */
              } else {
                fprintf(f_debug, "\?\?\?");
              }  /* if */
            }  /* if */
            fprintf(f_debug, "\"%s", hnp == NULL ? "" : " [modif]");
            fprintf(f_debug, "\n");
          }  /* if */
        }  /* if */
#endif /* DEBUG */
        if (hnp == NULL) {
          /* No existing entry.  Allocate a new one. */
          a_scope_depth           scope_depth;
          a_memory_region_number  region_to_switch_back_to;
           /* Get the scope depth from which to determine the appropriate
             memory region in which to allocate the hidden-name entry. */
          if (in_file_scope(sp)) {
            scope_depth = DEPTH_OF_FILE_SCOPE;
          } else {
            scope_depth = sp->depth_in_scope_stack;
            check_assertion(scope_depth != NO_SCOPE_DEPTH);
          }  /* if */
          switch_to_scope_region(scope_depth, &region_to_switch_back_to);
          hnp = alloc_hidden_name();
          switch_back_to_original_region(region_to_switch_back_to);
          hnp->entity.ptr = entity;
          hnp->entity.kind = (a_byte_il_entry_kind)kind;
          /* Add it to the start of the hiden_names list for the current
             scope. */
          hnp->next = sp->hidden_names;
          sp->hidden_names = hnp;
        }  /* if */
        /* Set the appropriate flag. */
        if (tag_hidden_by_nontag) {
          check_assertion(kind == (an_il_entry_kind)iek_type);
          hnp->elaborated_type_specifier_needed = TRUE;
        }  /* if */
        if (hidden_class_or_namespace_member) {
          check_assertion(in_file_scope(entity));
          hnp->qualification_needed = TRUE;
        }  /* if */
        break;
    }  /* switch */
  }  /* if */
}  /* record_defeatable_name_hiding */


void record_name_hiding_for_template_instance(
                                    a_symbol_ptr                      sym_ptr,
                                    a_template_symbol_supplement_ptr  tssp)
/*
An instance of a template has been generated.  Hidden name table entries
may be required for it in scopes where the template name is hidden by
another declaration.  The instance is indicated by sym_ptr; the template
of which it is an instance is represented by the specified template symbol
supplement.  Check the fixup list associated with the template and update
the hidden name table for each entry on the list.
*/
{
  a_hidden_template_name_fixup_ptr  htnfp;

  if (tssp != NULL) {
    htnfp = tssp->hidden_name_fixup_list;
#if DEBUG
    if (htnfp != NULL) {
      if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
        fputs("Deferred hidden name record: ", f_debug);
        db_symbol_name(sym_ptr);
        fputc('\n', f_debug);
      }  /* if */
    }  /* if */
#endif /* DEBUG */
    for (; htnfp != NULL; htnfp = htnfp->next) {
      if (htnfp->scope->kind == (a_scope_kind)sck_block &&
          htnfp->scope->depth_in_scope_stack == NO_SCOPE_DEPTH) {
        continue;
      }  /* if */
      record_defeatable_name_hiding(sym_ptr, htnfp->tag_hidden_by_nontag,
                                    htnfp->hidden_class_or_namespace_member,
                                    htnfp->scope, (a_symbol_ptr)NULL);
    }  /* for */
  }  /* if */
}  /* record_name_hiding_for_template_instance */


static void add_to_hidden_name_fixup_list(a_symbol_ptr  sym_ptr)
/*
Create a symbol-list entry for sym_ptr and add it to the hidden-name fixup
list for the scope to which sym_ptr belongs.
*/
{
  a_scope_depth               depth;
  a_boolean                   is_local_to_function;
  a_namespace_ptr             nsp;
  a_symbol_list_entry_ptr     slep;
  a_scope_pointers_block_ptr  pointers_block;

  check_assertion(!sym_ptr->is_class_member);
  nsp = sym_ptr->parent.namespace_ptr;
  if (nsp != NULL) {
    pointers_block = &symbol_supplement_for_namespace(nsp)->pointers_block;
  } else {
    depth = scope_depth_of_symbol(sym_ptr, &is_local_to_function);
    if (depth == NO_SCOPE_DEPTH) {
      pointers_block = NULL;
    } else {
      pointers_block = assoc_pointers_block_of(&scope_stack[depth]);
    }  /* if */
  }  /* if */
  if (pointers_block != NULL) {
#if DEBUG
    if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
      fputs("Deferring hidden name check: ", f_debug);
      db_symbol_name(sym_ptr);
      fputc('\n', f_debug);
    }  /* if */
#endif /* DEBUG */
    slep = alloc_symbol_list_entry();
    slep->symbol = sym_ptr;
    slep->next = pointers_block->hidden_name_fixup_list;
    pointers_block->hidden_name_fixup_list = slep;
  }  /* if */
}  /* add_to_hidden_name_fixup_list */


void check_hidden_name_fixup_list(a_symbol_list_entry_ptr  *list)
/*
Do the defeatable-name-hiding check for each symbol on the symbol-list and
then free the list.
*/
{
  a_symbol_list_entry_ptr  slep;

  if (*list != NULL) {
    for (slep = *list; slep != NULL; slep = slep->next) {
      check_for_defeatable_name_hiding(slep->symbol);
    }  /* for */
    free_list_of_symbol_list_entries(*list);
    *list = NULL;
  }  /* if */
}  /* check_hidden_name_fixup_list */


static a_boolean matches_member_of_overload_set(a_symbol_ptr  sym_ptr,
                                                a_symbol_ptr  overload_sym)
/*
Return TRUE if sym_ptr refers to the same routine as overload_sym or
refers to the same entity as a member of the overload set headed by
overload_sym.  Also, return TRUE if sym_ptr is an instance of a template
pointed to by overload_sym or a template that is a member of the overload
set pointed to by overload_sym.
*/
{
  a_boolean     found = FALSE;
  a_boolean	is_list;
  a_symbol_ptr  other_sym;

  if (overload_sym->kind == (a_symbol_kind)sk_overloaded_function) {
    is_list = TRUE;
    other_sym = overload_sym->variant.overloaded_function.symbols;
  } else {
    is_list = FALSE;
    other_sym = overload_sym;
  }  /* if */
  for (; other_sym != NULL; other_sym = is_list ? other_sym->next : NULL) {
    if (symbols_are_equivalent(sym_ptr, other_sym)) {
      found = TRUE;
      break;
    }  /* if */
    if (other_sym->kind == (a_symbol_kind)sk_function_template &&
        (sym_ptr->kind == (a_symbol_kind)sk_routine ||
         sym_ptr->kind == (a_symbol_kind)sk_member_function) &&
        sym_ptr->variant.routine.instance_ptr != NULL &&
        sym_ptr->variant.routine.instance_ptr->template_sym == other_sym) {
      /* The function is an instance of the template specified by other_sym. */
      found = TRUE;
      break;
    }  /* if */
  }  /* for */
  return found;
}  /* matches_member_of_overload_set */


static a_boolean is_member_of_inactive_local_class(a_symbol_ptr  member_sym)
/*
Return TRUE if the symbol passed in is a member of a class local to a
function that is no longer active.  (This is necessary because the member
symbol remains on the inactive list even after its class disappears from
the symbol table.)
*/
{
  a_boolean     match = FALSE;
  a_type_ptr    tp;
  a_symbol_ptr  class_sym, sym;

  if (member_sym->is_class_member) {
    tp = member_sym->parent.class_type;
    if (tp->source_corresp.is_local_to_function) {
      /* It's a member of an local class.  Find the outer-most class in case
         the member belongs to a nested class. */
      while (tp->source_corresp.is_class_member) {
        tp = tp->source_corresp.parent.class_type;
      }  /* while */
      /* See if the class is still in scope. */
      class_sym = (a_symbol_ptr)tp->source_corresp.assoc_info;
      for (sym = class_sym->header->symbol; sym != NULL; sym = sym->next) {
        if (sym == class_sym) break;
      }  /* for */
      /* No symbol for the class was found on the active list, so the scope
         in which the class was declared is no longer active. */
      if (sym == NULL) match = TRUE;
    }  /* if */
  }  /* if */
  return match;
}  /* is_member_of_inactive_local_class */


static a_boolean is_potentially_hidden_by(a_symbol_ptr  sym1,
                                          a_symbol_ptr  sym2)
/*
Return TRUE if the declaration of sym1 is potentially hidden by the
declaration of sym2 -- that is, if a lookup of sym1 from a scope
to which sym2 belongs (or a scope nested therein) will fail to find
sym1 because it is hidden by sym2.
*/
{
  a_boolean        is_potentially_hidden = FALSE;
  a_type_ptr       curr_parent_class, tp;
  a_namespace_ptr  curr_namespace, nsp;

  if (is_member_of_inactive_local_class(sym2)) {
    /* is_potentially_hidden = FALSE; */
  } else if (sym1->decl_scope == FILE_SCOPE_NUMBER) {
    if (sym2->decl_scope != FILE_SCOPE_NUMBER) {
      /* sym2 belongs to a scope that is enclosed within the file scope
         (the scope to which sym1 belongs) -- so sym1 is potentially hidden
         by sym2. */
      is_potentially_hidden = TRUE;
    }  /* if */
  } else if (sym1->is_class_member) {
    if (!sym2->is_class_member) {
#if 0
/* What if sym2 is inside a member function body? */
#endif /* if */
      /* is_potentially_hidden = FALSE; */
    } else {
      tp = sym2->parent.class_type;
      curr_parent_class = sym1->parent.class_type;
      if (tp == curr_parent_class) {
        /* sym1 and sym2 are members of the same class. */
      } else {
        do {
          if (find_base_class_of(tp, curr_parent_class) != NULL) {
            /* The class to which sym2 belongs is (or is nested within a
               class that is) derived from the class to which sym1 belongs --
               so sym1 is potentially hidden by sym2. */
            is_potentially_hidden = TRUE;
          } else if (!tp->source_corresp.is_class_member) {
            break;
          } else {
            tp = tp->source_corresp.parent.class_type;
            if (tp == curr_parent_class) {
              /* The class to which sym2 belongs is nested within that of
                 sym1 -- so sym1 is potentially hidden by sym2. */
              is_potentially_hidden = TRUE;
            }  /* if */
          }  /* if */
        } while (!is_potentially_hidden);
      }  /* if */
    }  /* if */
  } else {
    /* sym1 is not a class member.  It may be a namespace member. */
    curr_namespace = sym1->parent.namespace_ptr;
    if (curr_namespace != NULL) {
      /* See if the namespace to which sym2 belongs (if any) is nested
         within that of sym1. */
      nsp = parent_namespace_for_symbol(sym2);
      if (nsp == curr_namespace) {
        /* They belong to the same namespace. */
        if (sym2->is_class_member) {
          /* sym2 is in a class that is nested within the namespace to which
             sym1 belongs -- so sym1 is potentially hidden by sym2. */
          is_potentially_hidden = TRUE;
        }  /* if */
      } else {
        while (nsp != NULL) {
          nsp = skip_namespace_aliases(nsp);
          if (nsp == curr_namespace) {
            /* sym2 is in a namespace that is nested within the namespace to
               which sym1 belongs -- so sym1 is potentially hidden by sym2. */
            is_potentially_hidden = TRUE;
            break;
          }  /* if */
          nsp = nsp->source_corresp.parent.namespace_ptr;
        }  /* while */
      }  /* if */
    }  /* if */
  }  /* if */
  return is_potentially_hidden;
}  /* is_potentially_hidden_by */


void check_for_defeatable_name_hiding(a_symbol_ptr  sym_ptr)
/*
Determine whether "defeatable hidden-name information" should be put out for
sym_ptr and/or other entities of the same name.  The generation of such
information is primarily for the C++ generating back end, so that it will
know to use elaborated type specifiers and/or :: qualification to defeat name
hiding.
*/
{
  a_symbol_locator         locator;
  a_symbol_ptr             old_sym_ptr;
  a_scope_ptr              sp;
  a_namespace_ptr          nsp;
  a_boolean                tag_hidden_by_nontag;
  a_boolean                hidden_class_or_namespace_member;
  a_scope_stack_entry_ptr  ssep = &scope_stack[depth_scope_stack];

  if (sym_ptr->is_error || total_errors > 0) {
    /* Ignore error symbols.  And if there is an error, don't bother with
       this processing, which can be costly. */
  } else if (decl_scope_level == depth_innermost_namespace_scope &&
             sym_ptr->is_class_member) {
    /* Ignore member definitions outside the class definition. */
  } else if (sym_ptr->kind == (a_symbol_kind)sk_parameter) {
    /* Ignore parameter symbols.  The only parameters that are interesting
       are the ones that have been turned into variables. */
  } else if (is_unnamed_tag_symbol(sym_ptr)) {
    /* No name hiding for unnamed entities. */
  } else if (sym_ptr->is_invisible) {
    /* Ignore invisible names. */
  } else if ((depth_template_declaration_scope != NO_SCOPE_DEPTH ||
              ssep->in_prototype_instantiation) &&
             sym_ptr->kind == (a_symbol_kind)sk_class_template) {
    /* We don't deal with class template definitions. */
  } else if (sym_ptr->is_class_member &&
             symbol_supplement_for_class(sym_ptr->parent.class_type)->
                                                          is_nonreal_class) {
    /* Ignore members of prototype instantiations. */
  } else if (sym_ptr->is_template_param) {
    /* Ignore template parameters. */
  } else if (sym_ptr->kind == (a_symbol_kind)sk_macro) {
    /* Ignore macros. */
  } else if (ssep->kind == (a_scope_kind)sck_template_instantiation) {
    /* Ignore template instantiation scopes. */
  } else if (is_template_class_symbol(sym_ptr)) {
    /* Ignore template class specializations. */
  } else if (!sym_ptr->is_class_member &&
             ssep->kind == (a_scope_kind)sck_class_struct_union &&
             sym_ptr->decl_scope != FILE_SCOPE_NUMBER &&
             (ssep->il_scope->
                   variant.assoc_type->source_corresp.is_local_to_function ||
              depth_innermost_namespace_scope != DEPTH_OF_FILE_SCOPE)) {
    /* We are inside a local class or namespace member class and a name is
       introduced (e.g., by a friend declaration) and injected into an
       enclosing scope.  Put the symbol on a fixup list and process it once
       we pop out to that scope. */
    add_to_hidden_name_fixup_list(sym_ptr);
  } else {
#if DEBUG
    if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
      if (sym_ptr->decl_position.seq) {
        fputs("Hidden name check: ", f_debug);
        fprintf(f_debug, "<%s> ", symbol_kind_names[(int)sym_ptr->kind]);
        db_symbol_name(sym_ptr);
        fputc('\n', f_debug);
      }  /* if */
    }  /* if */
#endif /* DEBUG */
    clear_locator(&locator, &sym_ptr->decl_position);
    locator.symbol_header = sym_ptr->header;
    /* Determine what declarations are hidden by the current declaration. */
    /* First check for hiding that can be resolved with an elaborated type
       specifier -- e.g., when the current declaration is a non-tag name that
       hides a tag name in the same or an enclosing scope and when the current
       declaration is a tag name that is hidden by a non-tag name in the
       current scope. */
    if (is_injected_class_symbol(sym_ptr)) {
      /* Ignore it. */
    } else if (!is_tag_symbol(sym_ptr)) {
      /* The current declaration is of something other than a tag name.
         If it hides a tag in the same scope or an enclosing scope, an
         elaborated type specifier can render the tag visible.  For example:
           class x;
           int x = 1;                   // class x is hidden at file scope
           class y;
           void f() {
             int y = 1;                 // class y is hidden in function f
           }
         An elaborated type specifier can be used to "defeat" the hiding. */
      /* Find the innermost tag declaration with the same name. */
      old_sym_ptr = normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP |
                                               IDL_MUST_BE_TAG);
      if (old_sym_ptr != NULL) {
        /* old_sym_ptr is a tag with the same name as sym_ptr and in the
           same or a containing scope. */
        if (sym_ptr->kind == (a_symbol_kind)sk_type &&
            typeref_is_typedef(sym_ptr->variant.type.ptr) &&
            skip_typerefs(sym_ptr->variant.type.ptr) ==
                            old_sym_ptr->variant.class_struct_union.type) {
          /* sym_ptr is a typedef that refers the type represented by
             old_sym_ptr -- something like "typedef struct S { ... } S;"
             There's no need to generate hidden-name info for this common
             construct. */
        } else if (old_sym_ptr->decl_scope != sym_ptr->decl_scope &&
                   (old_sym_ptr->is_class_member ||
                    old_sym_ptr->parent.namespace_ptr != NULL ||
                    old_sym_ptr->decl_scope == FILE_SCOPE_NUMBER)) {
          /* No need to defeat the name hiding with an elaborated type
             specifier -- the tag name will be qualified, either by its
             parent class or namespace or by a leading "::".  That's
             handled later. */
        } else {
          /* Either the two declarations are in the same scope or else
             old_sym_ptr cannot be qualified -- e.g., its containing scope is
             local to a function:
               void f() {
                 struct S { ... };
                 { int S; ... }     // S is hidden in the block scope
               }
          */
          tag_hidden_by_nontag = TRUE;
          hidden_class_or_namespace_member = FALSE;
          record_defeatable_name_hiding(old_sym_ptr, tag_hidden_by_nontag,
                                        hidden_class_or_namespace_member,
                                        (a_scope_ptr)NULL, sym_ptr);
        }  /* if */
      }  /* if */
    } else {
      /* This is a tag declaration, which would be hidden by any non-tag
         already declared within the current scope.  For instance:
           x = 1;
           class x;                 // class x is hidden at file scope
         Again, hiding can be defeated by using "class x" instead of "x". */
      old_sym_ptr = curr_scope_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
      if (old_sym_ptr == NULL) {
        /* Nothing to do. */
      } else if (is_class_template_symbol(old_sym_ptr) &&
                 is_template_class_symbol(sym_ptr) &&
                 sym_ptr->decl_scope == old_sym_ptr->decl_scope) {
        /* The other symbol is a class template symbol and sym_ptr is a
           template instance. */
      } else if (old_sym_ptr != sym_ptr) {
        tag_hidden_by_nontag = TRUE;
        hidden_class_or_namespace_member = FALSE;
        record_defeatable_name_hiding(sym_ptr, tag_hidden_by_nontag,
                                      hidden_class_or_namespace_member,
                                      (a_scope_ptr)NULL, old_sym_ptr);
      }  /* if */
    }  /* if */
    /* Now check for hiding that can be resolved by using a qualified name. */
    if (scope_stack[depth_scope_stack].kind ==
                            (a_scope_kind)sck_class_struct_union &&
        sym_ptr->decl_scope != scope_stack[depth_scope_stack].number) {
      /* A friend declaration.  Determine whether a qualifier is needed.
         It is needed if there is an intervening declaration (say, in an
         enclosing block scope) that hides the declaration. */
      check_assertion(!sym_ptr->is_class_member ||
                      sym_ptr->parent.class_type !=
                         scope_stack[depth_scope_stack].assoc_type);
      clear_specific_symbol(locator);
      old_sym_ptr = curr_scope_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
      if (old_sym_ptr != NULL) {
        /* Hidden by another declaration in the current scope. */
        hidden_class_or_namespace_member = TRUE;
      } else {
        hidden_class_or_namespace_member = FALSE;
        old_sym_ptr = normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
        if (old_sym_ptr != NULL) {
          if (old_sym_ptr == sym_ptr ||
              matches_member_of_overload_set(sym_ptr, old_sym_ptr)) {
            /* There is no intervening declaration of this name, or if there
               is it is a block-extern declaration that refers to the same
               entity. */
          } else if (is_class_struct_union_symbol(sym_ptr) &&
                     is_class_template_symbol(old_sym_ptr) &&
                     sym_ptr->variant.class_struct_union.
                                 extra_info->class_template == old_sym_ptr) {
            /* *sym_ptr is an instance of the class template that *old_sym_ptr
               represents. */
          } else {
            hidden_class_or_namespace_member = TRUE;
          }  /* if */
        }  /* if */
      }  /* if */
      if (hidden_class_or_namespace_member) {
        tag_hidden_by_nontag = FALSE;
        record_defeatable_name_hiding(sym_ptr, tag_hidden_by_nontag,
                                      hidden_class_or_namespace_member,
                                      (a_scope_ptr)NULL, old_sym_ptr);
      }  /* if */
    } else {
      /* Not a friend declaration.  Unless it is a declaration at file scope,
         look for a declaration in an enclosing scope that is hidden by this
         declaration -- if there is one, see if the hidden reference can be
         resolved by using a name qualifier. */
      if ((sym_ptr->kind == (a_symbol_kind)sk_routine ||
           sym_ptr->kind == (a_symbol_kind)sk_member_function) &&
           sym_ptr->variant.routine.instance_ptr != NULL &&
           !sym_ptr->variant.routine.instance_ptr->is_guiding_decl &&
           sym_ptr == (a_symbol_ptr)sym_ptr->
                         variant.routine.ptr->source_corresp.assoc_info) {
        /* Ignore function template instances; the references that trigger
           their creation are not declarations that can hide other
           declarations. */
        if (depth_innermost_function_scope != NO_SCOPE_DEPTH &&
            sym_ptr->kind == (a_symbol_kind)sk_routine) {
          old_sym_ptr = normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
          if (old_sym_ptr != NULL) {
            if (old_sym_ptr == sym_ptr ||
                matches_member_of_overload_set(sym_ptr, old_sym_ptr)) {
            } else {
              tag_hidden_by_nontag = FALSE;
              hidden_class_or_namespace_member = TRUE;
              record_defeatable_name_hiding(sym_ptr, tag_hidden_by_nontag,
                                            hidden_class_or_namespace_member,
                                            (a_scope_ptr)NULL, old_sym_ptr);
            }  /* if */
          }  /* if */
        }  /* if */
      } else if (sym_ptr->decl_scope == FILE_SCOPE_NUMBER ||
                 (!sym_ptr->is_class_member &&
                  (nsp = sym_ptr->parent.namespace_ptr) != NULL &&
                  nsp->source_corresp.name == NULL &&
                  nsp->source_corresp.parent.namespace_ptr == NULL)) {
        /* Ignore names that belong to the file scope or to an unnamed
           namespace scope immediately within the file scope. */
      } else {
        an_id_lookup_options_set	options;
        clear_specific_symbol(locator);
        options = IDL_HIDDEN_NAME_LOOKUP | IDL_SKIP_CURR_SCOPE |
                  IDL_SKIP_TEMPLATE_DECL_SCOPES;
        old_sym_ptr = normal_id_lookup(&locator, options);
        if (old_sym_ptr != NULL) {
          a_symbol_ptr  tag_sym = NULL;
          if (is_injected_class_symbol(sym_ptr) &&
              (is_tag_symbol(old_sym_ptr) ||
               is_class_template_symbol(old_sym_ptr))) {
            tag_sym =
               (a_symbol_ptr)(skip_typerefs(type_symbol_type(sym_ptr))->
                                                  source_corresp.assoc_info);
          }  /* if */
          if (tag_sym != NULL &&
              (symbols_are_equivalent(old_sym_ptr, tag_sym) ||
               (is_class_template_symbol(old_sym_ptr) &&
                is_template_class_symbol(tag_sym)))) {
            /* sym_ptr does not hide old_sym_ptr -- they represent the same
               declaration. */
          } else if (old_sym_ptr->decl_scope == FILE_SCOPE_NUMBER ||
                     old_sym_ptr->is_class_member ||
                     old_sym_ptr->parent.namespace_ptr != NULL ||
                     old_sym_ptr->synthesized_namespace_projection) {
            /* A qualifiable name. */
            tag_hidden_by_nontag = FALSE;
            hidden_class_or_namespace_member = TRUE;
            record_defeatable_name_hiding(old_sym_ptr, tag_hidden_by_nontag,
                                          hidden_class_or_namespace_member,
                                          (a_scope_ptr)NULL, sym_ptr);
          }  /* if */
          /* Do a similar check for tag names in containing scopes. */
          if (!is_tag_symbol(old_sym_ptr) &&
              !is_class_template_symbol(old_sym_ptr)) {
            clear_specific_symbol(locator);
            old_sym_ptr = normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP |
                                                     IDL_MUST_BE_TAG |
                                                     IDL_SKIP_CURR_SCOPE);
            if (old_sym_ptr != NULL) {
              if ((old_sym_ptr == sym_ptr) ||
                  (old_sym_ptr->decl_scope == sym_ptr->decl_scope)) {
                /* This can happen when the scope to which sym_ptr belongs is
                   an unnamed namespace. */
              } else {
                tag_hidden_by_nontag = TRUE;
                if (old_sym_ptr->decl_scope == FILE_SCOPE_NUMBER ||
                    old_sym_ptr->is_class_member ||
                    old_sym_ptr->parent.namespace_ptr != NULL) {
                  hidden_class_or_namespace_member = TRUE;
                  record_defeatable_name_hiding(
                                              old_sym_ptr,
                                              tag_hidden_by_nontag,
                                              hidden_class_or_namespace_member,
                                              (a_scope_ptr)NULL, sym_ptr);
                }  /* if */
              }  /* if */
            }  /* if */
          }  /* if */
        }  /* if */
      }  /* if */
      if (sym_ptr->decl_scope == FILE_SCOPE_NUMBER ||
          sym_ptr->is_class_member ||
          sym_ptr->parent.namespace_ptr != NULL) {
        /* This is a declaration at namespace or class scope.  Examine every
           declaration of this name that has already appeared in a namespace
           or nonlocal class scope that is nested within the current scope
           -- the current declaration will be hidden in such a scope, but
           the hiding can be defeated (in a reactivation of that scope) by
           applying a qualifier (class-name:: or namespace-name:: or ::). */
        hidden_class_or_namespace_member = FALSE;
        tag_hidden_by_nontag = FALSE;
        if (!is_injected_class_symbol(sym_ptr) && is_tag_symbol(sym_ptr)) {
          clear_specific_symbol(locator);
          if (sym_ptr->is_class_member) {
            (void)class_qualified_id_lookup(&locator,
                                            sym_ptr->parent.class_type,
                                            IDL_HIDDEN_NAME_LOOKUP);
          } else if (sym_ptr->parent.namespace_ptr != NULL) {
            (void)namespace_qualified_id_lookup(&locator,
                                                sym_ptr->parent.namespace_ptr,
                                                IDL_HIDDEN_NAME_LOOKUP);
          } else {
            (void)file_scope_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
          }  /* if */
          check_assertion(locator.specific_symbol != NULL);
          tag_hidden_by_nontag = locator.specific_symbol != sym_ptr;
        }  /* if */
        for (old_sym_ptr = sym_ptr->header->inactive_symbols;
             old_sym_ptr != NULL;
             old_sym_ptr = old_sym_ptr->next) {
          /* See if *sym_ptr is potentially hidden by *old_sym_ptr. */
          if (is_potentially_hidden_by(sym_ptr, old_sym_ptr)) {
            /* The scope to which *old_sym_ptr belongs is nested within the
               scope to which *sym_ptr belongs.  That means sym_ptr would be
               hidden by old_sym_ptr unless it's hidden by some intervening
               declaration. */
            nsp = NULL;
            if (old_sym_ptr->is_class_member) {
              a_type_ptr  tp = old_sym_ptr->parent.class_type;
              if (symbol_supplement_for_class(tp)->is_nonreal_class) {
                /* Ignore nonreal classes. */
                continue;
              }  /* if */
              sp = tp->variant.class_struct_union.extra_info->assoc_scope;
              if (sp == NULL) {
                /* This can happen if a name is a member of class that is
                   a template parameter -- e.g.,
                     template <class T> void f(T t, T::S s) { ... }
                   In such a case, a class type for T is created to serve as
                   the parent for S but it is undefined.  A similar case
                   occurs with friend declarations within a class template:
                     template <class T> class A {
                       friend void T::f();
                     };
                */
                continue;
              }  /* if */
              /* Look for an intervening declaration that would make it
                 unnecessary to record sym_ptr in the hidden name table for
                 the scope to which old_sym_ptr belongs. */
              while (tp->source_corresp.is_class_member) {
                a_symbol_ptr  sym;
                tp = tp->source_corresp.parent.class_type;
                clear_specific_symbol(locator);
                sym = class_qualified_id_lookup(&locator, tp,
                                                IDL_HIDDEN_NAME_LOOKUP);
                if (sym != NULL) {
                  if (sym == sym_ptr ||
                      matches_member_of_overload_set(sym_ptr, sym)) {
                    /* The lookup found sym_ptr, which means there is no
                       intervening declaration. */
                    hidden_class_or_namespace_member = TRUE;
                  }  /* if */
                  break;
                }  /* if */
              }  /* while */
              if (!hidden_class_or_namespace_member) {
                if (tp->source_corresp.is_class_member) {
                  /* We must have found an intervening declaration. */
                  continue;
                } else {
                  /* No intervening declaration -- set up for checking
                     enclosing namespaces, if any. */
                  nsp = parent_namespace_for_symbol(old_sym_ptr);
                  check_assertion(nsp ==
                                    tp->source_corresp.parent.namespace_ptr);
                }  /* if */
              }  /* if */
            } else if ((nsp = old_sym_ptr->parent.namespace_ptr) != NULL) {
              /* old_sym_ptr is a namespace member. */
              check_assertion(!nsp->is_namespace_alias &&
                              nsp->variant.assoc_scope != NULL);
              if (sym_ptr->decl_scope != FILE_SCOPE_NUMBER &&
                  !sym_ptr->is_class_member &&
                  sym_ptr->parent.namespace_ptr == nsp) {
                continue;
              }  /* if */
              /* Record the scope to which old_sym_ptr belongs. */
              sp = nsp->variant.assoc_scope;
              /* Set up for checking enclosing namespaces, if any. */
              nsp = nsp->source_corresp.parent.namespace_ptr;
            } else {
              /* old_sym_ptr is not a class or namespace member.  Skip past
                 it. */
              continue;
            }  /* if */
            if (!hidden_class_or_namespace_member) {
              for (;;) {
                if (nsp == NULL) {
                  hidden_class_or_namespace_member = TRUE;
                  break;
                } else {
                  a_symbol_ptr  sym;
                  clear_specific_symbol(locator);
                  sym = namespace_qualified_id_lookup(&locator, nsp,
                                                      IDL_HIDDEN_NAME_LOOKUP);
                  if (sym != NULL) {
                    if (sym == sym_ptr ||
                        matches_member_of_overload_set(sym_ptr, sym)) {
                      /* The lookup found sym_ptr, which means there is no
                         intervening declaration. */
                      hidden_class_or_namespace_member = TRUE;
                    }  /* if */
                    break;
                  }  /* if */
                }  /* if */
                nsp = nsp->source_corresp.parent.namespace_ptr;
              }  /* for */
            }  /* if */
            if (hidden_class_or_namespace_member) {
              record_defeatable_name_hiding(sym_ptr, tag_hidden_by_nontag,
                                            hidden_class_or_namespace_member,
                                            sp, (a_symbol_ptr)NULL);
            }  /* if */
          }  /* if */
        }  /* for */
      }  /* if */
      /* Special handling for an ambiguity resulting from a using-directive.
           namespace N { void f(); }
           using namespace N;
           void f();
           void g() { ::f(); }    // ambiguity resolved by qualifier
      */
      if (sym_ptr->decl_scope == FILE_SCOPE_NUMBER ||
          (!sym_ptr->is_class_member &&
           sym_ptr->parent.namespace_ptr != NULL)) {
        /* Do a lookup and see if a synthesized namespace projection is
           found.  If it is, we can assume that sym_ptr is part of the mix
           (though it may not actually be returned unless a function overload
           set is produced), and if so qualifying sym_ptr will disambiguate
           the reference. */
        clear_specific_symbol(locator);
        (void)normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
        old_sym_ptr = locator.specific_symbol;
        if (old_sym_ptr != NULL &&
            old_sym_ptr->synthesized_namespace_projection) {
          hidden_class_or_namespace_member = TRUE;
          tag_hidden_by_nontag = FALSE;
          record_defeatable_name_hiding(sym_ptr, tag_hidden_by_nontag,
                                        hidden_class_or_namespace_member,
                                        (a_scope_ptr)NULL,
                                        (a_symbol_ptr)NULL);
        }  /* if */
      }  /* if */
    }  /* if */
  }  /* if */
}  /* check_for_defeatable_name_hiding */


void check_hiding_by_inherited_names(a_type_ptr  class_type,
                                     a_scope_ptr sp)
/*
Perform hidden name checking on the members of each of the base classes of
class_type.  If class_type is not the most derived type (i.e., if its
IL scope is not that of the indicated IL scope), do hidden name checking on
its own members, too.  This routine is called recursively.
*/
{
  a_base_class_ptr  bcp = base_classes_of(class_type);
  a_symbol_ptr      sym_ptr, old_sym_ptr;
  a_symbol_locator  locator;
  a_boolean         top_level;

  top_level = (sp == class_type->variant.class_struct_union.
                                                   extra_info->assoc_scope);
#if DEBUG
  if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
    /* If this is the top-level call, identify class_type. */
    if (bcp != NULL && top_level) {
      fputs("Hidden name check for inherited names of ", f_debug);
      db_type_name(class_type);
      fputc('\n', f_debug);
    }  /* if */
  }  /* if */
#endif /* DEBUG */
  /* Loop through each of the base classes of class type and perform hidden
     name checking on the inherited members of direct (and, if top-level,
     virtual) base classes. */
  for (; bcp != NULL; bcp = bcp->next) {
    if (bcp->direct || (top_level && bcp->is_virtual)) {
      check_hiding_by_inherited_names(bcp->type, sp);
    }  /* if */
  }  /* for */
  if (sp != class_type->variant.class_struct_union.extra_info->assoc_scope) {
    sym_ptr = symbol_supplement_for_class(class_type)->symbols;
    for (; sym_ptr != NULL; sym_ptr = sym_ptr->next_in_scope) {
      /* Skip constructors. */
      if (is_constructor_symbol(sym_ptr)) continue;
#if DEBUG
      if (debug_level >= 4 || db_flag_is_set("dump_hidden")) {
        if (sym_ptr->decl_position.seq) {
          fputs("  Hidden name check: ", f_debug);
          fprintf(f_debug, "<%s> ", symbol_kind_names[(int)sym_ptr->kind]);
          db_symbol_name(sym_ptr);
          fputc('\n', f_debug);
        }  /* if */
      }  /* if */
#endif /* DEBUG */
      /* Perform a lookup. */
      clear_locator(&locator, &sym_ptr->decl_position);
      locator.symbol_header = sym_ptr->header;
      (void)normal_id_lookup(&locator, IDL_HIDDEN_NAME_LOOKUP);
      old_sym_ptr = locator.specific_symbol;
      /* If something was found, see if it is hidden by sym_ptr. */
      if (old_sym_ptr != NULL) {
        a_symbol_ptr  tag_sym = NULL;
        if (is_injected_class_symbol(sym_ptr) &&
            (is_tag_symbol(old_sym_ptr) ||
             is_class_template_symbol(old_sym_ptr))) {
          tag_sym =
               (a_symbol_ptr)(skip_typerefs(type_symbol_type(sym_ptr))->
                                                  source_corresp.assoc_info);
        }  /* if */
        if (tag_sym != NULL &&
            (symbols_are_equivalent(old_sym_ptr, tag_sym) ||
             (is_class_template_symbol(old_sym_ptr) &&
              is_template_class_symbol(tag_sym)))) {
          /* sym_ptr does not hide old_sym_ptr -- they represent the same
             declaration. */
        } else if (old_sym_ptr->decl_scope == FILE_SCOPE_NUMBER ||
                   old_sym_ptr->is_class_member ||
                   old_sym_ptr->parent.namespace_ptr != NULL) {
          /* The name hiding can be defeated by using a qualifier. */
          record_defeatable_name_hiding(
                                  old_sym_ptr,
                                  /*tag_hidden_by_nontag=*/FALSE,
                                  /*hidden_class_or_namespace_member=*/TRUE,
                                  sp, sym_ptr);
        }  /* if */
      }  /* if */
    }  /* for */
  }  /* if */
}  /* check_hiding_by_inherited_names */

#endif /* RECORD_HIDDEN_NAMES_IN_IL */
#if GENERATE_SOURCE_SEQUENCE_LISTS

static void sym_update_source_sequence_list(
                                  a_symbol_ptr                 sym,
                                  a_source_position            *pos,
                                  a_boolean                    is_primary_decl,
                                  a_source_sequence_entry_ptr  old_ssep)
/*
Allocate a source sequence entry for the IL entry to which sym refers and
add it to the list for the appropriate scope.  If is_primary_decl is TRUE
this is the primary declaration of the IL entity, and any existing source
sequence entry already bound to the IL entity should be demoted to
secondary status.
*/
{
  char                          *il_entry_ptr;
  an_il_entry_kind              kind;
  a_src_seq_secondary_decl_ptr  sssdp;
  a_boolean                     force_alloc_in_filescope;
  a_memory_region_number        region_to_switch_back_to;

  if (!source_sequence_entries_disallowed) {
    /* We are in a context in which source sequence entries are being
       generated. */
    if ((il_entry_ptr = il_entry_for_symbol_null_okay(sym, &kind)) != NULL) {
      if (pos->seq == 0 ||
          (kind == iek_routine &&
           ((a_routine_ptr)il_entry_ptr)->compiler_generated)) {
        /* Don't put out source sequence information on compiler generated
           functions. */
      } else {
        if (!is_primary_decl) {
          /* This is not a primary declaration, so put out an entry for a
             secondary declaration. */
          /* Switch to the file scope memory region to allocate the new entry
             if necessary. */
          if (curr_il_region_number != FILE_SCOPE_REGION_NUMBER &&
              in_file_scope(il_entry_ptr)) {
            force_alloc_in_filescope = TRUE;
            switch_to_file_scope_region(&region_to_switch_back_to);
          } else {
            force_alloc_in_filescope = FALSE;
          }  /* if */
          sssdp = alloc_src_seq_secondary_decl();
          if (force_alloc_in_filescope) {
            switch_back_to_original_region(region_to_switch_back_to);
          }  /* if */
          /* Set the fields. */
          sssdp->decl_position = *pos;
          sssdp->entity.kind = (a_byte_il_entry_kind)kind;
          sssdp->entity.ptr = il_entry_ptr;
          /* Change the parameter values accordingly. */
          kind = iek_src_seq_secondary_decl;
          il_entry_ptr = (char *)sssdp;
          if (scope_stack[depth_scope_stack].kind ==
                                       (a_scope_kind)sck_func_prototype) {
            sssdp->declared_in_func_prototype = TRUE;
          }  /* if */
        }  /* if */
        f_update_source_sequence_list(il_entry_ptr, kind, old_ssep);
      }  /* if */
    }  /* if */
  }  /* if */
}  /* sym_update_source_sequence_list */

#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */

#if !GENERATE_SOURCE_SEQUENCE_LISTS
/* ARGSUSED */ /* <-- ssep is only used with source sequence lists. */
#endif /* !GENERATE_SOURCE_SEQUENCE_LISTS */
void record_symbol_declaration(a_symbol_reference_kind      srk_flags,
                               a_symbol_ptr                 sym_ptr,
                               a_source_position            *source_position,
                               a_source_sequence_entry_ptr  ssep)
/*
Record information about how the given symbol is declared.  The srk_flags
parameter describes the specificity of the declaration (e.g., that it is a
definition, a friend declaration, etc.).  The source position will be recorded
in the symbol as its "decl_position" (overwriting what's there already, if
this is a definition); the same will be done for the decl_position field of
the IL entry.  A cross-reference entry will be put out.  If source-sequence
entries are being generated, ssep may point to an "empty" entry already
created for this entity; otherwise, it is NULL.
*/
{
  a_boolean                is_definition = srk_flags & SRK_DEFINITION;
  a_boolean                is_tentative_def = srk_flags & SRK_TENTATIVE_DEF;
#if GENERATE_SOURCE_SEQUENCE_LISTS
  a_boolean                is_primary_decl = FALSE;
  a_boolean                set_first_decl_flag = FALSE;
  a_boolean                update_src_seq_list = TRUE;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
  a_source_correspondence  *scptr = NULL;

  if (is_definition) {
    if (sym_ptr->defined) {
      /* This is a redefinition -- allowed for C variables at file scope, for
         macros, and for C++ typedefs. */
      if (C_mode() && sym_ptr->kind == (a_symbol_kind)sk_variable &&
          !is_tentative_def) {
        /* This must be an initializing definition following a tentative
           definition. */
#if GENERATE_SOURCE_SEQUENCE_LISTS
        is_primary_decl = TRUE;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
      } else {
        /* A definition is ordinarily the primary declaration, but if it was
           previously defined and this is just a redefinition, this should be
           recorded as a secondary declaration. */
        is_definition = FALSE;
      }  /* if */
    } else {
#if GENERATE_SOURCE_SEQUENCE_LISTS
      is_primary_decl = !is_tentative_def;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
      sym_ptr->defined = TRUE;
      sym_ptr->decl_position = *source_position;
    }  /* if */
    if (is_definition) {
      sym_ptr->decl_position = *source_position;
      scptr = source_corresp_entry_for_symbol(sym_ptr);
      if (scptr != NULL) {
#if RECORD_TEMPLATES_IN_IL
        if (is_template_symbol(sym_ptr)) {
          /* The decl_position field in the IL template entry is not
             updated. */
        } else
#endif /* RECORD_TEMPLATES_IN_IL */
        /* Do not insert code here. */
        {
          scptr->decl_position = *source_position;
        }  /* if */
#if EXTRA_SOURCE_POSITIONS_IN_IL
        if (scptr->decl_pos_info == NULL) {
          scptr->decl_pos_info =
                       alloc_decl_position_supplement(in_file_scope(scptr));
#if RECORD_TEMPLATES_IN_IL
        } else if (is_template_symbol(sym_ptr)) {
          /* The decl-position-supplement in the IL template entry should not
             be modified. */
#endif /* RECORD_TEMPLATES_IN_IL */
        } else {
          clear_decl_position_supplement(scptr->decl_pos_info);
        }  /* if */
#endif /* EXTRA_SOURCE_POSITIONS_IN_IL */
      }  /* if */
    }  /* if */
  }  /* if */
  /* Set declaration sequence numbers based on the first declaration of the
     name, regardless of whether it is the primary declaration or not. */
  if (sym_ptr->decl_seq == 0) set_decl_sequence_number(sym_ptr);
  /* Update the cross reference file if it exists. */
  if (f_xref_info != NULL) {
    /* If writing cross-reference information, write an entry for this
       declaration. */
    write_xref_entry(srk_flags, sym_ptr, source_position);
  }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  /* Issue a source sequence entry -- unless this is a label definition.  (A
     label is always defined by an stmk_label statement, for which a source
     sequence entry will be put out; putting out both would be redundant.)
     Also, sk_parameter symbols are not yet bound to a variable, so there's
     no way to put out a source sequence entry yet. */
  if (sym_ptr->kind != (a_symbol_kind)sk_label &&
      sym_ptr->kind != (a_symbol_kind)sk_parameter) {
    /* Determine whether the field definition_is_first_decl should be set
       for a class symbol.  Note that it may be changed later, if a source
       sequence entry is generated to represent a forward declaration of
       the class. */
    if (is_definition && is_class_struct_union_symbol(sym_ptr) &&
        scptr != NULL && scptr->source_sequence_entry == NULL) {
      set_first_decl_flag = TRUE;
    }  /* if */
#if TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS
    if (sym_ptr->kind == (a_symbol_kind)sk_member_function ||
        sym_ptr->kind == (a_symbol_kind)sk_routine) {
      if (is_definition && !C_mode() &&
          scope_stack[depth_scope_stack].kind ==
                                    (a_scope_kind)sck_class_struct_union &&
          !scope_stack[depth_scope_stack].inside_local_class) {
        /* This is a member or friend function definition inside the
           definition of a nonlocal class.  When template instantiations are
           put out in the source sequence list, it is necessary to move the
           member or friend definition outside the class definition (i.e.,
           just after it).  That means a secondary-source-sequence entry
           should be put out here. */
        is_primary_decl = FALSE;
      }  /* if */
#if CLASS_TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS
    } else if (is_class_struct_union_symbol(sym_ptr) && !C_mode()) {
      if (is_definition) {
        if (scptr != NULL && scptr->source_sequence_entry == NULL) {
          /* This is the initial declaration of this class.  If appropriate,
             put out a secondary declaration entry immediately before the
             definition entry to deal with forward reference problems of
             instantiations that are inserted in front of the class; if
             there is no insertion, the entry will be removed eventually. */
          a_boolean                     add_secondary_decl;
          a_type_ptr                    class_type;
          an_il_entry_kind              kind;
          a_class_type_supplement_ptr   parent_ctsp;
          a_src_seq_secondary_decl_ptr  sssdp;

          if (scptr->is_local_to_function) {
            /* Can't be done for local functions. */
            add_secondary_decl = FALSE;
          } else if (!scptr->is_class_member) {
            /* Okay for all classes that aren't nested. */
            add_secondary_decl = TRUE;
          } else {
            /* It's okay for nested classes only if it's a deferred
               definition (i.e., the definition appears at file or
               namespace scope). */
            parent_ctsp = scptr->parent.class_type->
                                  variant.class_struct_union.extra_info;
            add_secondary_decl = (parent_ctsp->assoc_scope->
                                     depth_in_scope_stack == NO_SCOPE_DEPTH);
          }  /* if */
          if (add_secondary_decl) {
            class_type = sym_ptr->variant.class_struct_union.type;
            kind = (an_il_entry_kind)iek_type;
            sssdp = make_source_sequence_secondary_decl((char *)class_type,
                                                        kind, class_type);
            sssdp->autonomous_tag_decl = TRUE;
            sssdp->decl_position = *source_position;
            sssdp->compiler_generated_forward_decl = TRUE;
            sssdp->first_declaration = TRUE;
            set_first_decl_flag = FALSE;
            if (class_type->variant.class_struct_union.is_template_class) {
#if BACK_END_IS_CP_GEN_BE
              sssdp->specialized_with_new_syntax =
                            !old_specializations_for_generated_instances;
#else /* !BACK_END_IS_CP_GEN_BE */
              sssdp->specialized_with_new_syntax = TRUE;
#endif /* BACK_END_IS_CP_GEN_BE */
            }  /* if */
            kind = (an_il_entry_kind)iek_src_seq_secondary_decl;
            add_to_source_sequence_list((char *)sssdp, kind);
            /* Reset the insertion point for instantiations to NULL. */
            reset_ss_list_instantiation_insert_point();
          }  /* if */
        }  /* if */
      } else if (depth_innermost_instantiation_scope != NO_SCOPE_DEPTH) {
        /* Not a definition.  If this is a nested class declaration inside
           a class template instantiation, only put out the declaration if
           it's the first.  This is to deal with the following case:
             template <class T> class A {
               class N;
               class N { ... };
             };
             A<int> x;
           where the instantiation of A<int> would be represented in the
           generated C++ as a specialization:
             template<> class A<int> {
               class N;
               class N;                // declaration substitutes for
             };                        //    inline definition
             class A<int>::N { ... }   // if needed
           The problem is that a second declaration of class N is disallowed
           (9.2 paragraph 1 of the C++ standard).  The solution is to suppress
           any declaration of a nested class other than the first. */
        a_scope_stack_entry_ptr scope_stack_ptr =
                                         &scope_stack[depth_scope_stack];
        if (!scope_stack_ptr->in_prototype_instantiation &&
            scope_stack_ptr->kind == (a_scope_kind)sck_class_struct_union &&
            sym_ptr->is_class_member &&
            sym_ptr->parent.class_type == scope_stack_ptr->assoc_type) {
          scptr = source_corresp_entry_for_symbol(sym_ptr);
          if (scptr != NULL && scptr->source_sequence_entry != NULL) {
            update_src_seq_list = FALSE;
          }  /* if */
        }  /* if */
      }  /* if */
#endif /* CLASS_TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS */
    }  /* if */
#endif /* TEMPLATE_INSTANTIATIONS_IN_SOURCE_SEQUENCE_LISTS */
    if (update_src_seq_list) {      /*lint !e774*/
      if (is_definition) {
        /* If this is a primary declaration (or a tentative definition that
           is the first definition of the variable), erase the previous
           source sequence entry bound to this entity (if any). */
        if (scptr != NULL) scptr->source_sequence_entry = NULL;
        if (set_first_decl_flag) {
          sym_ptr->variant.class_struct_union.extra_info->
                                         definition_is_first_decl = TRUE;
        }  /* if */
      }  /* if */
      sym_update_source_sequence_list(sym_ptr, source_position,
                                      is_primary_decl, ssep);
    }  /* if */
  }  /* if */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
#if RECORD_HIDDEN_NAMES_IN_IL
  if (!C_mode()) check_for_defeatable_name_hiding(sym_ptr);
#endif /* RECORD_HIDDEN_NAMES_IN_IL */
}  /* record_symbol_declaration */


void record_symbol_reference(a_symbol_reference_kind kind,
                             a_symbol_ptr            sym_ptr,
                             a_source_position       *source_position,
                             a_boolean               update_il_entry)
/*
Record a reference of the indicated kind to the indicated symbol.  Set the
referenced flag in the symbol entry.  If update_il_entry is TRUE, also
set the referenced flag in the associated IL entry, if any.  Mark the
symbol "used" or "set", if appropriate.  sym_ptr should not point to a
projection symbol.
*/
{
  a_source_correspondence *scptr;
  a_symbol_kind           sym_kind = sym_ptr->kind;
 
  check_assertion_str(sym_ptr->kind != (a_symbol_kind)sk_projection &&
                      sym_ptr->kind != (a_symbol_kind)sk_namespace_projection,
                      "record_symbol_reference: projection symbol");
  /* If writing cross-reference information, write an entry for this
     declaration. */
  if (f_xref_info != NULL) {
    a_symbol_ptr             sym_for_xref = sym_ptr;
    a_symbol_reference_kind  kind_for_xref = kind;
    a_type_ptr               tp;

    if (sym_kind == (a_symbol_kind)sk_type) {
      if (sym_ptr->is_template_param) {
        /* A reference to a template parameter during template instantiation is
           actually a reference to the template argument that it represents. */
        tp = sym_ptr->variant.type.ptr;
        if (tp->kind == (a_type_kind)tk_template_param) {
          /* We are in the midst of a template definition. */
        } else {
          /* We are in the midst of a template instantiation. */
          for(;;) {
            if (tp->kind == (a_type_kind)tk_typeref) {
              if (typeref_is_qualified(tp)) {
                tp = tp->variant.typeref.type;
              } else {
                sym_for_xref = (a_symbol_ptr)tp->source_corresp.assoc_info;
                check_assertion(sym_for_xref != NULL);
                kind_for_xref |= SRK_IMPLICIT_TEMPLATE_ARG;
                break;
              }  /* if */
            } else if (is_array_type(tp)) {
              tp = array_element_type(tp);
            } else if (is_ptr_or_ref_type(tp)) {
              tp = type_pointed_to(tp);
            } else {
              break;
            }  /* if */
          }  /* for */
        }  /* if */
      }  /* if */
    } else if (is_class_symbol(sym_ptr)) {
      tp = type_symbol_type(sym_ptr);
      if (is_immediate_class_type(tp) && !sym_ptr->is_class_member) {
        a_class_symbol_supplement_ptr  cssp;
        cssp = sym_ptr->variant.class_struct_union.extra_info;
        if (cssp->is_prototype_instantiation) {
          /* A reference to a top-level prototype instantiation (i.e., not a
             nested class) is put out as a reference to the template itself. */
          sym_for_xref = cssp->class_template;
          check_assertion(sym_for_xref != NULL);
        }  /* if */
      }  /* if */
    }  /* if */
    write_xref_entry(kind_for_xref, sym_for_xref, source_position);
  }  /* if */
  /* Set the referenced flag in the symbol. */
  sym_ptr->referenced = TRUE;
  scptr = source_corresp_entry_for_symbol(sym_ptr);
  if (update_il_entry && scptr != NULL) {
    /* Set the referenced flag in the associated intermediate language entry,
       if there is one.  Note that more than one symbol can point to the same
       IL entry.  Use the fact that all the IL tables begin with
       a_source_correspondence. */
    /* If the symbol is for a virtual function, do not set the IL referenced
       flag; a reference to the symbol is not necessarily a reference to the
       corresponding IL entry.  When it is, the flag is set explicitly
       elsewhere. */
    if (sym_kind == (a_symbol_kind)sk_member_function &&
        sym_ptr->variant.routine.ptr->is_virtual) {
      /* Do not set IL referenced flag. */
    } else {
      if (sym_kind == (a_symbol_kind)sk_static_data_member) {
        /* If we are marking a template static data member as referenced, also
           set its instantiation required flag. */
        a_template_instance_ptr	tip;
        tip = sym_ptr->variant.static_data_member.instance_ptr;
        if (tip != NULL && !tip->instantiation_required) {
          update_instantiation_required_flag(tip, TRUE,
                                            /*defer_inline=*/FALSE);
        }  /* if */
      }  /* if */
      scptr->referenced = TRUE;
    }  /* if */
  }  /* if */
  if (update_il_entry && (kind & SRK_ADDRESS_TAKEN)) {
    /* Set the address_taken flag in variables and routines. */
    if (sym_kind == (a_symbol_kind)sk_variable) {
      set_variable_address_taken(sym_ptr->variant.variable.ptr);
    } else if (sym_kind == (a_symbol_kind)sk_static_data_member) {
      set_variable_address_taken(sym_ptr->variant.static_data_member.variable);
    } else if (sym_kind == (a_symbol_kind)sk_routine ||
               sym_kind == (a_symbol_kind)sk_member_function) {
      sym_ptr->variant.routine.ptr->address_taken = TRUE;
    }  /* if */
  }  /* if */
  if (sym_kind == (a_symbol_kind)sk_variable) {
    /* If this reference is a use or, by taking the variable's address, a
       potential use, mark the variable has having been used.  Note that for
       an error reference, the variable is marked as being both set
       and modified, to keep diagnostics from being issued down the road; nor
       are diagnostics issued here. */
    a_scope_stack_entry_ptr  ssep;
    a_variable_ptr           vp = sym_ptr->variant.variable.ptr;
    if ((kind & SRK_ALL_VARIABLE_USES) || (kind & SRK_ERROR)) {
      if (sym_ptr->variant.variable.used) {
        /* This is not the first use. */
        if (vp->is_parameter || vp->is_handler_param) {
          /* Mark the parameter as multiply used (information that may be
             useful for inlining). */
          vp->param_used_more_than_once = TRUE;
        }  /* if */
      } else {
        /* This is the first use of the variable. */
        if (!(kind & SRK_USE) || suppress_used_before_set_warnings ||
            sym_ptr->variant.variable.value_has_been_set) {
          /* No diagnostic. */
        } else if (!vp->source_corresp.is_local_to_function) {
          /* A block-extern variable or a namespace-scope variable with
             internal linkage -- no diagnostic. */
        } else {
          /* Variable's value has not been set yet.  Issue a warning, if
             appropriate. */
          a_boolean                suppress_warning = FALSE;

          if (!suppress_warning && !C_mode()) {
            /* In C++ don't put out a warning if the variable of class
               type (or array of class type) and the class has no fields. */
            a_type_ptr  tp = vp->type;
            if (is_array_type(tp)) tp = underlying_array_element_type(tp);
            if (is_class_struct_union_type(tp) &&
                !symbol_supplement_for_class(tp)->any_nonstatic_data_members) {
              /* Variable is of empty-class type. */
              suppress_warning = TRUE;
            }  /* if */
          }  /* if */
          if (!suppress_warning) {
            /* To determine whether to suppress the warning, examine the scope
               stack for labels and uncompleted loops that might enable the
               program to set the variable in code that has not yet been seen
               and then to branch back to the current code.  In other words,
               only issue a warning if we're sure the variable cannot have
               been set. */
            for (ssep = &scope_stack[decl_scope_level]; ; --ssep) {
              check_assertion(ssep != &scope_stack[0]);
              if (ssep->kind == (a_scope_kind)sck_function) {
                /* A reference to a local variable from within quasi-nested
                   function definition should have been reported as an error
                   and recorded as an srk_error reference. */
                check_assertion(ssep->number == sym_ptr->decl_scope ||
                                !scptr->is_local_to_function);
                /* We are at the outermost scope of the function.  Check for
                   a label. */
                goto check_label_decl_seq;
              } else if (ssep->number == sym_ptr->decl_scope) {
                /* We are at the scope in which the variable was declared.
                   Jump out to the function scope and look for a label. */
                ssep = &scope_stack[depth_innermost_function_scope];
check_label_decl_seq:
                /* If the variable was declared before the label, suppress the
                   warning.  If it was declared after the label, the warning
                   is appropriate.  For example:
                     void f() {
                       int i;
                         :
                     L:
                       int j;
                       ++i;          // No warning -- i may be set later.
                       ++j;          // Warning -- j cannot have been set yet.
                           :
                     }
                */
                if (ssep->last_label_decl_seq > sym_ptr->decl_seq) {
                  /* Variable was declared before the label was defined. */
                  suppress_warning = TRUE;
                }  /* if */
                break;
              } else if (ssep->is_loop_scope) {
                /* The variable was declared in a scope outside the loop
                   scope, so suppress the warning.  If it were declared within
                   the loop, the warning would still be okay.  For example:
                     void f() {
                       int i;
                         :
                       for (;;) {
                         int j;
                         ++i;        // No warning -- i may be set later.
                         ++j;        // Warning -- j cannot have been set yet.
                           :
                       }
                     }
                */
                suppress_warning = TRUE;
                break;
              }  /* if */
            }  /* for */
          }  /* if */
          if (!suppress_warning) {
            pos_sy_warning(ec_used_before_set, source_position, sym_ptr);
          }  /* if */
        }  /* if */
        sym_ptr->variant.variable.used = TRUE;
        if (scptr != NULL) {
          /* The variable may point to a different symbol in cases like
             this:
               static int i = 1;
               int f() { extern int i; return i; }
             and it is necessary for the file-scope symbol to be marked
             "used" too. */
          if ((a_symbol_ptr)scptr->assoc_info != sym_ptr) {
            ((a_symbol_ptr)scptr->assoc_info)->variant.variable.used = TRUE;
          }  /* if */
        }  /* if */
      }  /* if */
    }  /* if */
    /* If this reference involves a modification or, by taking the variable's
       address, a potential modification, mark the variable as having its
       value set. */
    if ((kind & SRK_MODIFICATION) || (kind & SRK_ADDRESS_TAKEN) ||
        (kind & SRK_ERROR)) {
      mark_variable_value_set(sym_ptr);
      if (exceptions_enabled) {
        /* If the modification takes place inside a try block and the
           variable was declared in a (function-local) scope that contains
           the try block, then it may have to be treated as quasi-volatile
           -- it may need to be stored immediately in case an exception is
           thrown. */
        vp = sym_ptr->variant.variable.ptr;
        if (!vp->source_corresp.is_local_to_function) {
          /* Don't worry about file-scope variables. */
        } else if (vp->modified_within_try_block) {
          /* Flag is already set. */
        } else {
          ssep = &scope_stack[decl_scope_level];
          if (ssep->within_try_block) {
            /* This modification is inside a try block. */
            for (;;) {
              if (ssep->number == sym_ptr->decl_scope) {
                /* Symbol was declared inside the try block.  It's only those
                   declared outside the try block we're interested in. */
                break;
              } else if (ssep->is_try_block) {
                /* We've reached the try block's scope without finding the
                   scope in which the variable was declared.  Set the flag
                   and break out of the loop. */
                vp->modified_within_try_block = TRUE;
                break;
              }  /* if */
              /* Advance up the scope stack. */
              --ssep;
              check_assertion_str2(ssep->within_try_block,
                                   "record_symbol_reference:",
                                   "within_try_block not set properly");
            }  /* for */
          } /* if */
        }  /* if */
      }  /* if */
    }  /* if */
  }  /* if */
}  /* record_symbol_reference */


void reference_to_invalid_name(a_symbol_locator *locator)
/*
A name was referred to in a declaration but was invalid -- either it was
undefined or it was not being used correctly.  Put out cross reference
information on the reference, if required.
*/
{
  a_symbol_locator  loc;

  if (f_xref_info != NULL) {
    loc = *locator;
    if (loc.specific_symbol == NULL && !is_error_locator(loc)) {
      make_specific_symbol_error_locator(&loc);
    }  /* if */
    write_xref_entry(SRK_ERROR | SRK_REFERENCE, loc.specific_symbol,
                     &loc.source_position);
  }  /* if */
}  /* reference_to_invalid_name */


void record_param_id_list_declarations(a_func_info_block_ptr func_info)
/*
The function with which the param-id list headed by pid is associated has
been declared but not defined.  The symbols associated with the parameter
declarations should be recorded for cross referencing and any associated
source-sequence entries should be removed from the list.
*/
{
  a_param_id_ptr  pid = func_info->param_id_list;
#if GENERATE_SOURCE_SEQUENCE_LISTS
  a_source_sequence_entry_ptr  ss_list = func_info->prototype_scope_ss_list;
  a_source_sequence_entry_ptr  ssep, next_ssep, *avail_list;
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */

  /* Update xref information on each symbol. */
  for (; pid != NULL; pid = pid->next) {
    if (pid->symbol != NULL) {
      mark_declared(pid->symbol, &pid->symbol->decl_position);
    }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
    if (pid->source_sequence_entry != NULL) {
      check_assertion(ss_entry_kind(pid->source_sequence_entry) ==
                                             (an_il_entry_kind)iek_none);
      if (ss_list != NULL) {
        ssep = ss_list;
        for (; ssep != pid->source_sequence_entry; ssep = ssep->next) {
          check_assertion(ssep != NULL);
        }  /* for */
        if (ssep == ss_list) {
          ss_list = ssep->next;
        } else {
          ssep->prev->next = ssep->next;
        }  /* if */
        if (ssep->next != NULL) ssep->next->prev = ssep->prev;
        if (in_file_scope(ssep)) {
          avail_list = &scope_stack[DEPTH_OF_FILE_SCOPE].
                                              source_sequence_avail_list;
        } else {
          check_assertion(depth_innermost_function_scope != NO_SCOPE_DEPTH);
          avail_list = &scope_stack[depth_innermost_function_scope].
                                              source_sequence_avail_list;
        }  /* if */
        ssep->next = *avail_list;
        *avail_list = ssep;
      }  /* if */
      pid->source_sequence_entry = NULL;
    }  /* if */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
  }  /* for */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  for (ssep = ss_list; ssep != NULL; ssep = next_ssep) {
    next_ssep = ssep->next;
    if (ssep->prev != NULL) ssep->prev->next = next_ssep;
    if (ssep->next != NULL) ssep->next->prev = ssep->prev;
    ssep->next = ssep->prev = NULL;
    add_source_sequence_entry_to_list(ssep);
  }  /* for */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
}  /* record_param_id_list_declarations */


#if !GENERATE_SOURCE_SEQUENCE_LISTS
/*ARGSUSED*/ /* udp and prev_udp are used only for source sequence entries. */
#endif /* !GENERATE_SOURCE_SEQUENCE_LISTS */
void record_using_decl(a_symbol_ptr       sym,
                       a_source_position  *pos,
                       a_using_decl_ptr   udp,
                       a_using_decl_ptr   prev_udp)
/*
udp points to a using-decl entry created to represent an using declaration
specifying fundamental symbol sym.  If appropriate, update the cross reference
and source sequence output.  prev_udp, if non-NULL, refers to the previously
created using-decl in a function overload set.  *pos is the source position of
the identifier in the using-declaration.
*/
{
  /* Update the cross reference file if it exists. */
  if (f_xref_info != NULL) {
    /* If writing cross-reference information, write an entry for this
       declaration. */
    write_xref_entry(SRK_DECLARATION, sym, pos);
  }  /* if */
#if GENERATE_SOURCE_SEQUENCE_LISTS
  if (!source_sequence_entries_disallowed) {
    if (prev_udp == NULL) {
      add_to_source_sequence_list((char *)udp,
                                  (an_il_entry_kind)iek_using_decl);
    } else {
      prev_udp->next_in_overload_set = udp;
    }  /* if */
  }  /* if */
#endif /* GENERATE_SOURCE_SEQUENCE_LISTS */
}  /* record_using_decl */


static a_boolean is_cfront_base_class_destructor_access_bug(
                                                a_symbol_ptr   sym,
                                                a_routine_ptr  rp,
                                                a_type_ptr     class_of_object)
/*
Cfront has a bug in which a private destructor in a base class can be
called when the derived class really should not have access to it.
This function, which should only be called in cfront mode, detects
the condition in which the access error should be suppressed.
*/
{
  a_boolean  result = FALSE;
  if (rp->special_kind == (a_special_function_kind)sfk_destructor &&
      sym->parent.class_type != class_of_object &&
      class_of_object != NULL) {
    result = TRUE;
  }  /* if */
  return result;
}  /* is_cfront_base_class_destructor_access_bug */


void reference_to_implicitly_invoked_function
                                (a_symbol_ptr       sym,
                                 a_source_position  *pos,
                                 a_type_ptr         class_of_object,
                                 a_boolean          honor_virtual,
                                 a_boolean          evaluated,
                                 a_boolean          suppress_access_check)
/*
sym is points to a symbol for a special member function that is invoked
implicitly -- e.g., a copy constructor that is called when a class
object is passed by value or an assignment operator that is called when
another assignment operator function is being created.  Check that the
special member function is accessible and mark the routine entry
referenced.  sym can be a projection symbol.  *pos gives the source
position of the reference.  class_of_object points to the type of the
object for which the function is being called, which is not always the
same as the class of which the function is a member.  This is used to
check protected member access which only applies to objects of a
derived class.  class_of_object may be NULL if protected member access
checking is not needed.  Also, if the routine is compiler generated, it
may still need to be defined, since the definition may have been put
off until an actual reference occurred (e.g., ARM 12.8).  This function
deals with implicitly called constructors, destructors, assignment
operators, and conversion functions.  If honor_virtual is TRUE, and the
function is virtual, the reference is considered to be a virtual call;
that means the access control checking is done, but the IL entry is not
marked as referenced.  If evaluated is FALSE, the reference is within
an unevaluated expression; again, access control checking is done, but
the IL entry is not marked as referenced.  If suppress_access_check is
TRUE, no access control checking is done.
*/
{
  a_symbol_ptr  base_sym = fundamental_symbol_of(sym);
  a_routine_ptr rp = base_sym->variant.routine.ptr;

  check_assertion(rp->special_kind ==
                               (a_special_function_kind)sfk_constructor ||
                  rp->special_kind ==
                               (a_special_function_kind)sfk_destructor ||
                  rp->special_kind ==
                               (a_special_function_kind)sfk_conversion ||
                  (rp->special_kind == (a_special_function_kind)sfk_operator &&
                   rp->opname_kind == (an_opname_kind)onk_assign));
  if (!suppress_access_check) {
    /* Check for accessibility. */
    if (!have_access_to_symbol(sym)) {
      an_error_severity  severity = es_discretionary_error;
      /* Normally an error, but in cfront mode there is a special case
         involving a private base class destructor where we issue a warning. */
      if (any_cfront_mode() &&
          is_cfront_base_class_destructor_access_bug(sym, rp,
                                                     class_of_object)) {
        severity = es_warning;
      }  /* if */
      pos_sy_diagnostic(severity, ec_inaccessible_special_function,
                        pos, sym);
    } else if (class_of_object != NULL) {
      /* Protected members of a base class can only be accessed through an
         object of a derived class. */
      check_protected_member_access(sym, pos, class_of_object);
    }  /* if */
  }  /* if */
  /* Update the symbol and the cross-reference listing. */
  record_symbol_reference((SRK_REFERENCE | SRK_IMPLICIT), base_sym, pos,
                          /*update_il_entry=*/FALSE);
  if (!evaluated) {
    /* Unevaluated expression.  Do not set the IL referenced flag. */
  } else if (rp->is_virtual && honor_virtual) {
    /* Virtual function call.  Do not set the IL referenced flag because the
       call might actually be of an overriding function. */
  } else {
    /* Non-virtual call. */
    mark_routine_referenced(rp);
  }  /* if */
}  /* reference_to_implicitly_invoked_function */


a_boolean reference_to_trivial_default_constructor(
                                              a_type_ptr         class_type,
                                              a_source_position  *pos)
/*
If class_type has an associated trivial default constructor, record a
reference to it -- checking its accessibility, updating the cross-reference
listing if appropriate, and assuring that it is defined, which is done (even
though the function is not actually called) in case the definition has side
effects.  If class_type does have a trivial default constructor (which
should never be the case for PODs, for classes with any user-declared
constructors, or for classes with an implicitly declared nontrivial default
constructor), return TRUE.
*/
{
  a_symbol_ptr   ctor_sym;

  check_assertion(is_class_struct_union_type(class_type));
  ctor_sym = symbol_supplement_for_class(class_type)->
                                            trivial_default_constructor;
  if (ctor_sym != NULL) {
    reference_to_implicitly_invoked_function(ctor_sym, pos, class_type,
                                             /*honor_virtual=*/FALSE,
                                             /*evaluated=*/TRUE,
                                             /*suppress_access_check=*/FALSE);
  }  /* if */
  return (ctor_sym != NULL);
}  /* reference_to_trivial_default_constructor */


/******************************************************************************
*                                                             \  ___  /       *
*                                                               /   \         *
* Edison Design Group C++/C Front End                        - | \^/ | -      *
*                                                               \   /         *
* Proprietary information of Edison Design Group Inc.         /  | |  \       *
* Copyright 1988-1994 Edison Design Group Inc.                   [_]          *
*                                                                             *
******************************************************************************/
